const APP_NAME = "Woof";
const SUPPORT_EMAIL = "woofapp.help@gmail.com";
const EFFECTIVE_DATE = "March 16, 2026";

const baseStyles = `
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      line-height: 1.6;
      color: #1C1C1E;
      background: #FAFAFA;
      padding: 20px;
      padding-bottom: 60px;
    }
    h1 { font-size: 28px; font-weight: 700; margin-bottom: 8px; }
    h2 { font-size: 20px; font-weight: 600; margin-top: 28px; margin-bottom: 8px; }
    p, li { font-size: 15px; margin-bottom: 12px; }
    ul { padding-left: 20px; }
    .date { font-size: 13px; color: #6B7280; margin-bottom: 24px; }
    a { color: #007AFF; text-decoration: none; }
    @media (prefers-color-scheme: dark) {
      body { background: #1C1C1E; color: #F5F5F5; }
      .date { color: #9CA3AF; }
    }
  </style>
`;

export const PRIVACY_HTML = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Privacy Policy - ${APP_NAME}</title>${baseStyles}</head><body>
<h1>Privacy Policy</h1>
<p class="date">Effective: ${EFFECTIVE_DATE}</p>

<p>${APP_NAME} ("we", "our", "us") is a pet food analysis app. This policy explains how we collect, use, and protect your information.</p>

<h2>Information We Collect</h2>
<ul>
  <li><strong>Account information:</strong> email address and display name when you sign in with Apple or Google.</li>
  <li><strong>Photos:</strong> images of pet food labels you scan. Photos are sent to our servers for analysis and are not stored after processing.</li>
  <li><strong>Barcodes:</strong> barcode numbers you scan, used to look up product information.</li>
  <li><strong>Scan history:</strong> product names, scores, and analysis results are stored to provide your history.</li>
  <li><strong>Device information:</strong> device type and OS version for app functionality and troubleshooting.</li>
</ul>

<h2>How We Use Your Information</h2>
<ul>
  <li>Analyze pet food ingredients and provide quality scores using AI.</li>
  <li>Display your scan history.</li>
  <li>Cache analysis results to improve performance.</li>
  <li>Process subscription purchases.</li>
</ul>

<h2>AI-Generated Content</h2>
<p>${APP_NAME} uses artificial intelligence (Anthropic's Claude) to analyze pet food labels and generate ingredient ratings, quality scores, and recommendations. <strong>AI-generated content may contain errors, inaccuracies, or omissions.</strong> Scores and analysis should be treated as informational estimates, not definitive assessments. We do not guarantee the accuracy, completeness, or reliability of any AI-generated analysis. Always verify important dietary decisions with your veterinarian.</p>

<h2>Third-Party Services</h2>
<ul>
  <li><strong>Supabase:</strong> authentication and data storage.</li>
  <li><strong>Anthropic (Claude):</strong> AI-powered ingredient analysis. Label photos are sent to their API for processing.</li>
  <li><strong>Open Pet Food Facts:</strong> product database lookups by barcode.</li>
  <li><strong>RevenueCat:</strong> subscription management.</li>
  <li><strong>Apple / Google:</strong> sign-in authentication.</li>
</ul>

<h2>Data Retention</h2>
<p>Your scan history and cached analyses are retained while your account is active. You can delete your account by contacting us at <a href="mailto:${SUPPORT_EMAIL}">${SUPPORT_EMAIL}</a>.</p>

<h2>Data Security</h2>
<p>We use industry-standard security measures including encrypted connections (HTTPS), server-side API key management, and row-level security policies on our database.</p>

<h2>Children's Privacy</h2>
<p>${APP_NAME} is not directed at children under 13. We do not knowingly collect information from children.</p>

<h2>Changes to This Policy</h2>
<p>We may update this policy from time to time. We will notify you of material changes through the app.</p>

<h2>Contact Us</h2>
<p>Questions? Email us at <a href="mailto:${SUPPORT_EMAIL}">${SUPPORT_EMAIL}</a>.</p>
</body></html>`;

export const TERMS_HTML = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Terms of Use - ${APP_NAME}</title>${baseStyles}</head><body>
<h1>Terms of Use</h1>
<p class="date">Effective: ${EFFECTIVE_DATE}</p>

<p>By using ${APP_NAME} ("the App"), you agree to these terms. If you do not agree, do not use the App.</p>

<h2>Description of Service</h2>
<p>${APP_NAME} is a pet food analysis tool that uses artificial intelligence (AI) to evaluate ingredient labels. All scores, ratings, ingredient assessments, and recommendations are generated by AI and <strong>may contain errors, inaccuracies, or omissions</strong>. Results should be used as an informational guide only, not as veterinary or medical advice.</p>

<h2>AI Disclaimer</h2>
<p><strong>${APP_NAME} is powered by AI and may make mistakes.</strong> The AI analyzes pet food labels based on patterns in its training data and may misidentify ingredients, assign incorrect quality ratings, or provide inaccurate nutritional information. We do not guarantee the accuracy, completeness, or reliability of any analysis. You should independently verify any information that is important to your pet's health or diet.</p>

<h2>Not Veterinary Advice</h2>
<p>The information provided by ${APP_NAME} is for informational purposes only. It is not a substitute for professional veterinary advice, diagnosis, or treatment. Always consult your veterinarian with questions about your pet's diet. Do not make feeding decisions based solely on ${APP_NAME}'s AI-generated analysis.</p>

<h2>Account</h2>
<p>You must sign in with Apple or Google to use the App. You are responsible for maintaining the security of your account.</p>

<h2>Free Scans & Subscriptions</h2>
<ul>
  <li>${APP_NAME} provides 3 free scans with limited results. Free scans show the overall score, quick stats, a summary verdict, and the first 3 ingredients. Full ingredient details, quality breakdown, reviews, and recall history require a paid subscription.</li>
  <li>Some features require a paid subscription (Woof Pro).</li>
  <li>Subscriptions are billed through Apple's App Store or Google Play. There are no free trials — you are charged immediately upon subscribing.</li>
  <li>You can manage or cancel subscriptions in your device's subscription settings.</li>
  <li>Refunds are handled by Apple or Google per their respective policies.</li>
</ul>

<h2>Acceptable Use</h2>
<p>You agree not to:</p>
<ul>
  <li>Use the App for any unlawful purpose.</li>
  <li>Attempt to reverse engineer or tamper with the App.</li>
  <li>Abuse the analysis service with excessive automated requests.</li>
  <li>Redistribute analysis results commercially without permission.</li>
</ul>

<h2>Intellectual Property</h2>
<p>The App, its design, and its content are owned by us and protected by intellectual property laws. Product information sourced from Open Pet Food Facts is used under their open data license.</p>

<h2>Limitation of Liability</h2>
<p>The App is provided "as is" without warranties of any kind. We are not liable for any damages resulting from your use of the App, including but not limited to decisions made based on AI-generated analysis. The AI may produce incorrect or misleading results, and you use the analysis at your own risk.</p>

<h2>Termination</h2>
<p>We may suspend or terminate your access if you violate these terms.</p>

<h2>Changes to Terms</h2>
<p>We may update these terms. Continued use after changes constitutes acceptance.</p>

<h2>Contact</h2>
<p>Questions? Email us at <a href="mailto:${SUPPORT_EMAIL}">${SUPPORT_EMAIL}</a>.</p>
</body></html>`;
