-- 016: Authoritative pet food recall database.
--
-- Populated by scripts/scrape-fda-recalls.js (openFDA food enforcement API).
-- The analyze Edge Function queries this table by brand at scoring time and
-- overrides Claude's inferred recallSeverity/recallHistory when an authoritative
-- record exists. This replaces "whatever Claude remembers from training" with
-- FDA-verified data — removes a significant accuracy risk flagged by the
-- nutritionist reviewer (Eric Schwartz, Paw Power Nutrition).

CREATE TABLE IF NOT EXISTS brand_recalls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Matching keys. brand_normalized is lowercase, trimmed, no punctuation —
  -- same shape the scoring layer uses to look up a brand. brand_display keeps
  -- the original capitalization for UI rendering.
  brand_normalized TEXT NOT NULL,
  brand_display    TEXT NOT NULL,

  -- Recall metadata from the FDA enforcement report.
  recall_date      DATE,
  severity         TEXT NOT NULL CHECK (severity IN ('minor', 'major', 'active')),
  cause            TEXT,                       -- "salmonella", "aflatoxin", "vitamin D toxicity", etc.
  product_name     TEXT,                       -- specific SKU(s) recalled
  reason           TEXT,                       -- short human-readable reason
  status           TEXT DEFAULT 'resolved'     -- "ongoing" | "resolved"
                     CHECK (status IN ('ongoing', 'resolved', 'completed', 'terminated')),

  -- Provenance — so we can re-scrape and diff over time.
  source           TEXT NOT NULL DEFAULT 'fda', -- 'fda' | 'avma' | 'manual'
  source_url       TEXT,
  fda_recall_number TEXT UNIQUE,               -- FDA's internal recall_number when available; dedup key

  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);

-- Primary lookup pattern: "recalls for this brand, sorted most-recent first".
CREATE INDEX IF NOT EXISTS idx_brand_recalls_brand_date
  ON brand_recalls (brand_normalized, recall_date DESC NULLS LAST);

-- Also useful for admin/ops queries.
CREATE INDEX IF NOT EXISTS idx_brand_recalls_severity ON brand_recalls (severity);
CREATE INDEX IF NOT EXISTS idx_brand_recalls_date ON brand_recalls (recall_date DESC);

-- RLS: public read (same pattern as product_data), service role only for writes.
ALTER TABLE brand_recalls ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read brand recalls"
  ON brand_recalls FOR SELECT
  USING (true);

CREATE POLICY "Service role manages brand recalls"
  ON brand_recalls FOR ALL
  USING (auth.role() = 'service_role');

-- Summary RPC — returns the worst-severity recall + count + most-recent-date
-- for a brand. The Edge Function calls this once per analysis to decide whether
-- to override Claude's inferred recallSeverity.
CREATE OR REPLACE FUNCTION get_brand_recall_summary(p_brand_normalized TEXT)
RETURNS TABLE (
  severity         TEXT,
  recall_count     INT,
  most_recent_date DATE,
  oldest_date      DATE,
  summary          TEXT
)
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
  RETURN QUERY
  WITH agg AS (
    SELECT
      -- Severity ordering: active > major > minor. Worst one wins.
      CASE
        WHEN COUNT(*) FILTER (WHERE br.severity = 'active') > 0 THEN 'active'
        WHEN COUNT(*) FILTER (WHERE br.severity = 'major')  > 0 THEN 'major'
        ELSE 'minor'
      END                            AS worst_sev,
      COUNT(*)::INT                  AS n,
      MAX(br.recall_date)            AS max_d,
      MIN(br.recall_date)            AS min_d,
      ARRAY_AGG(DISTINCT br.cause) FILTER (WHERE br.cause IS NOT NULL) AS causes
    FROM brand_recalls br
    WHERE br.brand_normalized = p_brand_normalized
  )
  SELECT
    agg.worst_sev,
    agg.n,
    agg.max_d,
    agg.min_d,
    CASE
      WHEN agg.n = 0 THEN NULL
      WHEN agg.n = 1 THEN 'One recall on record (' || COALESCE(TO_CHAR(agg.max_d, 'YYYY'), 'date unknown') ||
                          CASE WHEN ARRAY_LENGTH(agg.causes, 1) > 0
                               THEN ', ' || agg.causes[1]
                               ELSE '' END || ').'
      ELSE agg.n || ' recalls on record between ' ||
           COALESCE(TO_CHAR(agg.min_d, 'YYYY'), 'unknown') || ' and ' ||
           COALESCE(TO_CHAR(agg.max_d, 'YYYY'), 'unknown') ||
           CASE WHEN ARRAY_LENGTH(agg.causes, 1) > 0
                THEN ' (' || ARRAY_TO_STRING(agg.causes[1:3], ', ') || ')'
                ELSE '' END || '.'
    END AS summary
  FROM agg
  WHERE agg.n > 0;
END;
$$;

-- Grant execute so anon role can call via PostgREST.
GRANT EXECUTE ON FUNCTION get_brand_recall_summary(TEXT) TO anon, authenticated, service_role;
