-- 017: Authoritative per-brand metadata.
--
-- Populated by scripts/seed-brand-metadata.js (hand-curated top ~40 brands)
-- and scripts/scrape-brand-metadata.js (ScrapingBee + GPT extraction for the
-- long tail). The analyze Edge Function queries this at scoring time to
-- override Claude's inferred processingMethod and testingTransparency with
-- verified data, the same way brand_recalls overrides recall fields.
--
-- Directly addresses Eric Schwartz's scoring feedback:
--   - Point 1: cooking temperature / processing method
--   - Point 2: brand testing methods / certification transparency

CREATE TABLE IF NOT EXISTS brand_metadata (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Lookup keys (same normalization as brand_recalls for consistent joins).
  brand_normalized TEXT UNIQUE NOT NULL,
  brand_display    TEXT NOT NULL,

  -- Processing methods this brand is known to use. Most brands use one, some
  -- span multiple lines (Orijen makes both kibble and freeze-dried treats, for
  -- example) so this is an array. primary_processing is the one the brand is
  -- most identified with and is what the EF returns by default.
  processing_methods TEXT[] NOT NULL DEFAULT '{}',
  primary_processing TEXT
    CHECK (primary_processing IN (
      'freeze-dried', 'air-dried', 'raw', 'cold-pressed',
      'baked', 'extruded', 'canned', 'unknown'
    )),

  -- Testing disclosure tier + supporting details + certifications held.
  -- testing_transparency mirrors the 4-value enum the EF already uses.
  testing_transparency TEXT
    CHECK (testing_transparency IN ('high', 'moderate', 'low', 'unknown')),
  testing_details      TEXT,                 -- human-readable summary
  certifications       TEXT[] DEFAULT '{}',  -- SQF, BRC, HACCP, GFSI, AAFCO-feed-trial, etc.
  third_party_tested   BOOLEAN,              -- explicitly disclosed third-party lab testing

  -- Manufacturing context — useful for the UI and for scoring edge cases.
  country_of_manufacture TEXT,               -- "USA", "Canada", "Thailand", etc. (headquartered/manufactured)
  owns_facility          BOOLEAN,            -- true = makes their own food; false = co-packed

  website_url         TEXT,
  quality_page_url    TEXT,                  -- the URL the scraper extracted the info from
  notes               TEXT,                  -- free-text caveats

  -- Provenance
  source              TEXT NOT NULL DEFAULT 'scrape', -- 'seed' | 'scrape' | 'manual'
  confidence          NUMERIC(3, 2)          -- 0.0-1.0 — lower when extracted from thin source pages
    CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),

  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW(),
  last_scraped_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_brand_metadata_brand ON brand_metadata (brand_normalized);

-- RLS matching brand_recalls: public read, service-role write.
ALTER TABLE brand_metadata ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read brand metadata"
  ON brand_metadata FOR SELECT USING (true);

CREATE POLICY "Service role manages brand metadata"
  ON brand_metadata FOR ALL USING (auth.role() = 'service_role');

-- Touch updated_at on every upsert — saves the scraper from having to set it.
CREATE OR REPLACE FUNCTION touch_brand_metadata_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_brand_metadata_updated_at ON brand_metadata;
CREATE TRIGGER trg_brand_metadata_updated_at
  BEFORE UPDATE ON brand_metadata
  FOR EACH ROW EXECUTE FUNCTION touch_brand_metadata_updated_at();
