-- Import one reviewed Dr. Harvey's manufacturer-backed dog food row.
-- Source: outputs/catalog-source-imports/dr-harvey-s/report.json generated 2026-06-23.
-- Included row: dr-harvey-s:810320020820, Garden Veggies Grain-Free Beef.
-- Excluded by importer: bird foods, non-complete products, variant ingredient mismatch,
-- variant nutrient mismatch, non-product rows, and missing ingredient rows.

SELECT count(*) AS upserted_rows
FROM public.upsert_catalog_product_feed((SELECT (
      CASE
        WHEN md5(payload_text) = '0f872f1c65dd61f26d74a42ad0b1600a' THEN payload_text
        ELSE (1 / (CASE WHEN payload_text IS NULL THEN 0 ELSE 0 END))::TEXT
      END
    )::jsonb
    FROM (SELECT convert_from(decode('W3siY2FjaGVfa2V5IjoiZHItaGFydmV5LXM6ODEwMzIwMDIwODIwIiwicHJvZHVjdF9uYW1lIjoiQSBKdXN0IEFkZCBXYXRlciBDb21wbGV0ZSBEaWV0IiwiYnJhbmQiOiJEci4gSGFydmV5J3MiLCJndGluIjoiODEwMzIwMDIwODIwIiwicHJvZHVjdF9saW5lIjoiQSBKdXN0IEFkZCBXYXRlciBDb21wbGV0ZSBEaWV0IiwicGFja2FnZV9zaXplIjoiNSBsYiAvIEJlZWYgUmVjaXBlIiwicGV0X3R5cGUiOiJkb2ciLCJpbmdyZWRpZW50X3RleHQiOiJCZWVmIFJlY2lwZTogQmVlZiwgQnJvY2NvbGksIEdyZWVuIEJlYW5zLCBDYXJyb3RzLCBQdW1wa2luLCBCZWVmIEhlYXJ0cywgQmVlZiBMdW5ncywgQ2hpYSBTZWVkcywgV2hvbGUgRWdnLCBQYXJzbGV5LCBCb3ZpbmUgUGxhc21hLCBCZWV0cywgU3BpbmFjaCwgVHJpY2FsY2l1bSBQaG9zcGhhdGUsIEJsdWViZXJyaWVzLCBDb2NvbnV0LCBDcmFuYmVycmllcywgR2luZ2VyLCBDaW5uYW1vbiwgUmVkIENsb3ZlciwgSW51bGluLCBFZ2dzaGVsbCwgWmluYyBQcm90ZWluYXRlLCBJcm9uIFByb3RlaW5hdGUsIFRhdXJpbmUsIFNlbGVuaXVtIFllYXN0LCBWaXRhbWluIEUgU3VwcGxlbWVudCwgQ29wcGVyIFByb3RlaW5hdGUsIE5pY290aW5pYyBBY2lkLCBNYW5nYW5lc2UgUHJvdGVpbmF0ZSwgTC1DYXJuaXRpbmUsIFZpdGFtaW4gQSBBY2V0YXRlLCBkLUNhbGNpdW0gUGFudG90aGVuYXRlLCBUaGlhbWluZSBNb25vbml0cmF0ZSwgUHlyaWRveGluZSBIeWRyb2NobG9yaWRlLCBSaWJvZmxhdmluIFN1cHBsZW1lbnQsIFZpdGFtaW4gQjEyIFN1cHBsZW1lbnQsIEJpb3RpbiwgQ2FsY2l1bSBJb2RhdGUsIFZpdGFtaW4gRDMgU3VwcGxlbWVudCwgRm9saWMgQWNpZCwgRHJpZWQgQmFjaWxsdXMgY29hZ3VsYW4gRmVybWVudGF0aW9uIFByb2R1Y3QsIERyaWVkIEJhY2lsbHVzIHN1YnRpbGlzIEZlcm1lbnRhdGlvbiBQcm9kdWN0LCBEcmllZCBQaW5lYXBwbGUsIERyaWVkIFBhcGF5YSIsIm51dHJpZW50X3BhbmVsIjoiQ3J1ZGUgUHJvdGVpbiAobWluKTogMjclIENydWRlIEZhdCAobWluKTogNyUgQ3J1ZGUgRmliZXIgKG1heC4pOiA4JSBNb2lzdHVyZSAobWF4Lik6IDEzJSBHcmFpbi1GcmVlIEJlZWYiLCJoYXNfcHVibGlzaGVkX251dHJpZW50cyI6dHJ1ZSwic291cmNlIjoiZHItaGFydmV5LXMiLCJzb3VyY2VfcXVhbGl0eSI6Im1hbnVmYWN0dXJlciIsImluZ3JlZGllbnRfdmVyaWZpY2F0aW9uX3N0YXR1cyI6Im1hbnVmYWN0dXJlciIsImltYWdlX3ZlcmlmaWNhdGlvbl9zdGF0dXMiOiJtYW51ZmFjdHVyZXIiLCJ2ZXJpZmllZF9hdCI6IjIwMjYtMDYtMjNUMDI6NTA6NDcuMjAwWiIsInNvdXJjZV91cmwiOiJodHRwczovL3d3dy5kcmhhcnZleXMuY29tL3Byb2R1Y3RzL2dhcmRlbi12ZWdnaWVzLWdyYWluLWZyZWUtZG9nLWZvb2QiLCJzY3JhcGVkX2F0IjoiMjAyNi0wNi0yM1QwMjo1MDo0Ny4yMDFaIiwiZXhwaXJlc19hdCI6IjIwMjctMDYtMjNUMDI6NTA6NDcuMjAxWiIsImltYWdlX3VybCI6Imh0dHBzOi8vY2RuLnNob3BpZnkuY29tL3MvZmlsZXMvMS8wNTgyLzUwNTUvOTU2MC9maWxlcy9HYXJkZW5fVmVnZ2llc18tX0dyYWluLUZyZWVfaW1hZ2VfMS5qcGc/dj0xNzgxODA1NDcwIiwiaXNfY29tcGxldGVfZm9vZCI6dHJ1ZSwidXBkYXRlZF9hdCI6IjIwMjYtMDYtMjNUMDI6NTA6NDcuMjAxWiJ9XQ==', 'base64'), 'UTF8') AS payload_text) AS payload_guard));

SELECT public.refresh_catalog_acquisition_queue(30, 5000) AS refresh_result;
SELECT public.reconcile_catalog_acquisition_queue() AS reconcile_result;
