INSERT INTO public.catalog_coverage_snapshots (
  snapshot_key, census_started_at, census_completed_at, source_panel,
  required_source_panel, completed_source_panel, denominator_formula_count,
  verified_formula_count, verified_formula_percent, popular_brand_count,
  complete_popular_brand_count, popular_formula_gap_count,
  ingredient_verified_percent, image_verified_percent,
  independent_denominator, passes_source_panel, passes_total_coverage,
  passes_popular_brands, passes_release_gate, details
) VALUES (
  'public-reviewed-major95-exact-gtin-v172:20260727',
  '2026-07-27T16:12:50Z', '2026-07-27T16:15:03.414Z',
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap',
    'petco-retail-catalog','amazon-retail-catalog'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  9756, 6851, 70.22, 86, 38, 2905, 70.22, 70.22,
  true, false, false, false, false,
  jsonb_build_object(
    'searchable_web_evidenced_count', 6851,
    'manufacturer_current_exact_count', 4941,
    'retailer_web_version_count', 1772,
    'web_label_version_count', 138,
    'unresolved_formula_count', 2905,
    'exact_gtin_alias_ledger_count', 53,
    'serving_ready_exact_gtin_alias_count', 43,
    'serving_evidence_repair_queue_count', 10,
    'closed_independent_gap_count_since_v169', 13,
    'canonical_duplicate_formula_collapse_since_v169', 12,
    'net_searchable_formula_gain_since_v169', 1,
    'petsmart_formula_count', 2256,
    'petsmart_searchable_formula_count', 2199,
    'petsmart_formula_gap_count', 57,
    'major95_formula_count', 9175,
    'major95_searchable_formula_count', 6270,
    'major95_formula_gap_count', 2905,
    'major95_inventory_continuity_failure_count', 0,
    'closed_gap_count_blue_buffalo', 5,
    'closed_gap_count_purina_pro_plan', 4,
    'closed_gap_count_royal_canin', 3,
    'closed_gap_count_purina_one', 1,
    'missing_source_panel',
      jsonb_build_array('petco-retail-catalog','amazon-retail-catalog'),
    'second_census_seven_days_apart', false,
    'eric_physical_device_validation', false
  )
)
ON CONFLICT (snapshot_key) DO UPDATE SET
  census_completed_at=excluded.census_completed_at,
  denominator_formula_count=excluded.denominator_formula_count,
  verified_formula_count=excluded.verified_formula_count,
  verified_formula_percent=excluded.verified_formula_percent,
  popular_formula_gap_count=excluded.popular_formula_gap_count,
  details=excluded.details;
