-- Preserve exact Chewy/Walmart ingredient-page evidence independently from
-- canonical manufacturer formulas. Retailer SKU IDs are evidence identifiers,
-- never GTINs, and ingredient versions are kept separate by content hash.

CREATE TABLE IF NOT EXISTS public.catalog_retailer_ingredient_evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_run_id UUID NOT NULL
    REFERENCES public.catalog_import_runs(id) ON DELETE CASCADE,
  source_slug TEXT NOT NULL,
  source_external_id TEXT NOT NULL,
  source_url TEXT NOT NULL,
  product_name TEXT NOT NULL,
  formula_title TEXT NOT NULL DEFAULT '',
  pet_type TEXT NOT NULL DEFAULT 'unknown',
  package_size TEXT NOT NULL DEFAULT '',
  ingredient_text TEXT NOT NULL DEFAULT '',
  ingredient_hash TEXT NOT NULL DEFAULT '',
  ingredient_count INTEGER NOT NULL DEFAULT 0,
  fetch_status TEXT NOT NULL,
  http_status INTEGER,
  attempts INTEGER NOT NULL DEFAULT 0,
  fetch_error TEXT NOT NULL DEFAULT '',
  fetched_at TIMESTAMPTZ,
  evidence_status TEXT NOT NULL,
  validation_reasons TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  content_hash TEXT NOT NULL,
  linked_observation_id BIGINT
    REFERENCES public.catalog_observations(id) ON DELETE SET NULL,
  linked_formula_id BIGINT
    REFERENCES public.catalog_formulas(id) ON DELETE SET NULL,
  promoted_cache_key TEXT,
  is_current BOOLEAN NOT NULL DEFAULT true,
  superseded_at TIMESTAMPTZ,
  raw_payload JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT catalog_retailer_ingredient_source_check
    CHECK (source_slug IN ('chewy', 'walmart')),
  CONSTRAINT catalog_retailer_ingredient_pet_type_check
    CHECK (pet_type IN ('dog', 'cat', 'unknown')),
  CONSTRAINT catalog_retailer_ingredient_count_check
    CHECK (ingredient_count >= 0),
  CONSTRAINT catalog_retailer_ingredient_attempts_check
    CHECK (attempts >= 0),
  CONSTRAINT catalog_retailer_ingredient_content_unique
    UNIQUE (source_slug, source_external_id, content_hash)
);

CREATE INDEX IF NOT EXISTS catalog_retailer_ingredient_run_status_idx
  ON public.catalog_retailer_ingredient_evidence (
    import_run_id,
    evidence_status,
    id
  );

CREATE INDEX IF NOT EXISTS catalog_retailer_ingredient_source_sku_idx
  ON public.catalog_retailer_ingredient_evidence (
    source_slug,
    source_external_id
  );

CREATE INDEX IF NOT EXISTS catalog_retailer_ingredient_formula_idx
  ON public.catalog_retailer_ingredient_evidence (linked_formula_id)
  WHERE linked_formula_id IS NOT NULL;

ALTER TABLE public.catalog_retailer_ingredient_evidence
  ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.catalog_retailer_ingredient_evidence
  FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON TABLE public.catalog_retailer_ingredient_evidence TO service_role;
GRANT USAGE, SELECT
  ON SEQUENCE public.catalog_retailer_ingredient_evidence_id_seq
  TO service_role;

CREATE OR REPLACE FUNCTION public.catalog_normalize_retailer_title(value TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
SET search_path = public
AS $function$
  SELECT btrim(regexp_replace(
    regexp_replace(
      regexp_replace(
        lower(extensions.unaccent(COALESCE(value, ''))),
        '\s*-\s*(chewy\.com|walmart\.com)\s*$',
        '',
        'gi'
      ),
      '(^|[ ,(])(?:case\s+of\s+)?[0-9]+(?:\.[0-9]+)?[ -]?(?:lb|lbs|oz|ounce|ounces|kg|g|gram|grams|ml|fl oz|ct|count|pack|pk|can|cans|tray|trays|pouch|pouches|bag|bags)(?=$|[ ,)])',
      ' ',
      'gi'
    ),
    '[^a-z0-9]+',
    ' ',
    'g'
  ));
$function$;

CREATE OR REPLACE FUNCTION public.stage_retailer_ingredient_evidence(
  p_import_run_id UUID,
  p_payload JSONB
)
RETURNS TABLE(inserted_rows INTEGER, updated_rows INTEGER)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $function$
DECLARE
  v_inserted INTEGER := 0;
  v_updated INTEGER := 0;
BEGIN
  IF p_import_run_id IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.catalog_import_runs
    WHERE id = p_import_run_id
  ) THEN
    RAISE EXCEPTION 'Unknown catalog import run %', p_import_run_id;
  END IF;

  IF jsonb_typeof(COALESCE(p_payload, '[]'::JSONB)) <> 'array' THEN
    RAISE EXCEPTION 'Retailer ingredient payload must be a JSON array';
  END IF;

  WITH input AS (
    SELECT parsed.*
    FROM jsonb_array_elements(COALESCE(p_payload, '[]'::JSONB)) AS item(payload)
    CROSS JOIN LATERAL jsonb_to_record(item.payload) AS parsed(
      source_slug TEXT,
      source_external_id TEXT,
      source_url TEXT,
      product_name TEXT,
      formula_title TEXT,
      pet_type TEXT,
      package_size TEXT,
      ingredient_text TEXT,
      ingredient_hash TEXT,
      ingredient_count INTEGER,
      fetch_status TEXT,
      http_status INTEGER,
      attempts INTEGER,
      fetch_error TEXT,
      fetched_at TIMESTAMPTZ,
      evidence_status TEXT,
      validation_reasons TEXT[],
      content_hash TEXT,
      raw_payload JSONB
    )
  ), upserted AS (
    INSERT INTO public.catalog_retailer_ingredient_evidence (
      import_run_id,
      source_slug,
      source_external_id,
      source_url,
      product_name,
      formula_title,
      pet_type,
      package_size,
      ingredient_text,
      ingredient_hash,
      ingredient_count,
      fetch_status,
      http_status,
      attempts,
      fetch_error,
      fetched_at,
      evidence_status,
      validation_reasons,
      content_hash,
      raw_payload
    )
    SELECT
      p_import_run_id,
      lower(btrim(source_slug)),
      btrim(source_external_id),
      btrim(source_url),
      btrim(product_name),
      btrim(COALESCE(formula_title, '')),
      CASE
        WHEN lower(btrim(COALESCE(pet_type, ''))) IN ('dog', 'cat')
          THEN lower(btrim(pet_type))
        ELSE 'unknown'
      END,
      btrim(COALESCE(package_size, '')),
      btrim(COALESCE(ingredient_text, '')),
      lower(btrim(COALESCE(ingredient_hash, ''))),
      GREATEST(COALESCE(ingredient_count, 0), 0),
      lower(btrim(fetch_status)),
      http_status,
      GREATEST(COALESCE(attempts, 0), 0),
      btrim(COALESCE(fetch_error, '')),
      fetched_at,
      lower(btrim(evidence_status)),
      COALESCE(validation_reasons, ARRAY[]::TEXT[]),
      lower(btrim(content_hash)),
      COALESCE(raw_payload, '{}'::JSONB)
    FROM input
    WHERE lower(btrim(source_slug)) IN ('chewy', 'walmart')
      AND NULLIF(btrim(source_external_id), '') IS NOT NULL
      AND NULLIF(btrim(source_url), '') IS NOT NULL
      AND NULLIF(btrim(product_name), '') IS NOT NULL
      AND NULLIF(btrim(content_hash), '') IS NOT NULL
    ON CONFLICT (source_slug, source_external_id, content_hash)
    DO UPDATE SET
      import_run_id = EXCLUDED.import_run_id,
      source_url = EXCLUDED.source_url,
      product_name = EXCLUDED.product_name,
      formula_title = EXCLUDED.formula_title,
      pet_type = EXCLUDED.pet_type,
      package_size = EXCLUDED.package_size,
      ingredient_text = EXCLUDED.ingredient_text,
      ingredient_hash = EXCLUDED.ingredient_hash,
      ingredient_count = EXCLUDED.ingredient_count,
      fetch_status = EXCLUDED.fetch_status,
      http_status = EXCLUDED.http_status,
      attempts = EXCLUDED.attempts,
      fetch_error = EXCLUDED.fetch_error,
      fetched_at = EXCLUDED.fetched_at,
      evidence_status = CASE
        WHEN public.catalog_retailer_ingredient_evidence.evidence_status = 'promoted'
          THEN 'promoted'
        ELSE EXCLUDED.evidence_status
      END,
      validation_reasons = EXCLUDED.validation_reasons,
      raw_payload = EXCLUDED.raw_payload,
      updated_at = now()
    RETURNING (xmax = 0) AS inserted
  )
  SELECT
    count(*) FILTER (WHERE inserted),
    count(*) FILTER (WHERE NOT inserted)
  INTO v_inserted, v_updated
  FROM upserted;

  UPDATE public.catalog_import_runs
  SET
    updated_at = now(),
    total_candidates = (
      SELECT count(*)
      FROM public.catalog_retailer_ingredient_evidence
      WHERE import_run_id = p_import_run_id
    ),
    accepted_candidates = (
      SELECT count(*)
      FROM public.catalog_retailer_ingredient_evidence
      WHERE import_run_id = p_import_run_id
        AND evidence_status IN (
          'usable_exact_page', 'linked_missing_exact_image',
          'promotable_exact_package', 'promoted'
        )
    ),
    rejected_candidates = (
      SELECT count(*)
      FROM public.catalog_retailer_ingredient_evidence
      WHERE import_run_id = p_import_run_id
        AND evidence_status NOT IN (
          'usable_exact_page', 'linked_missing_exact_image',
          'promotable_exact_package', 'promoted'
        )
    )
  WHERE id = p_import_run_id;

  RETURN QUERY SELECT v_inserted, v_updated;
END;
$function$;

CREATE OR REPLACE FUNCTION public.reconcile_retailer_ingredient_evidence(
  p_import_run_id UUID,
  p_limit INTEGER DEFAULT 500
)
RETURNS TABLE(
  linked_rows INTEGER,
  promoted_rows INTEGER,
  missing_image_rows INTEGER,
  unmatched_rows INTEGER,
  remaining_rows INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $function$
DECLARE
  v_linked INTEGER := 0;
  v_promoted INTEGER := 0;
  v_missing_image INTEGER := 0;
  v_unmatched INTEGER := 0;
  v_remaining INTEGER := 0;
  v_batch_started_at TIMESTAMPTZ := now();
  v_payload JSONB := '[]'::JSONB;
BEGIN
  IF p_limit < 1 OR p_limit > 2000 THEN
    RAISE EXCEPTION 'p_limit must be between 1 and 2000';
  END IF;

  WITH pending AS (
    SELECT evidence.*
    FROM public.catalog_retailer_ingredient_evidence evidence
    WHERE evidence.import_run_id = p_import_run_id
      AND evidence.evidence_status = 'usable_exact_page'
    ORDER BY evidence.id
    LIMIT p_limit
    FOR UPDATE SKIP LOCKED
  ), candidate_matches AS (
    SELECT
      pending.id AS evidence_id,
      observation.id AS observation_id,
      observation.formula_id,
      observation.front_image_url,
      similarity(
        public.catalog_normalize_retailer_title(pending.product_name),
        public.catalog_normalize_retailer_title(observation.product_name)
      ) AS title_similarity,
      row_number() OVER (
        PARTITION BY pending.id
        ORDER BY
          CASE WHEN NULLIF(btrim(observation.front_image_url), '') IS NOT NULL THEN 0 ELSE 1 END,
          similarity(
            public.catalog_normalize_retailer_title(pending.product_name),
            public.catalog_normalize_retailer_title(observation.product_name)
          ) DESC,
          observation.observed_at DESC,
          observation.id DESC
      ) AS match_rank
    FROM pending
    JOIN public.catalog_observations observation
      ON observation.source_external_id = pending.source_external_id
     AND observation.source_slug = CASE pending.source_slug
       WHEN 'chewy' THEN 'chewy-public-sitemap'
       WHEN 'walmart' THEN 'walmart-public-sitemap'
     END
     AND observation.formula_id IS NOT NULL
    JOIN public.catalog_formulas formula
      ON formula.id = observation.formula_id
     AND formula.active
     AND formula.is_complete_food
     AND formula.pet_type = pending.pet_type
    WHERE similarity(
      public.catalog_normalize_retailer_title(pending.product_name),
      public.catalog_normalize_retailer_title(observation.product_name)
    ) >= 0.58
  ), chosen AS (
    SELECT * FROM candidate_matches WHERE match_rank = 1
  ), linked AS (
    UPDATE public.catalog_retailer_ingredient_evidence evidence
    SET
      linked_observation_id = chosen.observation_id,
      linked_formula_id = chosen.formula_id,
      evidence_status = CASE
        WHEN NULLIF(btrim(chosen.front_image_url), '') IS NULL
          THEN 'linked_missing_exact_image'
        ELSE 'promotable_exact_package'
      END,
      updated_at = now()
    FROM chosen
    WHERE evidence.id = chosen.evidence_id
    RETURNING evidence.id
  ), unmatched AS (
    UPDATE public.catalog_retailer_ingredient_evidence evidence
    SET
      evidence_status = 'unmatched_catalog_sku',
      validation_reasons = array_append(
        evidence.validation_reasons,
        'no_unique_exact_catalog_sku_identity'
      ),
      updated_at = now()
    WHERE evidence.id IN (SELECT id FROM pending)
      AND NOT EXISTS (
        SELECT 1 FROM chosen WHERE chosen.evidence_id = evidence.id
      )
    RETURNING evidence.id
  )
  SELECT
    (SELECT count(*) FROM linked),
    (SELECT count(*) FROM unmatched)
  INTO v_linked, v_unmatched;

  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'cache_key',
      'retailer-web:' || evidence.source_slug || ':' || formula.identity_hash || ':' ||
      left(evidence.ingredient_hash, 16),
    'product_name', formula.product_name,
    'brand', formula.brand,
    'gtin', NULL,
    'product_line', formula.product_line,
    'flavor', formula.flavor,
    'life_stage', formula.life_stage,
    'food_form', formula.food_form,
    'package_size', NULL,
    'pet_type', formula.pet_type,
    'ingredients', to_jsonb(regexp_split_to_array(evidence.ingredient_text, '\s*,\s*')),
    'ingredient_text', evidence.ingredient_text,
    'nutritional_info', jsonb_build_object(
      'formula_evidence_tier', 'retailer_web_version',
      'formula_version_provenance', jsonb_build_object(
        'manufacturer_current_equivalence', false,
        'version_status', 'dated_retailer_web_version',
        'gtin_resolution_policy', 'abstain_on_version_conflict',
        'package_identifier', evidence.source_slug || ':' || evidence.source_external_id,
        'ingredient_text_hash', evidence.ingredient_hash,
        'front_image_url', observation.front_image_url,
        'source_url', evidence.source_url,
        'captured_at', evidence.fetched_at,
        'retailer_sku', evidence.source_external_id
      )
    ),
    'nutrient_panel', NULL,
    'has_published_nutrients', false,
    'source', evidence.source_slug || '-retailer-web',
    'source_quality', 'retailer_verified',
    'ingredient_verification_status', 'retailer_verified',
    'image_verification_status', 'retailer_verified',
    'verified_at', evidence.fetched_at,
    'source_url', evidence.source_url,
    'scraped_at', evidence.fetched_at,
    'expires_at', COALESCE(evidence.fetched_at, now()) + interval '180 days',
    'image_url', observation.front_image_url,
    'is_complete_food', true,
    'catalog_exclusion_reason', NULL,
    'updated_at', now()
  )), '[]'::JSONB)
  INTO v_payload
  FROM public.catalog_retailer_ingredient_evidence evidence
  JOIN public.catalog_formulas formula
    ON formula.id = evidence.linked_formula_id
  JOIN public.catalog_observations observation
    ON observation.id = evidence.linked_observation_id
  WHERE evidence.import_run_id = p_import_run_id
    AND evidence.evidence_status = 'promotable_exact_package'
    AND evidence.id IN (
      SELECT id
      FROM public.catalog_retailer_ingredient_evidence
      WHERE import_run_id = p_import_run_id
        AND evidence_status = 'promotable_exact_package'
      ORDER BY id
      LIMIT p_limit
    )
    AND evidence.ingredient_count >= 5
    AND length(evidence.ingredient_text) >= 30
    AND evidence.ingredient_text !~ '(\\.\\.\\.|…)'
    AND NOT public.catalog_has_unbalanced_parentheses(evidence.ingredient_text)
    AND NOT public.catalog_has_ingredient_ocr_artifacts(evidence.ingredient_text)
    AND NULLIF(btrim(observation.front_image_url), '') IS NOT NULL;

  IF jsonb_array_length(v_payload) > 0 THEN
    SELECT count(*) INTO v_promoted
    FROM public.upsert_catalog_product_feed(v_payload);

    UPDATE public.catalog_retailer_ingredient_evidence evidence
    SET
      evidence_status = 'promoted',
      promoted_cache_key =
        'retailer-web:' || evidence.source_slug || ':' || formula.identity_hash || ':' ||
        left(evidence.ingredient_hash, 16),
      updated_at = now()
    FROM public.catalog_formulas formula
    WHERE formula.id = evidence.linked_formula_id
      AND evidence.import_run_id = p_import_run_id
      AND evidence.evidence_status = 'promotable_exact_package'
      AND EXISTS (
        SELECT 1
        FROM public.product_data serving
        WHERE serving.cache_key =
          'retailer-web:' || evidence.source_slug || ':' || formula.identity_hash || ':' ||
          left(evidence.ingredient_hash, 16)
          AND serving.formula_evidence_tier = 'retailer_web_version'
      );

    INSERT INTO public.catalog_skus (
      formula_id,
      gtin,
      package_size,
      source_slug,
      source_external_id,
      source_url,
      active,
      first_observed_at,
      last_observed_at
    )
    SELECT
      evidence.linked_formula_id,
      NULL,
      NULLIF(evidence.package_size, ''),
      evidence.source_slug || '-retailer-web',
      evidence.source_external_id,
      evidence.source_url,
      true,
      COALESCE(evidence.fetched_at, now()),
      COALESCE(evidence.fetched_at, now())
    FROM public.catalog_retailer_ingredient_evidence evidence
    WHERE evidence.import_run_id = p_import_run_id
      AND evidence.evidence_status = 'promoted'
      AND evidence.updated_at >= v_batch_started_at
    ON CONFLICT (source_slug, source_external_id, gtin, package_size)
    DO UPDATE SET
      formula_id = EXCLUDED.formula_id,
      source_url = EXCLUDED.source_url,
      active = true,
      last_observed_at = GREATEST(
        public.catalog_skus.last_observed_at,
        EXCLUDED.last_observed_at
      );

    INSERT INTO public.catalog_field_evidence (
      formula_id,
      observation_id,
      field_name,
      field_value,
      source_url,
      source_authority,
      accepted,
      observed_at,
      content_hash
    )
    SELECT
      evidence.linked_formula_id,
      evidence.linked_observation_id,
      'ingredient_text',
      to_jsonb(evidence.ingredient_text),
      evidence.source_url,
      'retailer_verified',
      false,
      COALESCE(evidence.fetched_at, now()),
      evidence.ingredient_hash
    FROM public.catalog_retailer_ingredient_evidence evidence
    WHERE evidence.import_run_id = p_import_run_id
      AND evidence.evidence_status = 'promoted'
      AND evidence.updated_at >= v_batch_started_at
    ON CONFLICT (formula_id, field_name, source_url, content_hash)
    DO UPDATE SET
      accepted = false,
      observed_at = GREATEST(
        public.catalog_field_evidence.observed_at,
        EXCLUDED.observed_at
      );
  END IF;

  SELECT count(*) INTO v_missing_image
  FROM public.catalog_retailer_ingredient_evidence
  WHERE import_run_id = p_import_run_id
    AND evidence_status = 'linked_missing_exact_image';

  SELECT count(*) INTO v_remaining
  FROM public.catalog_retailer_ingredient_evidence
  WHERE import_run_id = p_import_run_id
    AND evidence_status IN ('usable_exact_page', 'promotable_exact_package');

  UPDATE public.catalog_import_runs
  SET
    updated_at = now(),
    imported_rows = (
      SELECT count(*)
      FROM public.catalog_retailer_ingredient_evidence
      WHERE import_run_id = p_import_run_id
        AND evidence_status = 'promoted'
    ),
    verified_ready_rows = (
      SELECT count(DISTINCT promoted_cache_key)
      FROM public.catalog_retailer_ingredient_evidence
      WHERE import_run_id = p_import_run_id
        AND evidence_status = 'promoted'
    ),
    report = COALESCE(report, '{}'::JSONB) || jsonb_build_object(
      'linked_missing_exact_image', v_missing_image,
      'unmatched_catalog_sku', (
        SELECT count(*)
        FROM public.catalog_retailer_ingredient_evidence
        WHERE import_run_id = p_import_run_id
          AND evidence_status = 'unmatched_catalog_sku'
      ),
      'remaining_reconciliation', v_remaining
    )
  WHERE id = p_import_run_id;

  RETURN QUERY SELECT
    v_linked,
    v_promoted,
    v_missing_image,
    v_unmatched,
    v_remaining;
END;
$function$;

REVOKE ALL ON FUNCTION public.stage_retailer_ingredient_evidence(UUID, JSONB)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.stage_retailer_ingredient_evidence(UUID, JSONB)
  TO service_role;

REVOKE ALL ON FUNCTION public.reconcile_retailer_ingredient_evidence(UUID, INTEGER)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.reconcile_retailer_ingredient_evidence(UUID, INTEGER)
  TO service_role;

REVOKE ALL ON FUNCTION public.catalog_normalize_retailer_title(TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.catalog_normalize_retailer_title(TEXT)
  TO service_role;

COMMENT ON TABLE public.catalog_retailer_ingredient_evidence IS
  'Private, source-versioned exact retailer ingredient-page evidence. Retailer SKU IDs are not GTINs; unsafe or incomplete rows remain quarantined.';
