-- Reconcile eight exact Purina Pro Plan retailer identities to eight
-- already verified manufacturer-current formulas.
--
-- Retailer sitemap titles and reviewed package fronts are identity evidence
-- only. This migration does not update product_data, ingredients, images,
-- formula versions, scoring, or verification tiers. Five Chewy rows have an
-- independently reviewed exact package-front match. Three Walmart rows have
-- complete protected title identities but no retailer image and remain
-- explicitly title-identity-only.

CREATE TEMP TABLE purina_pro_plan_retailer_alias_payload
ON COMMIT DROP
AS
SELECT
  raw.*,
  public.normalize_verified_product_search_query(raw.retailer_title)
    AS normalized_alias
FROM jsonb_to_recordset(
  convert_from(
    decode('W3siYWxpYXNfZm9ybXVsYV9rZXkiOiJwdXJpbmEgcHJvIHBsYW58cHVyaW5hIHBybyBwbGFufHB1cmluYSBwcm8gcGxhbiBjb21wbGV0ZSBlc3NlbnRpYWxzIGFkdWx0IHR1cmtleSBhbmQgdmVnZXRhYmxlIGVudHJlZSBpbiBncmF2eSBjYW5uZWQgY2F0IGZvb2R8Y2F0fGFkdWx0fHdldHx8IiwicmV0YWlsZXJfdGl0bGUiOiJQdXJpbmEgUHJvIFBsYW4gQ29tcGxldGUgRXNzZW50aWFscyBBZHVsdCBUdXJrZXkgJiBWZWdldGFibGUgRW50cmVlIGluIEdyYXZ5IENhbm5lZCBDYXQgRm9vZCIsInJldGFpbGVyX3NvdXJjZV91cmwiOiJodHRwczovL3d3dy5jaGV3eS5jb20vcHVyaW5hLXByby1wbGFuLWNvbXBsZXRlLWVzc2VudGlhbHMvZHAvNDAyMjgxNCIsInJldGFpbGVyX3Byb2R1Y3RfaWQiOiI0MDIyODE0IiwicmV0YWlsZXJfZnJvbnRfaW1hZ2VfdXJsIjoiaHR0cHM6Ly9pbWFnZS5jaGV3eS5jb20vY2F0YWxvZy9nZW5lcmFsL2ltYWdlcy9tb2UvMDY4OTIxYTUtNDRiZC03MWVkLTgwMDAtNTQyYjM1MDQzYWJjLl9WMV8uanBnIiwicmV0YWlsZXJfZnJvbnRfaW1hZ2Vfc2hhMjU2IjoiNWNkMWNhZWU0M2YzNTRhNzlmN2JjNjNjMjAxYmFhMThiYWNmNWE2NjEwYWU2MjA3MDlkMjliZmVkZTRiNGExNCIsInJldGFpbGVyX29ic2VydmVkX2F0IjoiMjAyNi0wNy0yNFQyMToxMjowNC4zNzhaIiwicmV0YWlsZXJfc291cmNlX3NsdWciOiJjaGV3eS1wdWJsaWMtc2l0ZW1hcCIsIm1hbnVhbF9wYWNrYWdlX2ltYWdlX21hdGNoIjp0cnVlLCJyZXZpZXdfbWV0aG9kIjoiZXhhY3RfcHVyaW5hX3Byb19wbGFuX3JldGFpbGVyX2lkZW50aXR5X29ubHkiLCJyZXZpZXdfcmVhc29uIjoiRXhhY3QgcHVibGljIENoZXd5IGZyb250LXBhY2thZ2UgaW1hZ2Ugd2FzIHZpc3VhbGx5IGNvbXBhcmVkIHdpdGggdGhlIGN1cnJlbnQgb2ZmaWNpYWwgZnJvbnQgYW5kIG1hdGNoZXMgdGhlIHNhbWUgYnJhbmQsIHNwZWNpZXMsIGxpZmUgc3RhZ2UsIGZvcm0sIGNvbmRpdGlvbi9wcmVzZW50YXRpb24sIGFuZCByZWNpcGUuIFRoZSByZXRhaWxlciByb3cgaXMgaWRlbnRpdHktb25seTsgY3VycmVudCBpbmdyZWRpZW50cyBhbmQgc2VydmluZyBldmlkZW5jZSByZW1haW4gbWFudWZhY3R1cmVyLWF1dGhvcml0YXRpdmUuIiwidGFyZ2V0X2NhY2hlX2tleSI6Im5lc3RsZS1wdXJpbmEtcHJvLXBsYW46MDM4MTAwMTQzOTkwIiwiZXhwZWN0ZWRfY2F0YWxvZ19mb3JtdWxhX2tleSI6Im5lc3RsZSBwdXJpbmEgcGV0Y2FyZXxwdXJpbmEgcHJvIHBsYW58cHJvIHBsYW4gY29tcGxldGUgZXNzZW50aWFscyB0dXJrZXkgYW5kIHZlZ2V0YWJsZXMgZW50cmVlIGluIGdyYXZ5IHdldCBjYXQgZm9vZHxjYXR8YWR1bHR8d2V0fHR1cmtleSBhbmQgdmVnZXRhYmxlcyBlbnRyZWV8IiwidGFyZ2V0X2JyYW5kIjoiUHVyaW5hIFBybyBQbGFuIiwidGFyZ2V0X3Byb2R1Y3RfbmFtZSI6IlBybyBQbGFuIENvbXBsZXRlIEVzc2VudGlhbHMgVHVya2V5ICYgVmVnZXRhYmxlcyBFbnRyw6llIEluIEdyYXZ5IFdldCBDYXQgRm9vZCIsInRhcmdldF9wcm9kdWN0X2xpbmUiOiJQcm8gUGxhbiBDb21wbGV0ZSBFc3NlbnRpYWxzIiwidGFyZ2V0X2ZsYXZvciI6IlR1cmtleSAmIFZlZ2V0YWJsZXMgRW50csOpZSIsInRhcmdldF9wZXRfdHlwZSI6ImNhdCIsInRhcmdldF9saWZlX3N0YWdlIjoiYWR1bHQiLCJ0YXJnZXRfZm9vZF9mb3JtIjoid2V0IiwidGFyZ2V0X3NvdXJjZV91cmwiOiJodHRwczovL3d3dy5wdXJpbmEuY29tL2NhdHMvc2hvcC9wcm8tcGxhbi1jb21wbGV0ZS1lc3NlbnRpYWxzLXR1cmtleS12ZWdldGFibGUtd2V0LWNhdC1mb29kIiwidGFyZ2V0X2d0aW4iOiIwMzgxMDAxNDM5OTAiLCJ0YXJnZXRfcGFja2FnZV9zaXplIjoiMyBveiIsInRhcmdldF9hcnRpZmFjdF9pbWFnZV91cmwiOiJodHRwczovL3d3dy5wdXJpbmEuY29tL3NpdGVzL2RlZmF1bHQvZmlsZXMvcHJvZHVjdHMvcHJvLXBsYW4tdHVya2V5LXZlZ2V0YWJsZXMtZ3Jhdnktd2V0LWNhdC1mb29kLnBuZyIsInRhcmdldF9hcnRpZmFjdF9pbWFnZV9zaGEyNTYiOiI2NmY5Yjk4NjE4YTY1NjUyNjdhYTc2MTI0MTI4NWJhZDFhMjY0ODEyOTZkNDNjYWY4N2M3NTFjNWQ0NTBkYjU5IiwidGFyZ2V0X2RhdGFiYXNlX2ltYWdlX3VybCI6Imh0dHBzOi8vd3d3LnB1cmluYS5jb20vc2l0ZXMvZGVmYXVsdC9maWxlcy9wcm9kdWN0cy9wcm8tcGxhbi10dXJrZXktdmVnZXRhYmxlcy1ncmF2eS13ZXQtY2F0LWZvb2QucG5nIiwidGFyZ2V0X2luZ3JlZGllbnRfY291bnQiOjM1LCJ0YXJnZXRfZGF0YWJhc2VfaW5ncmVkaWVudF9oYXNoIjoiNzVkODg5ZTk0YjdmNmE1NDJlYzZhYTUzZDgyY2FkMzRjZjFhZDNlODMxZWIyMjM2OGUzYjc0YWI5NTlhNjU1MCIsInRhcmdldF9jYW5vbmljYWxfaW5ncmVkaWVudF9oYXNoIjoiZGEyNWEwZWY2Njk0YzVkZTljYmU3NWRhNjFjYmViMjFmOThiMGM3YjEzMWM0YTE5MTE4ZDVkNzdiZDIyZjc5YyIsInRhcmdldF9yYXdfaW5ncmVkaWVudF9oYXNoIjoiMDkxYWY0MDc1ODVmNzAzODBmNTQ0MGEwNGE0N2RjZThhMzdjYzBhMmI0Yjg2NWQ0MDAzYmEwNjI0ZGM5YmE4ZCIsInRhcmdldF92ZXJpZmllZF9hdCI6IjIwMjYtMDgtMDNUMDY6MjI6NDguNTkxWiIsImlkZW50aXR5X3NpZ25hdHVyZSI6eyJicmFuZCI6InB1cmluYSBwcm8gcGxhbiIsInByb2dyYW1zIjpbImNvbXBsZXRlIGVzc2VudGlhbHMiXSwicGV0X3R5cGUiOiJjYXQiLCJsaWZlX3N0YWdlIjoiYWR1bHQiLCJmb29kX2Zvcm0iOiJ3ZXQiLCJicmVlZF9zaXplIjoic3RhbmRhcmQiLCJncmFpbl9ib3VuZGFyeSI6InVuc3BlY2lmaWVkIiwiY29uZGl0aW9ucyI6W10sInByZXNlbnRhdGlvbnMiOltdLCJwZXJmb3JtYW5jZV9yYXRpbyI6IiIsInJlY2lwZV90ZXJtcyI6WyJ0dXJrZXkiLCJ2ZWdldGFibGVzIl19LCJmb3JtdWxhX2lkX2hpbnQiOjM1MjU5fSx7ImFsaWFzX2Zvcm11bGFfa2V5IjoicHVyaW5hIHBybyBwbGFufHB1cmluYSBwcm8gcGxhbnxwdXJpbmEgcHJvIHBsYW4gd2VpZ2h0IGNvbnRyb2wgYWR1bHQgaGlnaCBwcm90ZWluIGNoaWNrZW4gYW5kIHJpY2UgZW50cmVlIGNhbm5lZCBkb2cgZm9vZHxkb2d8YWR1bHR8d2V0fHwiLCJyZXRhaWxlcl90aXRsZSI6IlB1cmluYSBQcm8gUGxhbiBXZWlnaHQgQ29udHJvbCBBZHVsdCBIaWdoIFByb3RlaW4gQ2hpY2tlbiAmIFJpY2UgRW50cmVlIENhbm5lZCBEb2cgRm9vZCIsInJldGFpbGVyX3NvdXJjZV91cmwiOiJodHRwczovL3d3dy5jaGV3eS5jb20vcHVyaW5hLXByby1wbGFuLXdlaWdodC1jb250cm9sLWFkdWx0L2RwLzExODA1OTAiLCJyZXRhaWxlcl9wcm9kdWN0X2lkIjoiMTE4MDU5MCIsInJldGFpbGVyX2Zyb250X2ltYWdlX3VybCI6Imh0dHBzOi8vaW1hZ2UuY2hld3kuY29tL2NhdGFsb2cvZ2VuZXJhbC9pbWFnZXMvcHVyaW5hLXByby1wbGFuLXdlaWdodC1jb250cm9sLWFkdWx0LWhpZ2gtcHJvdGVpbi1jaGlja2VuLXJpY2UtZW50cmVlLWNhbm5lZC1kb2ctZm9vZC0xM296LWNhbi1jYXNlLW9mLTEyL2ltZy00NDI0NjAuX1YxXy5qcGciLCJyZXRhaWxlcl9mcm9udF9pbWFnZV9zaGEyNTYiOiJiNGVmNjY4MTQxNDRlZTYwNWMyYjI4NGJkNjlmNDcwNmJlOTgxOWY0MGEwYjJkOTgyY2IxMTdlNGNhMzU4YTcwIiwicmV0YWlsZXJfb2JzZXJ2ZWRfYXQiOiIyMDI2LTA3LTI0VDIxOjEyOjA4Ljg3NFoiLCJyZXRhaWxlcl9zb3VyY2Vfc2x1ZyI6ImNoZXd5LXB1YmxpYy1zaXRlbWFwIiwibWFudWFsX3BhY2thZ2VfaW1hZ2VfbWF0Y2giOnRydWUsInJldmlld19tZXRob2QiOiJleGFjdF9wdXJpbmFfcHJvX3BsYW5fcmV0YWlsZXJfaWRlbnRpdHlfb25seSIsInJldmlld19yZWFzb24iOiJUaGUgQ2hld3kgdGl0bGUgdXNlcyB0aGUgb2xkZXIgV2VpZ2h0IENvbnRyb2wgd29yZGluZywgYnV0IGl0cyBleGFjdCBwdWJsaWMgZnJvbnQtcGFja2FnZSBpbWFnZSB2aXNpYmx5IHNheXMgV2VpZ2h0IE1hbmFnZW1lbnQgYW5kIGlzIHZpc3VhbGx5IGlkZW50aWNhbCB0byB0aGUgY3VycmVudCBvZmZpY2lhbCBwYWNrYWdlIGZvciB0aGUgc2FtZSByZWNpcGUsIHNwZWNpZXMsIGxpZmUgc3RhZ2UsIGZvcm0sIGFuZCAxMyBveiBjYW4uIFRoZSByZXRhaWxlciByb3cgaXMgaWRlbnRpdHktb25seTsgbm8gcmV0YWlsZXIgaW5ncmVkaWVudC12ZXJzaW9uIGVxdWl2YWxlbmNlIG9yIHNlcnZpbmcgcmV3cml0ZSBpcyBjbGFpbWVkLiIsInRhcmdldF9jYWNoZV9rZXkiOiJuZXN0bGUtcHVyaW5hLXByby1wbGFuOjAzODEwMDEwMjAwMyIsImV4cGVjdGVkX2NhdGFsb2dfZm9ybXVsYV9rZXkiOiJuZXN0bGUgcHVyaW5hIHBldGNhcmV8cHVyaW5hIHBybyBwbGFufHBybyBwbGFuIGFkdWx0IHdlaWdodCBtYW5hZ2VtZW50IGNoaWNrZW4gYW5kIHJpY2UgZW50cmVlIGluIGdyYXZ5IHdldCBkb2cgZm9vZHxkb2d8YWR1bHR8d2V0fGNoaWNrZW4gYW5kIHJpY2UgZW50cmVlfCIsInRhcmdldF9icmFuZCI6IlB1cmluYSBQcm8gUGxhbiIsInRhcmdldF9wcm9kdWN0X25hbWUiOiJQcm8gUGxhbiBBZHVsdCBXZWlnaHQgTWFuYWdlbWVudCBDaGlja2VuICYgUmljZSBFbnRyw6llIEluIEdyYXZ5IFdldCBEb2cgRm9vZCIsInRhcmdldF9wcm9kdWN0X2xpbmUiOiJQcm8gUGxhbiBBZHVsdCBXZWlnaHQgTWFuYWdlbWVudCIsInRhcmdldF9mbGF2b3IiOiJDaGlja2VuICYgUmljZSBFbnRyw6llIiwidGFyZ2V0X3BldF90eXBlIjoiZG9nIiwidGFyZ2V0X2xpZmVfc3RhZ2UiOiJhZHVsdCIsInRhcmdldF9mb29kX2Zvcm0iOiJ3ZXQiLCJ0YXJnZXRfc291cmNlX3VybCI6Imh0dHBzOi8vd3d3LnB1cmluYS5jb20vZG9ncy9zaG9wL3Byby1wbGFuLXdlaWdodC1tYW5hZ2VtZW50LWNoaWNrZW4tcmljZS1ncmF2eS13ZXQtZG9nLWZvb2QiLCJ0YXJnZXRfZ3RpbiI6IjAzODEwMDEwMjAwMyIsInRhcmdldF9wYWNrYWdlX3NpemUiOiIxMyBveiIsInRhcmdldF9hcnRpZmFjdF9pbWFnZV91cmwiOiJodHRwczovL3d3dy5wdXJpbmEuY29tL3NpdGVzL2RlZmF1bHQvZmlsZXMvcHJvZHVjdHMvMjAyNS0wMS8xcHJvLXBsYW4td2VpZ2h0LW1hbmFnZW1lbnQtY2hpY2tlbi1yaWNlLXdldC1kb2ctZm9vZC0xMy1vei1jYW4ucG5nIiwidGFyZ2V0X2FydGlmYWN0X2ltYWdlX3NoYTI1NiI6ImU2NGQ3OWY5NzMxYzliNjVhYWQ0YTg0NmQ4OTg5N2U4MmRjM2RkYzc1ZjZjNmVjNjZiOTdkMjVkNWY0ZDQwN2EiLCJ0YXJnZXRfZGF0YWJhc2VfaW1hZ2VfdXJsIjoiaHR0cHM6Ly93d3cucHVyaW5hLmNvbS9zaXRlcy9kZWZhdWx0L2ZpbGVzL3Byb2R1Y3RzLzIwMjUtMDEvMXByby1wbGFuLXdlaWdodC1tYW5hZ2VtZW50LWNoaWNrZW4tcmljZS13ZXQtZG9nLWZvb2QtMTMtb3otY2FuLnBuZyIsInRhcmdldF9pbmdyZWRpZW50X2NvdW50IjoyOCwidGFyZ2V0X2RhdGFiYXNlX2luZ3JlZGllbnRfaGFzaCI6Ijc3YmI3Nzk5MDU5ZDFkZmNhNzUwNjI3MjNkNzRmNzE3NGM5Mzc5MGU2YWI5MmRiYTE0YTQ2MDQ3YmQzZDlkZTgiLCJ0YXJnZXRfY2Fub25pY2FsX2luZ3JlZGllbnRfaGFzaCI6ImU3MTBlYzRhYTY0ZGFjNmZhNThkNTQyZDRlMDJlNTJjMTA4ZjExN2M5YzcwYjZmMTI3YTYxOWMxMjVkNjlkOTUiLCJ0YXJnZXRfcmF3X2luZ3JlZGllbnRfaGFzaCI6ImYyNDY2NGM0MmZmOTlmYmRhYzNjODRmYjc4MWExMDU2YWY3ZTk5NDcxYzA5NzhiMjE1NTEwNTQ2ZWYyY2VmZWUiLCJ0YXJnZXRfdmVyaWZpZWRfYXQiOiIyMDI2LTA4LTAzVDA2OjIyOjQ4LjU5MVoiLCJpZGVudGl0eV9zaWduYXR1cmUiOnsiYnJhbmQiOiJwdXJpbmEgcHJvIHBsYW4iLCJwcm9ncmFtcyI6W10sInBldF90eXBlIjoiZG9nIiwibGlmZV9zdGFnZSI6ImFkdWx0IiwiZm9vZF9mb3JtIjoid2V0IiwiYnJlZWRfc2l6ZSI6InN0YW5kYXJkIiwiZ3JhaW5fYm91bmRhcnkiOiJ1bnNwZWNpZmllZCIsImNvbmRpdGlvbnMiOlsid2VpZ2h0IG1hbmFnZW1lbnQiXSwicHJlc2VudGF0aW9ucyI6W10sInBlcmZvcm1hbmNlX3JhdGlvIjoiIiwicmVjaXBlX3Rlcm1zIjpbImNoaWNrZW4iLCJyaWNlIl19LCJmb3JtdWxhX2lkX2hpbnQiOjM1MjM4fSx7ImFsaWFzX2Zvcm11bGFfa2V5IjoicHVyaW5hIHBybyBwbGFufHB1cmluYSBwcm8gcGxhbnxwdXJpbmEgcHJvIHBsYW4gcHVwcHkgbW91c3NlIHN0YXJ0ZXIgY2hpY2tlbiBlbnRyZWUgd2V0IGRvZyBmb29kIGJveHxkb2d8cHVwcHl8d2V0fHwiLCJyZXRhaWxlcl90aXRsZSI6IlB1cmluYSBQcm8gUGxhbiBQdXBweSBNb3Vzc2UgU3RhcnRlciBDaGlja2VuIEVudHJlZSBXZXQgRG9nIEZvb2QsIGJveCIsInJldGFpbGVyX3NvdXJjZV91cmwiOiJodHRwczovL3d3dy5jaGV3eS5jb20vcHVyaW5hLXByby1wbGFuLXB1cHB5LW1vdXNzZS1zdGFydGVyL2RwLzIxODMyMjIiLCJyZXRhaWxlcl9wcm9kdWN0X2lkIjoiMjE4MzIyMiIsInJldGFpbGVyX2Zyb250X2ltYWdlX3VybCI6Imh0dHBzOi8vaW1hZ2UuY2hld3kuY29tL2NhdGFsb2cvZ2VuZXJhbC9pbWFnZXMvbW9lLzA2OTNjNmZlLWFkNmYtNzFiYS04MDAwLWUwN2E3M2MyODE4Ny5fVjFfLmpwZyIsInJldGFpbGVyX2Zyb250X2ltYWdlX3NoYTI1NiI6IjA0NWM2MDU3MjFiNWE2MjdmNTE0YTY0MjlkZDhjMTM4NDYyMGU4MjMzOGE4OTBjZDIwZWI0MDM5YzgxOGFjMjAiLCJyZXRhaWxlcl9vYnNlcnZlZF9hdCI6IjIwMjYtMDctMjRUMjE6MTI6MTIuMjU5WiIsInJldGFpbGVyX3NvdXJjZV9zbHVnIjoiY2hld3ktcHVibGljLXNpdGVtYXAiLCJtYW51YWxfcGFja2FnZV9pbWFnZV9tYXRjaCI6dHJ1ZSwicmV2aWV3X21ldGhvZCI6ImV4YWN0X3B1cmluYV9wcm9fcGxhbl9yZXRhaWxlcl9pZGVudGl0eV9vbmx5IiwicmV2aWV3X3JlYXNvbiI6IkV4YWN0IHB1YmxpYyBDaGV3eSBmcm9udC1wYWNrYWdlIGltYWdlIHdhcyB2aXN1YWxseSBjb21wYXJlZCB3aXRoIHRoZSBjdXJyZW50IG9mZmljaWFsIGZyb250IGFuZCBtYXRjaGVzIHRoZSBzYW1lIGJyYW5kLCBzcGVjaWVzLCBsaWZlIHN0YWdlLCBmb3JtLCBjb25kaXRpb24vcHJlc2VudGF0aW9uLCBhbmQgcmVjaXBlLiBUaGUgcmV0YWlsZXIgcm93IGlzIGlkZW50aXR5LW9ubHk7IGN1cnJlbnQgaW5ncmVkaWVudHMgYW5kIHNlcnZpbmcgZXZpZGVuY2UgcmVtYWluIG1hbnVmYWN0dXJlci1hdXRob3JpdGF0aXZlLiIsInRhcmdldF9jYWNoZV9rZXkiOiJuZXN0bGUtcHVyaW5hLXByby1wbGFuOjAzODEwMDE5MTAwNyIsImV4cGVjdGVkX2NhdGFsb2dfZm9ybXVsYV9rZXkiOiJuZXN0bGUgcHVyaW5hIHBldGNhcmV8cHVyaW5hIHBybyBwbGFufHB1cmluYSBwcm8gcGxhbiBwdXBweSBzdGFydGVyIGNoaWNrZW4gZW50cmVlIHVsdHJhIHNvZnQgbW91c3NlIHdldCBkb2cgZm9vZHxkb2d8cHVwcHl8d2V0fGNoaWNrZW4gZW50cmVlfCIsInRhcmdldF9icmFuZCI6IlB1cmluYSBQcm8gUGxhbiIsInRhcmdldF9wcm9kdWN0X25hbWUiOiJQdXJpbmEgUHJvIFBsYW4gUHVwcHkgU3RhcnRlciBDaGlja2VuIEVudHLDqWUgVWx0cmEgU29mdCBNb3Vzc2UgV2V0IERvZyBGb29kIiwidGFyZ2V0X3Byb2R1Y3RfbGluZSI6IlN0YXJ0ZXIiLCJ0YXJnZXRfZmxhdm9yIjoiQ2hpY2tlbiBFbnRyw6llIiwidGFyZ2V0X3BldF90eXBlIjoiZG9nIiwidGFyZ2V0X2xpZmVfc3RhZ2UiOiJwdXBweSIsInRhcmdldF9mb29kX2Zvcm0iOiJ3ZXQiLCJ0YXJnZXRfc291cmNlX3VybCI6Imh0dHBzOi8vd3d3LnB1cmluYS5jb20vZG9ncy9zaG9wL3Byby1wbGFuLXVsdHJhLXNvZnQtbW91c3NlLWNoaWNrZW4tcHVwcHktd2V0LWRvZy1mb29kIiwidGFyZ2V0X2d0aW4iOiIwMzgxMDAxOTEwMDciLCJ0YXJnZXRfcGFja2FnZV9zaXplIjoiNS41IG96IiwidGFyZ2V0X2FydGlmYWN0X2ltYWdlX3VybCI6Imh0dHBzOi8vd3d3LnB1cmluYS5jb20vc2l0ZXMvZGVmYXVsdC9maWxlcy9wcm9kdWN0cy8yMDI1LTA1L3Byby1wbGFuLXB1cHB5LXN0YXJ0ZXItbW91c3NlLWNoaWNrZW4td2V0LXB1cHB5LWZvb2QucG5nIiwidGFyZ2V0X2FydGlmYWN0X2ltYWdlX3NoYTI1NiI6Ijk3NTlmOWY2MjNmN2RmOGNkMzNkN2VlMzY4N2RjNDYyYjI1YmIyMTQ2MjI0YjdkMTQ1NjM5NTQ1ZmFkZDI4MDgiLCJ0YXJnZXRfZGF0YWJhc2VfaW1hZ2VfdXJsIjoiaHR0cHM6Ly93d3cucHVyaW5hLmNvbS9zaXRlcy9kZWZhdWx0L2ZpbGVzL3Byb2R1Y3RzLzIwMjUtMDUvcHJvLXBsYW4tcHVwcHktc3RhcnRlci1tb3Vzc2UtY2hpY2tlbi13ZXQtcHVwcHktZm9vZC5wbmciLCJ0YXJnZXRfaW5ncmVkaWVudF9jb3VudCI6MjksInRhcmdldF9kYXRhYmFzZV9pbmdyZWRpZW50X2hhc2giOiI4NzFhZDRiYzAwYTFlNDljNjg2NzVmMTU1N2JjNWRmZmE0OTNjZTlhNzAxOTYyZjI4NWU2ODkyOTcyZGIwNjhkIiwidGFyZ2V0X2Nhbm9uaWNhbF9pbmdyZWRpZW50X2hhc2giOiI5MTg1NWYxYjUxNWNmZGNmMWFmZmRiZDRjYzkyNjIyMmE3MWJlOWI2YzA2NDk5MDRkODEyM2Q5MzM4MTQ4YWZhIiwidGFyZ2V0X3Jhd19pbmdyZWRpZW50X2hhc2giOiI2MDk5ZGI5NGUzYjUyMjA5MGQzYWM2MmE1YjU1ZTliMzFjNjg5MGI2NTQyM2ZkMzZlNjU5NWM4NDJkZmMzOTdkIiwidGFyZ2V0X3ZlcmlmaWVkX2F0IjoiMjAyNi0wOC0wM1QwNjoyMjo0OC41OTFaIiwiaWRlbnRpdHlfc2lnbmF0dXJlIjp7ImJyYW5kIjoicHVyaW5hIHBybyBwbGFuIiwicHJvZ3JhbXMiOltdLCJwZXRfdHlwZSI6ImRvZyIsImxpZmVfc3RhZ2UiOiJwdXBweSIsImZvb2RfZm9ybSI6IndldCIsImJyZWVkX3NpemUiOiJzdGFuZGFyZCIsImdyYWluX2JvdW5kYXJ5IjoidW5zcGVjaWZpZWQiLCJjb25kaXRpb25zIjpbXSwicHJlc2VudGF0aW9ucyI6WyJtb3Vzc2UiXSwicGVyZm9ybWFuY2VfcmF0aW8iOiIiLCJyZWNpcGVfdGVybXMiOlsiY2hpY2tlbiJdfSwiZm9ybXVsYV9pZF9oaW50IjozNTMzNX0seyJhbGlhc19mb3JtdWxhX2tleSI6InB1cmluYSBwcm8gcGxhbnxwdXJpbmEgcHJvIHBsYW58cHVyaW5hIHBybyBwbGFuIHNlbnNpdGl2ZSBzdG9tYWNoIGFuZCBza2luIHB1cHB5IHNhbG1vbiBhbmQgcmljZSBlbnRyZWUgY2xhc3NpYyB3ZXQgZG9nIGZvb2R8ZG9nfHB1cHB5fHdldHx8IiwicmV0YWlsZXJfdGl0bGUiOiJQdXJpbmEgUHJvIFBsYW4gU2Vuc2l0aXZlIFN0b21hY2ggJiBTa2luIFB1cHB5IFNhbG1vbiAmIFJpY2UgRW50csOpZSBDbGFzc2ljIFdldCBEb2cgRm9vZCIsInJldGFpbGVyX3NvdXJjZV91cmwiOiJodHRwczovL3d3dy5jaGV3eS5jb20vcHVyaW5hLXByby1wbGFuLXNlbnNpdGl2ZS1zdG9tYWNoL2RwLzIxODMyNTQiLCJyZXRhaWxlcl9wcm9kdWN0X2lkIjoiMjE4MzI1NCIsInJldGFpbGVyX2Zyb250X2ltYWdlX3VybCI6Imh0dHBzOi8vaW1hZ2UuY2hld3kuY29tL2NhdGFsb2cvZ2VuZXJhbC9pbWFnZXMvbW9lLzA2OGJlZWIyLTEwYzAtN2RmZS04MDAwLTc1NzQyYzk1ODNjZC5fVjFfLmpwZyIsInJldGFpbGVyX2Zyb250X2ltYWdlX3NoYTI1NiI6IjQzNmY1YzQwYTNiMjUwYWRmMTJkNTFhNTEzYjQ4YzFkNGVlODEyNDdiYjIwNjM5ZTI2MDBhMDhmZTEzOTU3OGUiLCJyZXRhaWxlcl9vYnNlcnZlZF9hdCI6IjIwMjYtMDctMjRUMjE6MTI6MTUuNzk4WiIsInJldGFpbGVyX3NvdXJjZV9zbHVnIjoiY2hld3ktcHVibGljLXNpdGVtYXAiLCJtYW51YWxfcGFja2FnZV9pbWFnZV9tYXRjaCI6dHJ1ZSwicmV2aWV3X21ldGhvZCI6ImV4YWN0X3B1cmluYV9wcm9fcGxhbl9yZXRhaWxlcl9pZGVudGl0eV9vbmx5IiwicmV2aWV3X3JlYXNvbiI6IkV4YWN0IHB1YmxpYyBDaGV3eSBmcm9udC1wYWNrYWdlIGltYWdlIHdhcyB2aXN1YWxseSBjb21wYXJlZCB3aXRoIHRoZSBjdXJyZW50IG9mZmljaWFsIGZyb250IGFuZCBtYXRjaGVzIHRoZSBzYW1lIGJyYW5kLCBzcGVjaWVzLCBsaWZlIHN0YWdlLCBmb3JtLCBjb25kaXRpb24vcHJlc2VudGF0aW9uLCBhbmQgcmVjaXBlLiBUaGUgcmV0YWlsZXIgcm93IGlzIGlkZW50aXR5LW9ubHk7IGN1cnJlbnQgaW5ncmVkaWVudHMgYW5kIHNlcnZpbmcgZXZpZGVuY2UgcmVtYWluIG1hbnVmYWN0dXJlci1hdXRob3JpdGF0aXZlLiIsInRhcmdldF9jYWNoZV9rZXkiOiJuZXN0bGUtcHVyaW5hLXByby1wbGFuOjAzODEwMDEwNDg4NSIsImV4cGVjdGVkX2NhdGFsb2dfZm9ybXVsYV9rZXkiOiJuZXN0bGUgcHVyaW5hIHBldGNhcmV8cHVyaW5hIHBybyBwbGFufHB1cmluYSBwcm8gcGxhbiBwdXBweSBzZW5zaXRpdmUgc2tpbiBhbmQgc3RvbWFjaCBzYWxtb24gYW5kIHJpY2UgZW50cmVlIGNsYXNzaWMgd2V0IGRvZyBmb29kfGRvZ3xwdXBweXx3ZXR8c2FsbW9uIGFuZCByaWNlIGVudHJlZXwiLCJ0YXJnZXRfYnJhbmQiOiJQdXJpbmEgUHJvIFBsYW4iLCJ0YXJnZXRfcHJvZHVjdF9uYW1lIjoiUHVyaW5hIFBybyBQbGFuIFB1cHB5IFNlbnNpdGl2ZSBTa2luICYgU3RvbWFjaCBTYWxtb24gJiBSaWNlIEVudHLDqWUgQ2xhc3NpYyBXZXQgRG9nIEZvb2QiLCJ0YXJnZXRfcHJvZHVjdF9saW5lIjoiU2Vuc2l0aXZlIFNraW4gJiBTdG9tYWNoIiwidGFyZ2V0X2ZsYXZvciI6IlNhbG1vbiAmIFJpY2UgRW50csOpZSIsInRhcmdldF9wZXRfdHlwZSI6ImRvZyIsInRhcmdldF9saWZlX3N0YWdlIjoicHVwcHkiLCJ0YXJnZXRfZm9vZF9mb3JtIjoid2V0IiwidGFyZ2V0X3NvdXJjZV91cmwiOiJodHRwczovL3d3dy5wdXJpbmEuY29tL2RvZ3Mvc2hvcC9wcm8tcGxhbi1zZW5zaXRpdmUtc2tpbi1zdG9tYWNoLXB1cHB5LXNhbG1vbi13ZXQtZG9nLWZvb2QiLCJ0YXJnZXRfZ3RpbiI6IjAzODEwMDEwNDg4NSIsInRhcmdldF9wYWNrYWdlX3NpemUiOiIxMyBveiIsInRhcmdldF9hcnRpZmFjdF9pbWFnZV91cmwiOiJodHRwczovL3d3dy5wdXJpbmEuY29tL3NpdGVzL2RlZmF1bHQvZmlsZXMvcHJvZHVjdHMvMjAyNS0wNS9wdXJpbmEtcHJvLXBsYW4tYWR1bHQtcHVwcHktc2Vuc2l0aXZlLXNraW4tc3RvbWFjaC1zYWxtb24td2V0LWRvZy1mb29kLnBuZyIsInRhcmdldF9hcnRpZmFjdF9pbWFnZV9zaGEyNTYiOiI2Zjk5MjVkZTM2NjIyZTcyMzdhMjZmZTc5OTcyNzM3Mzc0YWE1ODAyZDU1MmYyN2QxYTQ4MTY2NTQ4MjdhMDkxIiwidGFyZ2V0X2RhdGFiYXNlX2ltYWdlX3VybCI6Imh0dHBzOi8vd3d3LnB1cmluYS5jb20vc2l0ZXMvZGVmYXVsdC9maWxlcy9wcm9kdWN0cy8yMDI1LTA1L3B1cmluYS1wcm8tcGxhbi1hZHVsdC1wdXBweS1zZW5zaXRpdmUtc2tpbi1zdG9tYWNoLXNhbG1vbi13ZXQtZG9nLWZvb2QucG5nIiwidGFyZ2V0X2luZ3JlZGllbnRfY291bnQiOjM1LCJ0YXJnZXRfZGF0YWJhc2VfaW5ncmVkaWVudF9oYXNoIjoiMzc5NWRjMGVhMzUwZjc4NzcwYTkwNzFiYTg0YjRkMmY3NzIxZTc4NzY3MGM0ZGMxODdkMjAxNTFjYjZlOTZlMCIsInRhcmdldF9jYW5vbmljYWxfaW5ncmVkaWVudF9oYXNoIjoiMDNiZjZjMzYyY2ZhM2M4NzAwNGYxOWQ4YjZkMDAyZjg0Y2ZhMDNkOGFmOTI4MWI5MDRiZjQ5MWYzODEyZDA4MyIsInRhcmdldF9yYXdfaW5ncmVkaWVudF9oYXNoIjoiODcxZGExMjM4ODA5N2Y5ODkxYjk1ZDA1ZDhiM2FjYTAxMjI3Y2FkMmVjY2MzZmEyNmQxNjZkNjA2YWE1N2Q4NiIsInRhcmdldF92ZXJpZmllZF9hdCI6IjIwMjYtMDgtMDNUMDY6MjI6NDguNTkxWiIsImlkZW50aXR5X3NpZ25hdHVyZSI6eyJicmFuZCI6InB1cmluYSBwcm8gcGxhbiIsInByb2dyYW1zIjpbXSwicGV0X3R5cGUiOiJkb2ciLCJsaWZlX3N0YWdlIjoicHVwcHkiLCJmb29kX2Zvcm0iOiJ3ZXQiLCJicmVlZF9zaXplIjoic3RhbmRhcmQiLCJncmFpbl9ib3VuZGFyeSI6InVuc3BlY2lmaWVkIiwiY29uZGl0aW9ucyI6WyJzZW5zaXRpdmUgc2tpbiBhbmQgc3RvbWFjaCJdLCJwcmVzZW50YXRpb25zIjpbImNsYXNzaWMiXSwicGVyZm9ybWFuY2VfcmF0aW8iOiIiLCJyZWNpcGVfdGVybXMiOlsic2FsbW9uIiwicmljZSJdfSwiZm9ybXVsYV9pZF9oaW50IjozNTMzNH0seyJhbGlhc19mb3JtdWxhX2tleSI6InB1cmluYSBwcm8gcGxhbnxwdXJpbmEgcHJvIHBsYW58cHVyaW5hIHBybyBwbGFuIHdlaWdodCBjb250cm9sIGFkdWx0IGhpZ2ggcHJvdGVpbiBiZWVmIGFuZCByaWNlIGVudHJlZSBjYW5uZWQgZG9nIGZvb2R8ZG9nfGFkdWx0fHdldHx8IiwicmV0YWlsZXJfdGl0bGUiOiJQdXJpbmEgUHJvIFBsYW4gV2VpZ2h0IENvbnRyb2wgQWR1bHQgSGlnaCBQcm90ZWluIEJlZWYgJiBSaWNlIEVudHJlZSBDYW5uZWQgRG9nIEZvb2QiLCJyZXRhaWxlcl9zb3VyY2VfdXJsIjoiaHR0cHM6Ly93d3cuY2hld3kuY29tL3B1cmluYS1wcm8tcGxhbi13ZWlnaHQtY29udHJvbC1hZHVsdC9kcC8xMTgwNTc0IiwicmV0YWlsZXJfcHJvZHVjdF9pZCI6IjExODA1NzQiLCJyZXRhaWxlcl9mcm9udF9pbWFnZV91cmwiOiJodHRwczovL2ltYWdlLmNoZXd5LmNvbS9jYXRhbG9nL2dlbmVyYWwvaW1hZ2VzL21vZS8wNjc3ODE1NC1kNzhhLTc2MDMtODAwMC1lZTE3NzhhMGY5YjUuX1YxXy5qcGciLCJyZXRhaWxlcl9mcm9udF9pbWFnZV9zaGEyNTYiOiJjYTg5ZTNlYzRhOWQ0ZTg5OThhZWU0NTJhN2NkN2I5ZDRmNDFkOWIwMjFlZWNkZGFlNTRlNzQ5NjFhMWFhMDlkIiwicmV0YWlsZXJfb2JzZXJ2ZWRfYXQiOiIyMDI2LTA3LTI0VDIxOjEyOjI0LjEwM1oiLCJyZXRhaWxlcl9zb3VyY2Vfc2x1ZyI6ImNoZXd5LXB1YmxpYy1zaXRlbWFwIiwibWFudWFsX3BhY2thZ2VfaW1hZ2VfbWF0Y2giOnRydWUsInJldmlld19tZXRob2QiOiJleGFjdF9wdXJpbmFfcHJvX3BsYW5fcmV0YWlsZXJfaWRlbnRpdHlfb25seSIsInJldmlld19yZWFzb24iOiJUaGUgQ2hld3kgdGl0bGUgdXNlcyB0aGUgb2xkZXIgV2VpZ2h0IENvbnRyb2wgd29yZGluZywgYnV0IGl0cyBleGFjdCBwdWJsaWMgZnJvbnQtcGFja2FnZSBpbWFnZSB2aXNpYmx5IHNheXMgV2VpZ2h0IE1hbmFnZW1lbnQgYW5kIGlzIHZpc3VhbGx5IGlkZW50aWNhbCB0byB0aGUgY3VycmVudCBvZmZpY2lhbCBwYWNrYWdlIGZvciB0aGUgc2FtZSByZWNpcGUsIHNwZWNpZXMsIGxpZmUgc3RhZ2UsIGZvcm0sIGFuZCAxMyBveiBjYW4uIFRoZSByZXRhaWxlciByb3cgaXMgaWRlbnRpdHktb25seTsgbm8gcmV0YWlsZXIgaW5ncmVkaWVudC12ZXJzaW9uIGVxdWl2YWxlbmNlIG9yIHNlcnZpbmcgcmV3cml0ZSBpcyBjbGFpbWVkLiIsInRhcmdldF9jYWNoZV9rZXkiOiJuZXN0bGUtcHVyaW5hLXByby1wbGFuOjAzODEwMDEwMjAyNyIsImV4cGVjdGVkX2NhdGFsb2dfZm9ybXVsYV9rZXkiOiJuZXN0bGUgcHVyaW5hIHBldGNhcmV8cHVyaW5hIHBybyBwbGFufHBybyBwbGFuIGFkdWx0IHdlaWdodCBtYW5hZ2VtZW50IGJlZWYgYW5kIHJpY2UgZW50cmVlIGluIGdyYXZ5IHdldCBkb2cgZm9vZHxkb2d8YWR1bHR8d2V0fGJlZWYgYW5kIHJpY2UgZW50cmVlfCIsInRhcmdldF9icmFuZCI6IlB1cmluYSBQcm8gUGxhbiIsInRhcmdldF9wcm9kdWN0X25hbWUiOiJQcm8gUGxhbiBBZHVsdCBXZWlnaHQgTWFuYWdlbWVudCBCZWVmICYgUmljZSBFbnRyw6llIEluIEdyYXZ5IFdldCBEb2cgRm9vZCIsInRhcmdldF9wcm9kdWN0X2xpbmUiOiJQcm8gUGxhbiBBZHVsdCBXZWlnaHQgTWFuYWdlbWVudCIsInRhcmdldF9mbGF2b3IiOiJCZWVmICYgUmljZSBFbnRyw6llIiwidGFyZ2V0X3BldF90eXBlIjoiZG9nIiwidGFyZ2V0X2xpZmVfc3RhZ2UiOiJhZHVsdCIsInRhcmdldF9mb29kX2Zvcm0iOiJ3ZXQiLCJ0YXJnZXRfc291cmNlX3VybCI6Imh0dHBzOi8vd3d3LnB1cmluYS5jb20vZG9ncy9zaG9wL3Byby1wbGFuLXdlaWdodC1tYW5hZ2VtZW50LWJlZWYtcmljZS1ncmF2eS13ZXQtZG9nLWZvb2QiLCJ0YXJnZXRfZ3RpbiI6IjAzODEwMDEwMjAyNyIsInRhcmdldF9wYWNrYWdlX3NpemUiOiIxMyBveiIsInRhcmdldF9hcnRpZmFjdF9pbWFnZV91cmwiOiJodHRwczovL3d3dy5wdXJpbmEuY29tL3NpdGVzL2RlZmF1bHQvZmlsZXMvcHJvZHVjdHMvMjAyNS0wMS8xcHJvLXBsYW4td2VpZ2h0LW1hbmFnZW1lbnQtYmVlZi1yaWNlLXdldC1kb2ctZm9vZC0xMy1vei1jYW4ucG5nIiwidGFyZ2V0X2FydGlmYWN0X2ltYWdlX3NoYTI1NiI6ImFiNDlkZDExNWFhNWE3NGNkMTdmOGJjNjk1NjI5Nzc4YzcwMGUwMzE4YjUwM2VmMmQxM2QzNjIyOGQ4ZjExODgiLCJ0YXJnZXRfZGF0YWJhc2VfaW1hZ2VfdXJsIjoiaHR0cHM6Ly93d3cucHVyaW5hLmNvbS9zaXRlcy9kZWZhdWx0L2ZpbGVzL3Byb2R1Y3RzLzIwMjUtMDEvMXByby1wbGFuLXdlaWdodC1tYW5hZ2VtZW50LWJlZWYtcmljZS13ZXQtZG9nLWZvb2QtMTMtb3otY2FuLnBuZyIsInRhcmdldF9pbmdyZWRpZW50X2NvdW50IjoyOSwidGFyZ2V0X2RhdGFiYXNlX2luZ3JlZGllbnRfaGFzaCI6ImJkNDU3ZjI1MWJkYzI2ZjE3M2YwNzEzZmJmZjBhZTBlZjhhM2Q1ZmJlYTY1ZGNlNzdmMGNjZTUyNWU2YjBmMDciLCJ0YXJnZXRfY2Fub25pY2FsX2luZ3JlZGllbnRfaGFzaCI6ImEyOWY2ZjBkYWMyODgyZWQ1Y2U1MWQwYmE0MmViMzgwOTE3ZTJjNzZiODIwYmUwNTE2MWY4OGRhNzMwMDg0YzQiLCJ0YXJnZXRfcmF3X2luZ3JlZGllbnRfaGFzaCI6ImY4ZWU4OTM1ZjQ4NmRlMjc0Zjc2NTRmMjc3ZjA2MTI4NjRjNzk3MjdiODIyZWMyNjU4MjBlYzYwOGE3OTRmOTIiLCJ0YXJnZXRfdmVyaWZpZWRfYXQiOiIyMDI2LTA4LTAzVDA2OjIyOjQ4LjU5MVoiLCJpZGVudGl0eV9zaWduYXR1cmUiOnsiYnJhbmQiOiJwdXJpbmEgcHJvIHBsYW4iLCJwcm9ncmFtcyI6W10sInBldF90eXBlIjoiZG9nIiwibGlmZV9zdGFnZSI6ImFkdWx0IiwiZm9vZF9mb3JtIjoid2V0IiwiYnJlZWRfc2l6ZSI6InN0YW5kYXJkIiwiZ3JhaW5fYm91bmRhcnkiOiJ1bnNwZWNpZmllZCIsImNvbmRpdGlvbnMiOlsid2VpZ2h0IG1hbmFnZW1lbnQiXSwicHJlc2VudGF0aW9ucyI6W10sInBlcmZvcm1hbmNlX3JhdGlvIjoiIiwicmVjaXBlX3Rlcm1zIjpbImJlZWYiLCJyaWNlIl19LCJmb3JtdWxhX2lkX2hpbnQiOjM1MjM3fSx7ImFsaWFzX2Zvcm11bGFfa2V5IjoicHVyaW5hIHBybyBwbGFufHB1cmluYSBwcm8gcGxhbnxwdXJpbmEgcHJvIHBsYW4gc21hbGwgYnJlZWQgZHJ5IGRvZyBmb29kIHNocmVkZGVkIGJsZW5kIGZvciBhZHVsdHMgY2hpY2tlbiByaWNlfGRvZ3x1bmtub3dufGRyeXx8IiwicmV0YWlsZXJfdGl0bGUiOiJQdXJpbmEgUHJvIFBsYW4gU21hbGwgQnJlZWQgRHJ5IERvZyBGb29kIFNocmVkZGVkIEJsZW5kIGZvciBBZHVsdHMgQ2hpY2tlbiBSaWNlIiwicmV0YWlsZXJfc291cmNlX3VybCI6Imh0dHBzOi8vd3d3LndhbG1hcnQuY29tL2lwL1B1cmluYS1Qcm8tUGxhbi1TbWFsbC1CcmVlZC1EcnktRG9nLUZvb2QtU2hyZWRkZWQtQmxlbmQtZm9yLUFkdWx0cy1DaGlja2VuLVJpY2UtMzQtbGItQmFnLzIwMjY3MDA3MSIsInJldGFpbGVyX3Byb2R1Y3RfaWQiOiIyMDI2NzAwNzEiLCJyZXRhaWxlcl9mcm9udF9pbWFnZV91cmwiOiIiLCJyZXRhaWxlcl9mcm9udF9pbWFnZV9zaGEyNTYiOiIiLCJyZXRhaWxlcl9vYnNlcnZlZF9hdCI6IjIwMjYtMDctMjRUMjE6MTI6NDcuNTI5WiIsInJldGFpbGVyX3NvdXJjZV9zbHVnIjoid2FsbWFydC1wdWJsaWMtc2l0ZW1hcCIsIm1hbnVhbF9wYWNrYWdlX2ltYWdlX21hdGNoIjpmYWxzZSwicmV2aWV3X21ldGhvZCI6ImV4YWN0X3B1cmluYV9wcm9fcGxhbl9yZXRhaWxlcl9pZGVudGl0eV9vbmx5IiwicmV2aWV3X3JlYXNvbiI6IlRoZSBXYWxtYXJ0IHRpdGxlIGNvbnRhaW5zIGEgY29tcGxldGUgcHJvdGVjdGVkIHNwZWNpZXMsIGxpZmUtc3RhZ2UsIGRyeS1mb3JtLCBicmVlZC1zaXplLCBwcmVzZW50YXRpb24sIGFuZCByZWNpcGUgaWRlbnRpdHkgdGhhdCByZXNvbHZlcyB0byBleGFjdGx5IG9uZSBjdXJyZW50IG9mZmljaWFsIGZvcm11bGEuIFRoZSBzaXRlbWFwIHN1cHBsaWVkIG5vIHBhY2thZ2UgaW1hZ2Ugb3IgaW5ncmVkaWVudHMsIHNvIHRoaXMgcmVtYWlucyBpZGVudGl0eS1vbmx5IGFuZCBkb2VzIG5vdCBjbGFpbSByZXRhaWxlciBpbmdyZWRpZW50IHZlcmlmaWNhdGlvbi4iLCJ0YXJnZXRfY2FjaGVfa2V5IjoibmVzdGxlLXB1cmluYS1wcm8tcGxhbjowMzgxMDAxNjA0ODUiLCJleHBlY3RlZF9jYXRhbG9nX2Zvcm11bGFfa2V5IjoibmVzdGxlIHB1cmluYSBwZXRjYXJlfHB1cmluYSBwcm8gcGxhbnxwcm8gcGxhbiBhZHVsdCBzbWFsbCBicmVlZCBzaHJlZGRlZCBibGVuZCBjaGlja2VuIGFuZCByaWNlIGZvcm11bGEgZHJ5IGRvZyBmb29kfGRvZ3xhZHVsdHxkcnl8Y2hpY2tlbiBhbmQgcmljZSBmb3JtdWxhfCIsInRhcmdldF9icmFuZCI6IlB1cmluYSBQcm8gUGxhbiIsInRhcmdldF9wcm9kdWN0X25hbWUiOiJQcm8gUGxhbiBBZHVsdCBTbWFsbCBCcmVlZCBTaHJlZGRlZCBCbGVuZCBDaGlja2VuICYgUmljZSBGb3JtdWxhIERyeSBEb2cgRm9vZCIsInRhcmdldF9wcm9kdWN0X2xpbmUiOiJQcm8gUGxhbiBBZHVsdCBTbWFsbCBCcmVlZCBTaHJlZGRlZCBCbGVuZCIsInRhcmdldF9mbGF2b3IiOiJDaGlja2VuICYgUmljZSBGb3JtdWxhIiwidGFyZ2V0X3BldF90eXBlIjoiZG9nIiwidGFyZ2V0X2xpZmVfc3RhZ2UiOiJhZHVsdCIsInRhcmdldF9mb29kX2Zvcm0iOiJkcnkiLCJ0YXJnZXRfc291cmNlX3VybCI6Imh0dHBzOi8vd3d3LnB1cmluYS5jb20vZG9ncy9zaG9wL3Byby1wbGFuLXNwZWNpYWxpemVkLXNocmVkZGVkLWJsZW5kLXNtYWxsLWJyZWVkLWNoaWNrZW4tcmljZS1wcm9iaW90aWNzLWRyeS1kb2ctZm9vZCIsInRhcmdldF9ndGluIjoiMDM4MTAwMTYwNDg1IiwidGFyZ2V0X3BhY2thZ2Vfc2l6ZSI6IjYgbGIiLCJ0YXJnZXRfYXJ0aWZhY3RfaW1hZ2VfdXJsIjoiaHR0cHM6Ly93d3cucHVyaW5hLmNvbS9zaXRlcy9kZWZhdWx0L2ZpbGVzL3Byb2R1Y3RzLzIwMjUtMDMvcHJvLXBsYW4tc21hbGwtYnJlZWQtc2hyZWRkZWQtYmxlbmQtY2hpY2tlbi1yaWNlLWRyeS1kb2ctZm9vZC0xOC1sYi1iYWdfMC5wbmciLCJ0YXJnZXRfYXJ0aWZhY3RfaW1hZ2Vfc2hhMjU2IjoiZmU5MzJjODE5NGVlNzk5M2Y4MGFjZjNjZDA1MGUyY2JmZTdjODhlODAzNTFkYzdjMTgxYzUxMGQ0YTgxNThkYyIsInRhcmdldF9kYXRhYmFzZV9pbWFnZV91cmwiOiJodHRwczovL3d3dy5wdXJpbmEuY29tL3NpdGVzL2RlZmF1bHQvZmlsZXMvcHJvZHVjdHMvMjAyNS0wMy9wcm8tcGxhbi1zbWFsbC1icmVlZC1zaHJlZGRlZC1ibGVuZC1jaGlja2VuLXJpY2UtZHJ5LWRvZy1mb29kLTE4LWxiLWJhZ18wLnBuZyIsInRhcmdldF9pbmdyZWRpZW50X2NvdW50Ijo0MiwidGFyZ2V0X2RhdGFiYXNlX2luZ3JlZGllbnRfaGFzaCI6IjA0NDdjOGE2OTUzYzRhZTc5NjgxMDFmMWI2Y2YwODZmNWZkZTM0ZTkzYjIzZjU0NGJiZDNmZjJiMGZiYjFkM2QiLCJ0YXJnZXRfY2Fub25pY2FsX2luZ3JlZGllbnRfaGFzaCI6ImJiZTRlZTkyNGZiMGY2N2RiZmM2Y2FlNzRjODg4ZDg0OWRkZDU1ZWY0ZDlkM2U1Njk4Njk0NDNmYjdiMTc5NjkiLCJ0YXJnZXRfcmF3X2luZ3JlZGllbnRfaGFzaCI6IjczMjUxYmVkNzBhNDg1NDU2ZTkyYTJlZDUxOGFhZTBhMmNmMzcyYmU4ZjI0OTA1ZjAzMDBkZmU5OWYwNDU0YjkiLCJ0YXJnZXRfdmVyaWZpZWRfYXQiOiIyMDI2LTA4LTAzVDA2OjIyOjQ4LjU5MVoiLCJpZGVudGl0eV9zaWduYXR1cmUiOnsiYnJhbmQiOiJwdXJpbmEgcHJvIHBsYW4iLCJwcm9ncmFtcyI6W10sInBldF90eXBlIjoiZG9nIiwibGlmZV9zdGFnZSI6ImFkdWx0IiwiZm9vZF9mb3JtIjoiZHJ5IiwiYnJlZWRfc2l6ZSI6InNtYWxsIGJyZWVkIiwiZ3JhaW5fYm91bmRhcnkiOiJ1bnNwZWNpZmllZCIsImNvbmRpdGlvbnMiOltdLCJwcmVzZW50YXRpb25zIjpbInNocmVkZGVkIGJsZW5kIl0sInBlcmZvcm1hbmNlX3JhdGlvIjoiIiwicmVjaXBlX3Rlcm1zIjpbImNoaWNrZW4iLCJyaWNlIl19LCJmb3JtdWxhX2lkX2hpbnQiOjM1MjMzfSx7ImFsaWFzX2Zvcm11bGFfa2V5IjoicHVyaW5hIHBybyBwbGFufHB1cmluYSBwcm8gcGxhbnxwdXJpbmEgcHJvIHBsYW4gcHVwcHkgZHJ5IGRvZyBmb29kIGZvciBsYXJnZSBkb2dzIHVuZGVyIDIgeWVhcnMgcmVhbCBjaGlja2VuIHJpY2V8ZG9nfHB1cHB5fGRyeXx8IiwicmV0YWlsZXJfdGl0bGUiOiJQdXJpbmEgUHJvIFBsYW4gUHVwcHkgRHJ5IERvZyBGb29kIGZvciBMYXJnZSBEb2dzIFVuZGVyIDIgWWVhcnMgUmVhbCBDaGlja2VuIFJpY2UiLCJyZXRhaWxlcl9zb3VyY2VfdXJsIjoiaHR0cHM6Ly93d3cud2FsbWFydC5jb20vaXAvUHVyaW5hLVByby1QbGFuLVB1cHB5LURyeS1Eb2ctRm9vZC1mb3ItTGFyZ2UtRG9ncy1VbmRlci0yLVllYXJzLVJlYWwtQ2hpY2tlbi1SaWNlLTM0LWxiLUJhZy80MjQwODQ1MiIsInJldGFpbGVyX3Byb2R1Y3RfaWQiOiI0MjQwODQ1MiIsInJldGFpbGVyX2Zyb250X2ltYWdlX3VybCI6IiIsInJldGFpbGVyX2Zyb250X2ltYWdlX3NoYTI1NiI6IiIsInJldGFpbGVyX29ic2VydmVkX2F0IjoiMjAyNi0wNy0yNFQyMToxNDowOS45OTVaIiwicmV0YWlsZXJfc291cmNlX3NsdWciOiJ3YWxtYXJ0LXB1YmxpYy1zaXRlbWFwIiwibWFudWFsX3BhY2thZ2VfaW1hZ2VfbWF0Y2giOmZhbHNlLCJyZXZpZXdfbWV0aG9kIjoiZXhhY3RfcHVyaW5hX3Byb19wbGFuX3JldGFpbGVyX2lkZW50aXR5X29ubHkiLCJyZXZpZXdfcmVhc29uIjoiVGhlIFdhbG1hcnQgdGl0bGUgY29udGFpbnMgYSBjb21wbGV0ZSBwcm90ZWN0ZWQgc3BlY2llcywgbGlmZS1zdGFnZSwgZHJ5LWZvcm0sIGJyZWVkLXNpemUsIHByZXNlbnRhdGlvbiwgYW5kIHJlY2lwZSBpZGVudGl0eSB0aGF0IHJlc29sdmVzIHRvIGV4YWN0bHkgb25lIGN1cnJlbnQgb2ZmaWNpYWwgZm9ybXVsYS4gVGhlIHNpdGVtYXAgc3VwcGxpZWQgbm8gcGFja2FnZSBpbWFnZSBvciBpbmdyZWRpZW50cywgc28gdGhpcyByZW1haW5zIGlkZW50aXR5LW9ubHkgYW5kIGRvZXMgbm90IGNsYWltIHJldGFpbGVyIGluZ3JlZGllbnQgdmVyaWZpY2F0aW9uLiIsInRhcmdldF9jYWNoZV9rZXkiOiJuZXN0bGUtcHVyaW5hLXByby1wbGFuOjAzODEwMDEzMjY0MiIsImV4cGVjdGVkX2NhdGFsb2dfZm9ybXVsYV9rZXkiOiJuZXN0bGUgcHVyaW5hIHBldGNhcmV8cHVyaW5hIHBybyBwbGFufHBybyBwbGFuIHB1cHB5IGxhcmdlIGJyZWVkIGNoaWNrZW4gYW5kIHJpY2UgZm9ybXVsYSBkcnkgZG9nIGZvb2R8ZG9nfHB1cHB5fGRyeXxwcm8gcGxhbiBsYXJnZSBicmVlZCBjaGlja2VuIGFuZCByaWNlIGZvcm11bGF8IiwidGFyZ2V0X2JyYW5kIjoiUHVyaW5hIFBybyBQbGFuIiwidGFyZ2V0X3Byb2R1Y3RfbmFtZSI6IlBybyBQbGFuIFB1cHB5IExhcmdlIEJyZWVkIENoaWNrZW4gJiBSaWNlIEZvcm11bGEgRHJ5IERvZyBGb29kIiwidGFyZ2V0X3Byb2R1Y3RfbGluZSI6IlBybyBQbGFuIExhcmdlIEJyZWVkIiwidGFyZ2V0X2ZsYXZvciI6IlBybyBQbGFuIExhcmdlIEJyZWVkIENoaWNrZW4gJiBSaWNlIEZvcm11bGEiLCJ0YXJnZXRfcGV0X3R5cGUiOiJkb2ciLCJ0YXJnZXRfbGlmZV9zdGFnZSI6InB1cHB5IiwidGFyZ2V0X2Zvb2RfZm9ybSI6ImRyeSIsInRhcmdldF9zb3VyY2VfdXJsIjoiaHR0cHM6Ly93d3cucHVyaW5hLmNvbS9kb2dzL3Nob3AvcHJvLXBsYW4tZGV2ZWxvcG1lbnQtcHVwcHktbGFyZ2UtYnJlZWQtY2hpY2tlbi1yaWNlLWRyeS1kb2ctZm9vZCIsInRhcmdldF9ndGluIjoiMDM4MTAwMTMyNjQyIiwidGFyZ2V0X3BhY2thZ2Vfc2l6ZSI6IjE4IGxiIiwidGFyZ2V0X2FydGlmYWN0X2ltYWdlX3VybCI6Imh0dHBzOi8vd3d3LnB1cmluYS5jb20vc2l0ZXMvZGVmYXVsdC9maWxlcy9wcm9kdWN0cy8yMDI0LTEyL3Byb19wbGFuX2xhcmdlX2JyZWVkX3B1cHB5X2NoaWNrZW5fcmljZV9kcnlfZG9nX2Zvb2RfMzRsYi5wbmciLCJ0YXJnZXRfYXJ0aWZhY3RfaW1hZ2Vfc2hhMjU2IjoiZDYzNTdlYjAyODdhMzQ2OTc4M2M5ZTdhMzBjYmZlNDI0MTM3NGNmMmI1OTA2MjIyYzU2ZTczOTFkNDJjYzg2YyIsInRhcmdldF9kYXRhYmFzZV9pbWFnZV91cmwiOiJodHRwczovL3d3dy5wdXJpbmEuY29tL3NpdGVzL2RlZmF1bHQvZmlsZXMvcHJvZHVjdHMvMjAyNC0xMi9wcm9fcGxhbl9sYXJnZV9icmVlZF9wdXBweV9jaGlja2VuX3JpY2VfZHJ5X2RvZ19mb29kXzM0bGIucG5nIiwidGFyZ2V0X2luZ3JlZGllbnRfY291bnQiOjM5LCJ0YXJnZXRfZGF0YWJhc2VfaW5ncmVkaWVudF9oYXNoIjoiMzUxNzc3ZDI0NjQxZTRkYmFjNzQ4ZTlhNDI2OTk1MzI1NDRhOGI2Mzk2MjAxMDQwZjNiNTAzZjNjMTM4ZTQwYiIsInRhcmdldF9jYW5vbmljYWxfaW5ncmVkaWVudF9oYXNoIjoiNGU5MmUxYjRlMTc3NmM1ZDM4NWRkNjFhN2M0NTU4MjNkMmZiYTA4MTdiZGE2MTc4NDUxZTk1ZDY4OWNkZDI1OSIsInRhcmdldF9yYXdfaW5ncmVkaWVudF9oYXNoIjoiZjY3YjI1M2NhNmZmNjI4YmNlMDY5MTY4MzczMDliZmY4YmFiNmVhY2ZmN2VhMWIyNGYwZTcyYjUwMWI3NzgzMSIsInRhcmdldF92ZXJpZmllZF9hdCI6IjIwMjYtMDgtMDNUMDY6MjI6NDguNTkxWiIsImlkZW50aXR5X3NpZ25hdHVyZSI6eyJicmFuZCI6InB1cmluYSBwcm8gcGxhbiIsInByb2dyYW1zIjpbXSwicGV0X3R5cGUiOiJkb2ciLCJsaWZlX3N0YWdlIjoicHVwcHkiLCJmb29kX2Zvcm0iOiJkcnkiLCJicmVlZF9zaXplIjoibGFyZ2UgYnJlZWQiLCJncmFpbl9ib3VuZGFyeSI6InVuc3BlY2lmaWVkIiwiY29uZGl0aW9ucyI6W10sInByZXNlbnRhdGlvbnMiOltdLCJwZXJmb3JtYW5jZV9yYXRpbyI6IiIsInJlY2lwZV90ZXJtcyI6WyJjaGlja2VuIiwicmljZSJdfSwiZm9ybXVsYV9pZF9oaW50IjozNTI4N30seyJhbGlhc19mb3JtdWxhX2tleSI6InB1cmluYSBwcm8gcGxhbnxwdXJpbmEgcHJvIHBsYW58cHVyaW5hIHBybyBwbGFuIHB1cHB5IGRyeSBkb2cgZm9vZCBmb3Igc21hbGwgZG9ncyBoaWdoIHByb3RlaW4gcmVhbCBjaGlja2VuIHJpY2V8ZG9nfHB1cHB5fGRyeXx8IiwicmV0YWlsZXJfdGl0bGUiOiJQdXJpbmEgUHJvIFBsYW4gUHVwcHkgRHJ5IERvZyBGb29kIGZvciBTbWFsbCBEb2dzIEhpZ2ggUHJvdGVpbiBSZWFsIENoaWNrZW4gUmljZSIsInJldGFpbGVyX3NvdXJjZV91cmwiOiJodHRwczovL3d3dy53YWxtYXJ0LmNvbS9pcC9QdXJpbmEtUHJvLVBsYW4tUHVwcHktRHJ5LURvZy1Gb29kLWZvci1TbWFsbC1Eb2dzLUhpZ2gtUHJvdGVpbi1SZWFsLUNoaWNrZW4tUmljZS0xOC1sYi1CYWcvMjIwNDc1OTUiLCJyZXRhaWxlcl9wcm9kdWN0X2lkIjoiMjIwNDc1OTUiLCJyZXRhaWxlcl9mcm9udF9pbWFnZV91cmwiOiIiLCJyZXRhaWxlcl9mcm9udF9pbWFnZV9zaGEyNTYiOiIiLCJyZXRhaWxlcl9vYnNlcnZlZF9hdCI6IjIwMjYtMDctMjRUMjE6MTI6MjYuNzk4WiIsInJldGFpbGVyX3NvdXJjZV9zbHVnIjoid2FsbWFydC1wdWJsaWMtc2l0ZW1hcCIsIm1hbnVhbF9wYWNrYWdlX2ltYWdlX21hdGNoIjpmYWxzZSwicmV2aWV3X21ldGhvZCI6ImV4YWN0X3B1cmluYV9wcm9fcGxhbl9yZXRhaWxlcl9pZGVudGl0eV9vbmx5IiwicmV2aWV3X3JlYXNvbiI6IlRoZSBXYWxtYXJ0IHRpdGxlIGNvbnRhaW5zIGEgY29tcGxldGUgcHJvdGVjdGVkIHNwZWNpZXMsIGxpZmUtc3RhZ2UsIGRyeS1mb3JtLCBicmVlZC1zaXplLCBwcmVzZW50YXRpb24sIGFuZCByZWNpcGUgaWRlbnRpdHkgdGhhdCByZXNvbHZlcyB0byBleGFjdGx5IG9uZSBjdXJyZW50IG9mZmljaWFsIGZvcm11bGEuIFRoZSBzaXRlbWFwIHN1cHBsaWVkIG5vIHBhY2thZ2UgaW1hZ2Ugb3IgaW5ncmVkaWVudHMsIHNvIHRoaXMgcmVtYWlucyBpZGVudGl0eS1vbmx5IGFuZCBkb2VzIG5vdCBjbGFpbSByZXRhaWxlciBpbmdyZWRpZW50IHZlcmlmaWNhdGlvbi4iLCJ0YXJnZXRfY2FjaGVfa2V5IjoibmVzdGxlLXB1cmluYS1wcm8tcGxhbjowMzgxMDAxMTM2ODkiLCJleHBlY3RlZF9jYXRhbG9nX2Zvcm11bGFfa2V5IjoibmVzdGxlIHB1cmluYSBwZXRjYXJlfHB1cmluYSBwcm8gcGxhbnxwcm8gcGxhbiBwdXBweSBzbWFsbCBicmVlZCBjaGlja2VuIGFuZCByaWNlIGZvcm11bGEgZHJ5IGRvZyBmb29kfGRvZ3xwdXBweXxkcnl8cHJvIHBsYW4gc21hbGwgYnJlZWQgY2hpY2tlbiBhbmQgcmljZSBmb3JtdWxhfCIsInRhcmdldF9icmFuZCI6IlB1cmluYSBQcm8gUGxhbiIsInRhcmdldF9wcm9kdWN0X25hbWUiOiJQcm8gUGxhbiBQdXBweSBTbWFsbCBCcmVlZCBDaGlja2VuICYgUmljZSBGb3JtdWxhIERyeSBEb2cgRm9vZCIsInRhcmdldF9wcm9kdWN0X2xpbmUiOiJQcm8gUGxhbiBTbWFsbCBCcmVlZCIsInRhcmdldF9mbGF2b3IiOiJQcm8gUGxhbiBTbWFsbCBCcmVlZCBDaGlja2VuICYgUmljZSBGb3JtdWxhIiwidGFyZ2V0X3BldF90eXBlIjoiZG9nIiwidGFyZ2V0X2xpZmVfc3RhZ2UiOiJwdXBweSIsInRhcmdldF9mb29kX2Zvcm0iOiJkcnkiLCJ0YXJnZXRfc291cmNlX3VybCI6Imh0dHBzOi8vd3d3LnB1cmluYS5jb20vZG9ncy9zaG9wL3Byby1wbGFuLWRldmVsb3BtZW50LXB1cHB5LXNtYWxsLWJyZWVkLWNoaWNrZW4tcmljZS1kcnktZG9nLWZvb2QiLCJ0YXJnZXRfZ3RpbiI6IjAzODEwMDExMzY4OSIsInRhcmdldF9wYWNrYWdlX3NpemUiOiI2IGxiIiwidGFyZ2V0X2FydGlmYWN0X2ltYWdlX3VybCI6Imh0dHBzOi8vd3d3LnB1cmluYS5jb20vc2l0ZXMvZGVmYXVsdC9maWxlcy9wcm9kdWN0cy8yMDI0LTEyL3Byb19wbGFuX3B1cHB5X3NtYWxsX2JyZWVkX2NoaWNrZW5fcmljZV9kcnlfZG9nX2Zvb2RfMThsYi5wbmciLCJ0YXJnZXRfYXJ0aWZhY3RfaW1hZ2Vfc2hhMjU2IjoiZmU2YTRlYmI4NGZkZGZmMzU0YmQ1YzI2YjgzNjYyZTM3NTFjOThmNDVhMjA4MWM2YzIwMzk3NDU1NjY5ZDlkZiIsInRhcmdldF9kYXRhYmFzZV9pbWFnZV91cmwiOiJodHRwczovL3d3dy5wdXJpbmEuY29tL3NpdGVzL2RlZmF1bHQvZmlsZXMvcHJvZHVjdHMvMjAyNC0xMi9wcm9fcGxhbl9wdXBweV9zbWFsbF9icmVlZF9jaGlja2VuX3JpY2VfZHJ5X2RvZ19mb29kXzE4bGIucG5nIiwidGFyZ2V0X2luZ3JlZGllbnRfY291bnQiOjQwLCJ0YXJnZXRfZGF0YWJhc2VfaW5ncmVkaWVudF9oYXNoIjoiMWUwMTNkODhlZDgxNWFiNjkzYjMyNGI2YzFlZGQxN2FiZWQ5NmY1YTk0YjhhZjJlMmVjM2IzODkwYmZlYmY3NSIsInRhcmdldF9jYW5vbmljYWxfaW5ncmVkaWVudF9oYXNoIjoiZWE1Y2JlMDJlNTM3MDEzMmJlOTYxMTY5Zjk5YTIyNGY0MGE1ZGVjYWEwYjhhNDM0MzA3ZDg3ZjdlY2JhNzhjOSIsInRhcmdldF9yYXdfaW5ncmVkaWVudF9oYXNoIjoiODU5MWQ4ZmZhOTQ2ODlkODhhZWNiZTk3NzBmYmUxODg5NzM3MGVjN2Y1ZmM1M2QwMzI1NzAyNDEzODVkMzgxYSIsInRhcmdldF92ZXJpZmllZF9hdCI6IjIwMjYtMDgtMDNUMDY6MjI6NDguNTkxWiIsImlkZW50aXR5X3NpZ25hdHVyZSI6eyJicmFuZCI6InB1cmluYSBwcm8gcGxhbiIsInByb2dyYW1zIjpbXSwicGV0X3R5cGUiOiJkb2ciLCJsaWZlX3N0YWdlIjoicHVwcHkiLCJmb29kX2Zvcm0iOiJkcnkiLCJicmVlZF9zaXplIjoic21hbGwgYnJlZWQiLCJncmFpbl9ib3VuZGFyeSI6InVuc3BlY2lmaWVkIiwiY29uZGl0aW9ucyI6W10sInByZXNlbnRhdGlvbnMiOltdLCJwZXJmb3JtYW5jZV9yYXRpbyI6IiIsInJlY2lwZV90ZXJtcyI6WyJjaGlja2VuIiwicmljZSJdfSwiZm9ybXVsYV9pZF9oaW50IjozNTI5MX1dCg==', 'base64'),
    'utf8'
  )::JSONB
) AS raw(
  alias_formula_key TEXT,
  retailer_title TEXT,
  retailer_source_url TEXT,
  retailer_product_id TEXT,
  retailer_front_image_url TEXT,
  retailer_front_image_sha256 TEXT,
  retailer_observed_at TIMESTAMPTZ,
  retailer_source_slug TEXT,
  manual_package_image_match BOOLEAN,
  review_method TEXT,
  review_reason TEXT,
  target_cache_key TEXT,
  expected_catalog_formula_key TEXT,
  target_brand TEXT,
  target_product_name TEXT,
  target_product_line TEXT,
  target_flavor TEXT,
  target_pet_type TEXT,
  target_life_stage TEXT,
  target_food_form TEXT,
  target_source_url TEXT,
  target_gtin TEXT,
  target_package_size TEXT,
  target_artifact_image_url TEXT,
  target_artifact_image_sha256 TEXT,
  target_database_image_url TEXT,
  target_ingredient_count INTEGER,
  target_database_ingredient_hash TEXT,
  target_canonical_ingredient_hash TEXT,
  target_raw_ingredient_hash TEXT,
  target_verified_at TIMESTAMPTZ,
  identity_signature JSONB,
  formula_id_hint BIGINT
);

DO $payload_guard$
DECLARE
  v_key TEXT;
BEGIN
  IF (SELECT count(*) FROM purina_pro_plan_retailer_alias_payload) <> 8 THEN
    RAISE EXCEPTION 'Purina Pro Plan retailer identity payload must contain 8 rows';
  END IF;

  IF (
    SELECT count(DISTINCT alias_formula_key)
    FROM purina_pro_plan_retailer_alias_payload
  ) <> 8 OR (
    SELECT count(DISTINCT retailer_source_url)
    FROM purina_pro_plan_retailer_alias_payload
  ) <> 8 OR (
    SELECT count(DISTINCT normalized_alias)
    FROM purina_pro_plan_retailer_alias_payload
  ) <> 8 OR (
    SELECT count(DISTINCT target_cache_key)
    FROM purina_pro_plan_retailer_alias_payload
  ) <> 8 OR (
    SELECT count(DISTINCT formula_id_hint)
    FROM purina_pro_plan_retailer_alias_payload
  ) <> 8 THEN
    RAISE EXCEPTION 'Purina Pro Plan retailer identity keys are not unique';
  END IF;

  SELECT alias_formula_key
  INTO v_key
  FROM purina_pro_plan_retailer_alias_payload
  WHERE NULLIF(btrim(alias_formula_key), '') IS NULL
     OR NULLIF(btrim(retailer_title), '') IS NULL
     OR NULLIF(btrim(retailer_source_url), '') IS NULL
     OR NULLIF(btrim(retailer_product_id), '') IS NULL
     OR NULLIF(btrim(review_reason), '') IS NULL
     OR NULLIF(btrim(target_cache_key), '') IS NULL
     OR NULLIF(btrim(expected_catalog_formula_key), '') IS NULL
     OR NULLIF(btrim(target_product_name), '') IS NULL
     OR NULLIF(btrim(target_product_line), '') IS NULL
     OR NULLIF(btrim(target_source_url), '') IS NULL
     OR NULLIF(btrim(target_gtin), '') IS NULL
     OR NULLIF(btrim(target_package_size), '') IS NULL
     OR NULLIF(btrim(target_artifact_image_url), '') IS NULL
     OR NULLIF(btrim(target_database_image_url), '') IS NULL
     OR target_artifact_image_sha256 !~ '^[a-f0-9]{64}$'
     OR target_database_ingredient_hash !~ '^[a-f0-9]{64}$'
     OR target_canonical_ingredient_hash !~ '^[a-f0-9]{64}$'
     OR target_raw_ingredient_hash !~ '^[a-f0-9]{64}$'
     OR target_ingredient_count < 5
     OR target_verified_at IS NULL
     OR normalized_alias IS NULL
     OR length(normalized_alias) < 2
     OR review_method <> 'exact_purina_pro_plan_retailer_identity_only'
  LIMIT 1;

  IF FOUND THEN
    RAISE EXCEPTION 'Purina Pro Plan retailer identity payload is incomplete: %', v_key;
  END IF;

  IF (
    SELECT count(*)
    FROM purina_pro_plan_retailer_alias_payload
    WHERE retailer_source_slug = 'chewy-public-sitemap'
      AND manual_package_image_match
      AND retailer_front_image_url LIKE 'https://image.chewy.com/%'
      AND retailer_front_image_sha256 ~ '^[a-f0-9]{64}$'
  ) <> 5 OR (
    SELECT count(*)
    FROM purina_pro_plan_retailer_alias_payload
    WHERE retailer_source_slug = 'walmart-public-sitemap'
      AND NOT manual_package_image_match
      AND coalesce(retailer_front_image_url, '') = ''
      AND coalesce(retailer_front_image_sha256, '') = ''
  ) <> 3 THEN
    RAISE EXCEPTION 'Purina Pro Plan retailer image/source partition changed';
  END IF;

  SELECT alias_formula_key
  INTO v_key
  FROM purina_pro_plan_retailer_alias_payload
  WHERE lower(btrim(target_brand)) <> 'purina pro plan'
     OR target_pet_type NOT IN ('dog', 'cat')
     OR target_life_stage NOT IN ('adult', 'puppy')
     OR target_food_form NOT IN ('dry', 'wet')
     OR target_source_url NOT LIKE 'https://www.purina.com/%'
     OR target_artifact_image_url NOT LIKE 'https://www.purina.com/%'
     OR target_database_image_url NOT LIKE 'https://www.purina.com/%'
     OR target_gtin !~ '^[0-9]{12,14}$'
     OR identity_signature ->> 'brand' <> 'purina pro plan'
     OR identity_signature ->> 'pet_type' <> target_pet_type
     OR identity_signature ->> 'life_stage' <> target_life_stage
     OR identity_signature ->> 'food_form' <> target_food_form
     OR NULLIF(identity_signature ->> 'breed_size', '') IS NULL
     OR NULLIF(identity_signature ->> 'grain_boundary', '') IS NULL
     OR jsonb_typeof(identity_signature -> 'programs') <> 'array'
     OR jsonb_typeof(identity_signature -> 'conditions') <> 'array'
     OR jsonb_typeof(identity_signature -> 'presentations') <> 'array'
     OR jsonb_typeof(identity_signature -> 'recipe_terms') <> 'array'
     OR jsonb_array_length(identity_signature -> 'recipe_terms') = 0
  LIMIT 1;

  IF FOUND THEN
    RAISE EXCEPTION 'Purina Pro Plan protected identity boundary is unsafe: %', v_key;
  END IF;

  SELECT payload.alias_formula_key
  INTO v_key
  FROM purina_pro_plan_retailer_alias_payload payload
  WHERE NOT EXISTS (
    SELECT 1
    FROM public.product_data product
    WHERE product.cache_key = payload.target_cache_key
      AND lower(btrim(product.brand)) = 'purina pro plan'
      AND lower(btrim(product.product_name)) =
          lower(btrim(payload.target_product_name))
      AND lower(btrim(product.product_line)) =
          lower(btrim(payload.target_product_line))
      AND coalesce(lower(btrim(product.flavor)), '') =
          coalesce(lower(btrim(payload.target_flavor)), '')
      AND product.pet_type = payload.target_pet_type
      AND coalesce(
            nullif(lower(btrim(product.life_stage)), 'unknown'),
            ''
          ) = coalesce(
            nullif(lower(btrim(payload.target_life_stage)), 'unknown'),
            ''
          )
      AND product.food_form = payload.target_food_form
      AND product.source_url = payload.target_source_url
      AND product.image_url = payload.target_database_image_url
      AND product.gtin = payload.target_gtin
      AND product.package_size = payload.target_package_size
      AND product.ingredient_count = payload.target_ingredient_count
      AND coalesce(
            nullif(
              product.formula_version_provenance ->> 'ingredient_text_hash',
              ''
            ),
            encode(
              digest(
                public.catalog_normalize_ingredient_evidence(product.ingredient_text),
                'sha256'
              ),
              'hex'
            )
          ) = payload.target_database_ingredient_hash
      AND encode(
            digest(
              btrim(regexp_replace(product.ingredient_text, '\s+', ' ', 'g')),
              'sha256'
            ),
            'hex'
          ) = payload.target_raw_ingredient_hash
      AND product.formula_evidence_tier = 'manufacturer_current_exact'
      AND product.source_quality = 'manufacturer'
      AND product.ingredient_verification_status = 'manufacturer'
      AND product.image_verification_status = 'manufacturer'
      AND product.is_complete_food
      AND product.catalog_exclusion_reason IS NULL
      AND product.expires_at > now()
      AND product.verified_at IS NOT NULL
  )
  LIMIT 1;

  IF FOUND THEN
    RAISE EXCEPTION 'Purina Pro Plan serving precondition changed: %', v_key;
  END IF;
END
$payload_guard$;

CREATE TEMP TABLE purina_pro_plan_retailer_alias_resolved
ON COMMIT DROP
AS
SELECT
  payload.*,
  formula.id AS formula_id,
  formula.formula_key AS canonical_formula_key,
  formula.identity_hash AS canonical_identity_hash,
  observation.id AS observation_id,
  observation.product_name AS retailer_observation_title
FROM purina_pro_plan_retailer_alias_payload payload
JOIN public.catalog_formulas formula
  ON formula.id = payload.formula_id_hint
 AND formula.formula_key = payload.expected_catalog_formula_key
 AND formula.promoted_cache_key = payload.target_cache_key
 AND formula.active
 AND formula.verification_status = 'verified'
 AND formula.formula_evidence_tier = 'manufacturer_current_exact'
 AND formula.is_complete_food
 AND lower(btrim(formula.brand)) = 'purina pro plan'
 AND lower(btrim(formula.product_name)) =
     lower(btrim(payload.target_product_name))
 AND lower(btrim(formula.product_line)) =
     lower(btrim(payload.target_product_line))
 AND coalesce(lower(btrim(formula.flavor)), '') =
     coalesce(lower(btrim(payload.target_flavor)), '')
 AND formula.pet_type = payload.target_pet_type
 AND coalesce(
       nullif(lower(btrim(formula.life_stage)), 'unknown'),
       ''
     ) = coalesce(
       nullif(lower(btrim(payload.target_life_stage)), 'unknown'),
       ''
     )
 AND formula.food_form = payload.target_food_form
 AND formula.source_url = payload.target_source_url
 AND formula.front_image_url = payload.target_database_image_url
 AND formula.source_authority = 'manufacturer'
 AND formula.ingredient_verification_status = 'manufacturer'
 AND formula.image_verification_status = 'manufacturer'
 AND coalesce(
       nullif(formula.formula_version_provenance ->> 'ingredient_text_hash', ''),
       encode(
         digest(
           public.catalog_normalize_ingredient_evidence(formula.ingredient_text),
           'sha256'
         ),
         'hex'
       )
     ) = payload.target_database_ingredient_hash
 AND encode(
       digest(
         btrim(regexp_replace(formula.ingredient_text, '\s+', ' ', 'g')),
         'sha256'
       ),
       'hex'
     ) = payload.target_raw_ingredient_hash
JOIN LATERAL (
  SELECT exact_observation.id, exact_observation.product_name
  FROM public.catalog_observations exact_observation
  WHERE exact_observation.source_slug = payload.retailer_source_slug
    AND exact_observation.source_external_id = payload.retailer_product_id
    AND lower(regexp_replace(exact_observation.source_url, '/+$', '')) =
        lower(regexp_replace(payload.retailer_source_url, '/+$', ''))
    AND (
      lower(btrim(exact_observation.product_name)) =
          lower(btrim(payload.retailer_title))
      OR (
        payload.retailer_product_id = '2183254'
        AND lower(btrim(exact_observation.product_name)) =
            lower(btrim(payload.retailer_title || ', can,'))
      )
    )
    AND lower(btrim(exact_observation.brand)) = 'purina pro plan'
    AND exact_observation.pet_type = payload.target_pet_type
    AND exact_observation.food_form = payload.target_food_form
    AND exact_observation.formula_evidence_tier = 'unverified'
    AND coalesce(exact_observation.front_image_url, '') =
        coalesce(payload.retailer_front_image_url, '')
  ORDER BY
    exact_observation.observed_at DESC,
    exact_observation.created_at DESC,
    exact_observation.id DESC
  LIMIT 1
) observation ON TRUE;

DO $resolution_guard$
DECLARE
  v_key TEXT;
BEGIN
  SELECT payload.alias_formula_key
  INTO v_key
  FROM purina_pro_plan_retailer_alias_payload payload
  LEFT JOIN (
    SELECT alias_formula_key, count(*) AS candidate_count
    FROM purina_pro_plan_retailer_alias_resolved
    GROUP BY alias_formula_key
  ) resolved USING (alias_formula_key)
  WHERE coalesce(resolved.candidate_count, 0) <> 1
  LIMIT 1;

  IF FOUND THEN
    RAISE EXCEPTION
      'Purina Pro Plan formula/observation did not resolve uniquely: %',
      v_key;
  END IF;

  SELECT resolved.alias_formula_key
  INTO v_key
  FROM purina_pro_plan_retailer_alias_resolved resolved
  JOIN public.catalog_formula_aliases existing
    USING (alias_formula_key)
  WHERE existing.formula_id <> resolved.formula_id
  LIMIT 1;

  IF FOUND THEN
    RAISE EXCEPTION 'Purina Pro Plan formula alias collision: %', v_key;
  END IF;

  SELECT resolved.alias_formula_key
  INTO v_key
  FROM purina_pro_plan_retailer_alias_resolved resolved
  JOIN public.catalog_verified_product_search_aliases existing
    ON existing.active
   AND existing.normalized_alias = resolved.normalized_alias
  WHERE existing.cache_key <> resolved.target_cache_key
  LIMIT 1;

  IF FOUND THEN
    RAISE EXCEPTION 'Purina Pro Plan search alias collision: %', v_key;
  END IF;
END
$resolution_guard$;

INSERT INTO public.catalog_formula_aliases (
  alias_formula_key,
  formula_id,
  identity_hash,
  match_reason,
  source_url,
  metadata,
  updated_at
)
SELECT
  resolved.alias_formula_key,
  resolved.formula_id,
  resolved.canonical_identity_hash,
  'manual_review',
  resolved.retailer_source_url,
  jsonb_build_object(
    'source', 'purina_pro_plan_exact_retailer_identity_reconciliation_20260804',
    'review_method', resolved.review_method,
    'review_reason', resolved.review_reason,
    'retailer_identity_only', TRUE,
    'retailer_ingredient_verification', FALSE,
    'manual_package_image_match', resolved.manual_package_image_match,
    'retailer_source_slug', resolved.retailer_source_slug,
    'retailer_product_id', resolved.retailer_product_id,
    'retailer_title', resolved.retailer_title,
    'retailer_observation_title', resolved.retailer_observation_title,
    'retailer_source_url', resolved.retailer_source_url,
    'retailer_front_image_url', resolved.retailer_front_image_url,
    'retailer_front_image_sha256', resolved.retailer_front_image_sha256,
    'retailer_observed_at', resolved.retailer_observed_at,
    'official_source_url', resolved.target_source_url,
    'official_artifact_image_url', resolved.target_artifact_image_url,
    'official_artifact_image_sha256',
      resolved.target_artifact_image_sha256,
    'official_database_image_url', resolved.target_database_image_url,
    'official_cache_key', resolved.target_cache_key,
    'official_gtin', resolved.target_gtin,
    'official_package_size', resolved.target_package_size,
    'canonical_formula_key', resolved.canonical_formula_key,
    'database_ingredient_text_hash',
      resolved.target_database_ingredient_hash,
    'canonical_artifact_ingredient_hash',
      resolved.target_canonical_ingredient_hash,
    'raw_current_ingredient_hash', resolved.target_raw_ingredient_hash,
    'ingredient_count', resolved.target_ingredient_count,
    'identity_signature', resolved.identity_signature,
    'shelf_brand_boundary', resolved.target_brand,
    'species_boundary', resolved.target_pet_type,
    'life_stage_boundary', resolved.target_life_stage,
    'food_form_boundary', resolved.target_food_form,
    'package_size_is_sku_only', TRUE,
    'ingredient_or_image_rewrite', FALSE,
    'reviewed_at', now()
  ),
  now()
FROM purina_pro_plan_retailer_alias_resolved resolved
ON CONFLICT (alias_formula_key) DO UPDATE
SET formula_id = EXCLUDED.formula_id,
    identity_hash = EXCLUDED.identity_hash,
    match_reason = EXCLUDED.match_reason,
    source_url = EXCLUDED.source_url,
    metadata = public.catalog_formula_aliases.metadata || EXCLUDED.metadata,
    updated_at = now()
WHERE public.catalog_formula_aliases.formula_id = EXCLUDED.formula_id;

INSERT INTO public.catalog_verified_product_search_aliases (
  cache_key,
  alias_text,
  normalized_alias,
  source_url,
  source_authority,
  evidence_observed_at,
  provenance,
  active,
  updated_at
)
SELECT
  resolved.target_cache_key,
  resolved.retailer_title,
  resolved.normalized_alias,
  resolved.retailer_source_url,
  'retailer_identity',
  resolved.retailer_observed_at,
  jsonb_build_object(
    'source', 'purina_pro_plan_exact_retailer_identity_reconciliation_20260804',
    'review_method', resolved.review_method,
    'retailer_identity_only', TRUE,
    'retailer_ingredient_verification', FALSE,
    'manual_package_image_match', resolved.manual_package_image_match,
    'retailer_source_slug', resolved.retailer_source_slug,
    'retailer_product_id', resolved.retailer_product_id,
    'retailer_source_url', resolved.retailer_source_url,
    'retailer_observation_title', resolved.retailer_observation_title,
    'retailer_front_image_url', resolved.retailer_front_image_url,
    'retailer_front_image_sha256', resolved.retailer_front_image_sha256,
    'official_source_url', resolved.target_source_url,
    'official_artifact_image_url', resolved.target_artifact_image_url,
    'official_artifact_image_sha256',
      resolved.target_artifact_image_sha256,
    'official_database_image_url', resolved.target_database_image_url,
    'formula_id', resolved.formula_id,
    'canonical_formula_key', resolved.canonical_formula_key,
    'database_ingredient_text_hash',
      resolved.target_database_ingredient_hash,
    'canonical_artifact_ingredient_hash',
      resolved.target_canonical_ingredient_hash,
    'raw_current_ingredient_hash', resolved.target_raw_ingredient_hash,
    'identity_signature', resolved.identity_signature,
    'shelf_brand_boundary', resolved.target_brand,
    'species_boundary', resolved.target_pet_type,
    'life_stage_boundary', resolved.target_life_stage,
    'food_form_boundary', resolved.target_food_form,
    'ingredient_or_image_rewrite', FALSE
  ),
  TRUE,
  now()
FROM purina_pro_plan_retailer_alias_resolved resolved
ON CONFLICT (normalized_alias) WHERE active DO UPDATE
SET cache_key = EXCLUDED.cache_key,
    alias_text = EXCLUDED.alias_text,
    source_url = EXCLUDED.source_url,
    source_authority = EXCLUDED.source_authority,
    evidence_observed_at = EXCLUDED.evidence_observed_at,
    provenance =
      public.catalog_verified_product_search_aliases.provenance
      || EXCLUDED.provenance,
    updated_at = now()
WHERE public.catalog_verified_product_search_aliases.cache_key =
      EXCLUDED.cache_key;

INSERT INTO public.catalog_field_evidence (
  formula_id,
  observation_id,
  field_name,
  field_value,
  source_url,
  source_authority,
  accepted,
  observed_at,
  content_hash
)
SELECT
  resolved.formula_id,
  resolved.observation_id,
  'retailer_exact_identity_alias',
  jsonb_build_object(
    'source', 'purina_pro_plan_exact_retailer_identity_reconciliation_20260804',
    'review_method', resolved.review_method,
    'review_reason', resolved.review_reason,
    'retailer_identity_only', TRUE,
    'retailer_ingredient_verification', FALSE,
    'manual_package_image_match', resolved.manual_package_image_match,
    'retailer_title', resolved.retailer_title,
    'retailer_observation_title', resolved.retailer_observation_title,
    'retailer_product_id', resolved.retailer_product_id,
    'retailer_source_slug', resolved.retailer_source_slug,
    'retailer_front_image_url', resolved.retailer_front_image_url,
    'retailer_front_image_sha256', resolved.retailer_front_image_sha256,
    'official_source_url', resolved.target_source_url,
    'official_artifact_image_url', resolved.target_artifact_image_url,
    'official_artifact_image_sha256',
      resolved.target_artifact_image_sha256,
    'official_database_image_url', resolved.target_database_image_url,
    'official_cache_key', resolved.target_cache_key,
    'official_gtin', resolved.target_gtin,
    'official_package_size', resolved.target_package_size,
    'canonical_formula_key', resolved.canonical_formula_key,
    'database_ingredient_text_hash',
      resolved.target_database_ingredient_hash,
    'canonical_artifact_ingredient_hash',
      resolved.target_canonical_ingredient_hash,
    'raw_current_ingredient_hash', resolved.target_raw_ingredient_hash,
    'identity_signature', resolved.identity_signature,
    'shelf_brand_boundary', resolved.target_brand,
    'species_boundary', resolved.target_pet_type,
    'life_stage_boundary', resolved.target_life_stage,
    'food_form_boundary', resolved.target_food_form,
    'package_size_is_sku_only', TRUE,
    'ingredient_or_image_rewrite', FALSE
  ),
  resolved.retailer_source_url,
  'retailer_identity',
  TRUE,
  resolved.retailer_observed_at,
  encode(
    digest(
      resolved.formula_id::TEXT
      || '|purina_pro_plan_retailer_identity|'
      || resolved.alias_formula_key
      || '|'
      || resolved.retailer_source_url
      || '|'
      || resolved.target_database_ingredient_hash
      || '|'
      || resolved.target_raw_ingredient_hash,
      'sha256'
    ),
    'hex'
  )
FROM purina_pro_plan_retailer_alias_resolved resolved
ON CONFLICT (
  formula_id,
  field_name,
  source_url,
  content_hash
) DO UPDATE
SET observation_id = EXCLUDED.observation_id,
    field_value = EXCLUDED.field_value,
    source_authority = EXCLUDED.source_authority,
    accepted = TRUE,
    observed_at = EXCLUDED.observed_at;

DO $postconditions$
DECLARE
  v_resolved RECORD;
  v_top_cache_key TEXT;
  v_key TEXT;
BEGIN
  IF (
    SELECT count(*)
    FROM purina_pro_plan_retailer_alias_resolved resolved
    JOIN public.catalog_formula_aliases alias
      USING (alias_formula_key)
    WHERE alias.formula_id = resolved.formula_id
      AND alias.match_reason = 'manual_review'
      AND alias.metadata ->> 'source' =
          'purina_pro_plan_exact_retailer_identity_reconciliation_20260804'
      AND alias.metadata ->> 'review_method' =
          'exact_purina_pro_plan_retailer_identity_only'
      AND (alias.metadata ->> 'retailer_identity_only')::BOOLEAN
      AND NOT (alias.metadata ->> 'retailer_ingredient_verification')::BOOLEAN
  ) <> 8 THEN
    RAISE EXCEPTION 'Purina Pro Plan formula alias postcondition failed';
  END IF;

  IF (
    SELECT count(*)
    FROM purina_pro_plan_retailer_alias_resolved resolved
    JOIN public.catalog_verified_product_search_aliases alias
      ON alias.active
     AND alias.normalized_alias = resolved.normalized_alias
    WHERE alias.cache_key = resolved.target_cache_key
      AND alias.source_authority = 'retailer_identity'
      AND alias.provenance ->> 'source' =
          'purina_pro_plan_exact_retailer_identity_reconciliation_20260804'
      AND (alias.provenance ->> 'retailer_identity_only')::BOOLEAN
      AND NOT (alias.provenance ->> 'retailer_ingredient_verification')::BOOLEAN
  ) <> 8 THEN
    RAISE EXCEPTION 'Purina Pro Plan search alias postcondition failed';
  END IF;

  IF (
    SELECT count(*)
    FROM purina_pro_plan_retailer_alias_resolved resolved
    JOIN public.catalog_field_evidence evidence
      ON evidence.formula_id = resolved.formula_id
     AND evidence.observation_id = resolved.observation_id
     AND evidence.field_name = 'retailer_exact_identity_alias'
     AND evidence.source_url = resolved.retailer_source_url
    WHERE evidence.accepted
      AND evidence.source_authority = 'retailer_identity'
      AND evidence.field_value ->> 'source' =
          'purina_pro_plan_exact_retailer_identity_reconciliation_20260804'
      AND (evidence.field_value ->> 'retailer_identity_only')::BOOLEAN
      AND NOT (
        evidence.field_value ->> 'retailer_ingredient_verification'
      )::BOOLEAN
  ) <> 8 THEN
    RAISE EXCEPTION 'Purina Pro Plan field-evidence postcondition failed';
  END IF;

  FOR v_resolved IN
    SELECT *
    FROM purina_pro_plan_retailer_alias_resolved
    ORDER BY alias_formula_key
  LOOP
    SELECT result.cache_key
    INTO v_top_cache_key
    FROM public.search_verified_products(v_resolved.retailer_title, 8) result
    ORDER BY result.rank DESC
    LIMIT 1;

    IF v_top_cache_key IS DISTINCT FROM v_resolved.target_cache_key THEN
      RAISE EXCEPTION
        'Purina Pro Plan exact-title search regression for %: expected %, got %',
        v_resolved.retailer_product_id,
        v_resolved.target_cache_key,
        v_top_cache_key;
    END IF;

    IF EXISTS (
      SELECT 1
      FROM public.search_verified_products(v_resolved.retailer_title, 8) result
      WHERE lower(btrim(result.brand)) <> 'purina pro plan'
         OR result.pet_type <> v_resolved.target_pet_type
         OR result.food_form <> v_resolved.target_food_form
    ) THEN
      RAISE EXCEPTION
        'Purina Pro Plan exact-title search crossed a hard boundary: %',
        v_resolved.retailer_product_id;
    END IF;
  END LOOP;

  SELECT resolved.alias_formula_key
  INTO v_key
  FROM purina_pro_plan_retailer_alias_resolved resolved
  WHERE NOT EXISTS (
    SELECT 1
    FROM public.product_data product
    WHERE product.cache_key = resolved.target_cache_key
      AND product.source_url = resolved.target_source_url
      AND product.image_url = resolved.target_database_image_url
      AND product.gtin = resolved.target_gtin
      AND product.package_size = resolved.target_package_size
      AND product.ingredient_count = resolved.target_ingredient_count
      AND coalesce(
            nullif(
              product.formula_version_provenance ->> 'ingredient_text_hash',
              ''
            ),
            encode(
              digest(
                public.catalog_normalize_ingredient_evidence(product.ingredient_text),
                'sha256'
              ),
              'hex'
            )
          ) = resolved.target_database_ingredient_hash
      AND encode(
            digest(
              btrim(regexp_replace(product.ingredient_text, '\s+', ' ', 'g')),
              'sha256'
            ),
            'hex'
          ) = resolved.target_raw_ingredient_hash
      AND product.formula_evidence_tier = 'manufacturer_current_exact'
      AND product.source_quality = 'manufacturer'
      AND product.ingredient_verification_status = 'manufacturer'
      AND product.image_verification_status = 'manufacturer'
  )
  LIMIT 1;

  IF FOUND THEN
    RAISE EXCEPTION 'Purina Pro Plan identity migration changed serving evidence: %', v_key;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM purina_pro_plan_retailer_alias_resolved resolved
    JOIN public.catalog_formulas formula
      ON formula.promoted_cache_key = resolved.target_cache_key
     AND formula.active
     AND formula.verification_status = 'verified'
    GROUP BY resolved.target_cache_key
    HAVING count(*) <> 1
  ) THEN
    RAISE EXCEPTION 'Purina Pro Plan cache has multiple active verified formulas';
  END IF;
END
$postconditions$;
