INSERT INTO public.catalog_coverage_snapshots (
  snapshot_key, census_started_at, census_completed_at, source_panel,
  required_source_panel, completed_source_panel, denominator_formula_count,
  verified_formula_count, verified_formula_percent, popular_brand_count,
  complete_popular_brand_count, popular_formula_gap_count,
  ingredient_verified_percent, image_verified_percent,
  independent_denominator, passes_source_panel, passes_total_coverage,
  passes_popular_brands, passes_release_gate, details
) VALUES (
  'public-reviewed-major95-visible-package-v175:20260727',
  '2026-07-27T17:00:00Z', '2026-07-27T17:02:33.383Z',
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap',
    'petco-retail-catalog','amazon-retail-catalog'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  9747, 6851, 70.29, 86, 38, 2896, 70.29, 70.29,
  true, false, false, false, false,
  jsonb_build_object(
    'searchable_web_evidenced_count', 6851,
    'manufacturer_current_exact_count', 4941,
    'retailer_web_version_count', 1772,
    'web_label_version_count', 138,
    'unresolved_formula_count', 2896,
    'reviewed_visible_package_alias_count_v173_v174_v175', 7,
    'closed_independent_gap_count_since_v174', 3,
    'canonical_duplicate_formula_collapse_since_v174', 3,
    'net_searchable_formula_gain_since_v174', 0,
    'target_formula_count', 509,
    'target_searchable_formula_count', 244,
    'target_formula_gap_count', 265,
    'chewy_formula_count', 3329,
    'chewy_searchable_formula_count', 1830,
    'chewy_formula_gap_count', 1499,
    'blue_buffalo_formula_count', 909,
    'blue_buffalo_searchable_formula_count', 530,
    'blue_buffalo_formula_gap_count', 379,
    'nutro_formula_count', 216,
    'nutro_searchable_formula_count', 121,
    'nutro_formula_gap_count', 95,
    'major95_formula_count', 9166,
    'major95_searchable_formula_count', 6270,
    'major95_formula_gap_count', 2896,
    'major95_inventory_continuity_failure_count', 0,
    'visible_package_alias_policy',
      'exact retailer title and captured package-front identity select one existing verified manufacturer formula without claiming retailer ingredient-version equivalence',
    'ingredient_version_policy',
      'prefer_canonical_verified_version_without_package_version_claim',
    'older_package_designs_are_versioned_identity_evidence_only', true,
    'verified_serving_gtin_version_conflict_count', 110,
    'verified_serving_gtin_version_conflicts_still_resolving', 0,
    'missing_source_panel',
      jsonb_build_array('petco-retail-catalog','amazon-retail-catalog'),
    'second_census_seven_days_apart', false,
    'eric_physical_device_validation', false
  )
)
ON CONFLICT (snapshot_key) DO UPDATE SET
  census_completed_at = excluded.census_completed_at,
  denominator_formula_count = excluded.denominator_formula_count,
  verified_formula_count = excluded.verified_formula_count,
  verified_formula_percent = excluded.verified_formula_percent,
  popular_formula_gap_count = excluded.popular_formula_gap_count,
  ingredient_verified_percent = excluded.ingredient_verified_percent,
  image_verified_percent = excluded.image_verified_percent,
  passes_release_gate = excluded.passes_release_gate,
  details = excluded.details;
