INSERT INTO public.catalog_coverage_snapshots (
  snapshot_key, census_started_at, census_completed_at, source_panel,
  required_source_panel, completed_source_panel, denominator_formula_count,
  verified_formula_count, verified_formula_percent, popular_brand_count,
  complete_popular_brand_count, popular_formula_gap_count,
  ingredient_verified_percent, image_verified_percent,
  independent_denominator, passes_source_panel, passes_total_coverage,
  passes_popular_brands, passes_release_gate, details
) VALUES (
  'public-reviewed-major95-visible-package-v174:20260727',
  '2026-07-27T16:47:00Z', '2026-07-27T16:50:12.675Z',
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap',
    'petco-retail-catalog','amazon-retail-catalog'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  9750, 6851, 70.27, 86, 38, 2899, 70.27, 70.27,
  true, false, false, false, false,
  jsonb_build_object(
    'searchable_web_evidenced_count', 6851,
    'manufacturer_current_exact_count', 4941,
    'retailer_web_version_count', 1772,
    'web_label_version_count', 138,
    'unresolved_formula_count', 2899,
    'reviewed_visible_package_alias_count_v173_v174', 4,
    'repaired_manufacturer_serving_identity_count_v174', 2,
    'closed_independent_gap_count_since_v173', 4,
    'canonical_duplicate_formula_collapse_since_v173', 4,
    'net_searchable_formula_gain_since_v173', 0,
    'chewy_formula_count', 3329,
    'chewy_searchable_formula_count', 1829,
    'chewy_formula_gap_count', 1500,
    'purina_pro_plan_formula_count', 476,
    'purina_pro_plan_searchable_formula_count', 271,
    'purina_pro_plan_formula_gap_count', 205,
    'major95_formula_count', 9169,
    'major95_searchable_formula_count', 6270,
    'major95_formula_gap_count', 2899,
    'major95_inventory_continuity_failure_count', 0,
    'conflicting_puppy_formula_left_unresolved', true,
    'conflicting_puppy_formula',
      'Purina Pro Plan Puppy Sensitive Skin & Stomach Salmon & Rice Dry Dog Food',
    'visible_package_alias_policy',
      'exact retailer title and package-front identity select one existing verified manufacturer formula without claiming retailer ingredient-version equivalence',
    'ingredient_version_policy',
      'prefer_canonical_verified_version_without_package_version_claim',
    'verified_serving_gtin_version_conflict_count', 110,
    'verified_serving_gtin_version_conflicts_still_resolving', 0,
    'missing_source_panel',
      jsonb_build_array('petco-retail-catalog','amazon-retail-catalog'),
    'second_census_seven_days_apart', false,
    'eric_physical_device_validation', false
  )
)
ON CONFLICT (snapshot_key) DO UPDATE SET
  census_completed_at = excluded.census_completed_at,
  denominator_formula_count = excluded.denominator_formula_count,
  verified_formula_count = excluded.verified_formula_count,
  verified_formula_percent = excluded.verified_formula_percent,
  popular_formula_gap_count = excluded.popular_formula_gap_count,
  ingredient_verified_percent = excluded.ingredient_verified_percent,
  image_verified_percent = excluded.image_verified_percent,
  passes_release_gate = excluded.passes_release_gate,
  details = excluded.details;
