INSERT INTO public.catalog_coverage_snapshots (
  snapshot_key, census_started_at, census_completed_at, source_panel,
  required_source_panel, completed_source_panel, denominator_formula_count,
  verified_formula_count, verified_formula_percent, popular_brand_count,
  complete_popular_brand_count, popular_formula_gap_count,
  ingredient_verified_percent, image_verified_percent,
  independent_denominator, passes_source_panel, passes_total_coverage,
  passes_popular_brands, passes_release_gate, details
) VALUES (
  'public-reviewed-major95-petsmart-equivalence-v177:20260727',
  '2026-07-27T17:42:00Z', '2026-07-27T17:45:20.606Z',
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap',
    'petco-retail-catalog','amazon-retail-catalog'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  9711, 6853, 70.57, 86, 40, 2858, 70.57, 70.57,
  true, false, false, false, false,
  jsonb_build_object(
    'searchable_web_evidenced_count', 6853,
    'manufacturer_current_exact_count', 4941,
    'retailer_web_version_count', 1774,
    'web_label_version_count', 138,
    'unresolved_formula_count', 2858,
    'reviewed_petsmart_package_equivalence_count_v177', 7,
    'closed_independent_gap_count_since_v176', 7,
    'canonical_duplicate_formula_collapse_since_v176', 7,
    'net_searchable_formula_gain_since_v176', 0,
    'petsmart_formula_count', 2233,
    'petsmart_searchable_formula_count', 2212,
    'petsmart_formula_gap_count', 21,
    'petsmart_searchable_percent', 99.06,
    'authority_formula_count', 82,
    'authority_searchable_formula_count', 82,
    'authority_formula_gap_count', 0,
    'simply_nourish_formula_count', 90,
    'simply_nourish_searchable_formula_count', 90,
    'simply_nourish_formula_gap_count', 0,
    'major95_formula_count', 9130,
    'major95_searchable_formula_count', 6272,
    'major95_formula_gap_count', 2858,
    'major95_inventory_continuity_failure_count', 0,
    'formula_version_policy',
      'same exact retailer_web_version only; different ingredient hashes remain separate and unresolved until package version is proven',
    'identity_gate',
      'same GTIN, normalized full ingredient hash, front image, source URL, brand, species, life stage, form, and recipe',
    'evidence_artifact',
      'outputs/catalog-source-imports/petsmart-package-equivalence-v177/source-evidence.json',
    'missing_source_panel',
      jsonb_build_array('petco-retail-catalog','amazon-retail-catalog'),
    'second_census_seven_days_apart', false,
    'eric_physical_device_validation', false
  )
)
ON CONFLICT (snapshot_key) DO UPDATE SET
  census_completed_at = excluded.census_completed_at,
  denominator_formula_count = excluded.denominator_formula_count,
  verified_formula_count = excluded.verified_formula_count,
  verified_formula_percent = excluded.verified_formula_percent,
  popular_formula_gap_count = excluded.popular_formula_gap_count,
  ingredient_verified_percent = excluded.ingredient_verified_percent,
  image_verified_percent = excluded.image_verified_percent,
  passes_release_gate = excluded.passes_release_gate,
  details = excluded.details;
