INSERT INTO public.catalog_coverage_snapshots (
  snapshot_key, census_started_at, census_completed_at, source_panel,
  required_source_panel, completed_source_panel, denominator_formula_count,
  verified_formula_count, verified_formula_percent, popular_brand_count,
  complete_popular_brand_count, popular_formula_gap_count,
  ingredient_verified_percent, image_verified_percent,
  independent_denominator, passes_source_panel, passes_total_coverage,
  passes_popular_brands, passes_release_gate, details
) VALUES (
  'public-reviewed-major95-target-blue-buffalo-v164:20260727',
  '2026-07-27T09:15:00Z', '2026-07-27T09:17:18.377Z',
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap',
    'petco-retail-catalog','amazon-retail-catalog'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  9750, 6846, 70.22, 86, 38, 2904, 70.22, 70.22,
  true, false, false, false, false,
  jsonb_build_object(
    'searchable_web_evidenced_count', 6846,
    'manufacturer_current_exact_count', 4941,
    'retailer_web_version_count', 1767,
    'web_label_version_count', 138,
    'unresolved_formula_count', 2904,
    'promoted_exact_source_version_formula_count', 9,
    'manufacturer_current_equivalent_package_count', 0,
    'reviewed_exact_package_sku_count', 9,
    'version_conflicting_gtin_abstention_count', 2,
    'runtime_exact_gtin_resolution_count', 7,
    'actionable_quarantine_count', 8,
    'net_searchable_formula_gain_since_v160', 6,
    'net_gap_reduction_since_v160', 2,
    'denominator_formula_growth_since_v160', 4,
    'target_formula_count', 510,
    'target_searchable_formula_count', 244,
    'target_formula_gap_count', 266,
    'blue_buffalo_formula_count', 898,
    'blue_buffalo_searchable_formula_count', 525,
    'blue_buffalo_formula_gap_count', 373,
    'major95_formula_count', 9169,
    'major95_searchable_formula_count', 6265,
    'major95_formula_gap_count', 2904,
    'major95_inventory_continuity_failure_count', 0,
    'missing_source_panel',
      jsonb_build_array('petco-retail-catalog','amazon-retail-catalog'),
    'second_census_seven_days_apart', false,
    'eric_physical_device_validation', false
  )
)
ON CONFLICT (snapshot_key) DO UPDATE SET
  census_completed_at=excluded.census_completed_at,
  denominator_formula_count=excluded.denominator_formula_count,
  verified_formula_count=excluded.verified_formula_count,
  verified_formula_percent=excluded.verified_formula_percent,
  popular_formula_gap_count=excluded.popular_formula_gap_count,
  details=excluded.details;
