INSERT INTO public.catalog_coverage_snapshots (
  snapshot_key, census_started_at, census_completed_at, source_panel,
  required_source_panel, completed_source_panel, denominator_formula_count,
  verified_formula_count, verified_formula_percent, popular_brand_count,
  complete_popular_brand_count, popular_formula_gap_count,
  ingredient_verified_percent, image_verified_percent,
  independent_denominator, passes_source_panel, passes_total_coverage,
  passes_popular_brands, passes_release_gate, details
) VALUES (
  'public-reviewed-major95-target-freshpet-v196:20260727',
  '2026-07-27T19:57:53.518Z', '2026-07-27T20:04:06.080Z',
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap',
    'petco-retail-catalog','amazon-retail-catalog'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  9682, 6911, 71.38, 86, 42, 2771, 71.38, 71.38,
  true, false, false, false, false,
  jsonb_build_object(
    'searchable_web_evidenced_count', 6911,
    'manufacturer_current_exact_count', 4938,
    'retailer_web_version_count', 1835,
    'web_label_version_count', 138,
    'unresolved_formula_count', 2771,
    'reviewed_target_freshpet_clean_package_count_v195', 17,
    'reviewed_target_freshpet_formula_version_count_v195', 17,
    'promoted_retailer_web_version_formula_count_v196', 17,
    'version_safe_gtin_count_v196', 7,
    'reused_or_incompatible_gtin_abstention_count_v196', 10,
    'malformed_or_incomplete_page_exclusion_count_v195', 7,
    'freshpet_formula_count', 113,
    'freshpet_searchable_formula_count', 76,
    'freshpet_formula_gap_count', 37,
    'target_formula_count', 508,
    'target_searchable_formula_count', 294,
    'target_formula_gap_count', 214,
    'major95_formula_count', 9101,
    'major95_searchable_formula_count', 6330,
    'major95_formula_gap_count', 2771,
    'major95_inventory_continuity_failure_count', 0,
    'major95_release_complete_brand_count', 18,
    'ingredient_completeness_policy',
      'A full exact retailer ingredient panel may be shorter than 500 characters when it has at least 8 parsed ingredients, complete delimiters, balanced parentheses, and no known OCR/transcription artifact',
    'formula_version_policy',
      'retailer_web_version remains source-versioned with URL, package identifier, capture date, image, and full ingredients; reused or incompatible GTINs abstain',
    'source_evidence_artifacts',
      jsonb_build_array(
        'outputs/catalog-source-imports/target-freshpet-gap-wave-v195-20260727/frozen/source-evidence-a6b9df022e91a1e531788615.json'
      ),
    'coverage_report',
      'outputs/catalog-market-leaders/brand-coverage-sprint-current-major95-target-freshpet-v196-20260727-sprint/WAVE_REPORT.md',
    'missing_source_panel',
      jsonb_build_array('petco-retail-catalog','amazon-retail-catalog'),
    'second_census_seven_days_apart', false,
    'eric_physical_device_validation', false
  )
)
ON CONFLICT (snapshot_key) DO UPDATE SET
  census_completed_at = excluded.census_completed_at,
  denominator_formula_count = excluded.denominator_formula_count,
  verified_formula_count = excluded.verified_formula_count,
  verified_formula_percent = excluded.verified_formula_percent,
  complete_popular_brand_count = excluded.complete_popular_brand_count,
  popular_formula_gap_count = excluded.popular_formula_gap_count,
  ingredient_verified_percent = excluded.ingredient_verified_percent,
  image_verified_percent = excluded.image_verified_percent,
  passes_source_panel = excluded.passes_source_panel,
  passes_total_coverage = excluded.passes_total_coverage,
  passes_popular_brands = excluded.passes_popular_brands,
  passes_release_gate = excluded.passes_release_gate,
  details = excluded.details;
