-- Preserve every exact retailer PDP URL independently from normalized search
-- title aliases. Package-size URLs are SKU evidence for one formula/version;
-- collapsing them by alias text caused already-promoted products to reappear
-- as false denominator gaps.

CREATE TABLE IF NOT EXISTS public.catalog_verified_product_source_aliases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_url TEXT NOT NULL UNIQUE,
  cache_key TEXT NOT NULL,
  alias_text TEXT NOT NULL,
  source_authority TEXT NOT NULL DEFAULT 'retailer_identity'
    CHECK (source_authority IN (
      'manufacturer', 'official', 'retailer_verified', 'retailer_identity',
      'label_ocr_verified', 'gdsn'
    )),
  evidence_observed_at TIMESTAMPTZ NOT NULL,
  provenance JSONB NOT NULL DEFAULT '{}'::JSONB,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.catalog_verified_product_source_aliases
  ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.catalog_verified_product_source_aliases
  FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON TABLE public.catalog_verified_product_source_aliases TO service_role;
REVOKE ALL ON SEQUENCE
  public.catalog_verified_product_source_aliases_id_seq
  FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE
  public.catalog_verified_product_source_aliases_id_seq TO service_role;

CREATE INDEX IF NOT EXISTS catalog_verified_product_source_aliases_cache_idx
  ON public.catalog_verified_product_source_aliases (cache_key)
  WHERE active;

CREATE OR REPLACE FUNCTION public.sync_retailer_verified_source_aliases(
  p_import_run_id UUID DEFAULT NULL
)
RETURNS TABLE(upserted_rows INTEGER)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $function$
DECLARE
  v_upserted INTEGER := 0;
BEGIN
  WITH safe_source_rows AS (
    SELECT
      evidence.source_url,
      evidence.promoted_cache_key AS cache_key,
      evidence.formula_title AS alias_text,
      GREATEST(
        COALESCE(evidence.fetched_at, '-infinity'::TIMESTAMPTZ),
        COALESCE(product.verified_at, '-infinity'::TIMESTAMPTZ),
        COALESCE(evidence.updated_at, '-infinity'::TIMESTAMPTZ)
      ) AS evidence_observed_at,
      jsonb_build_object(
        'source', 'exact_promoted_retailer_pdp_v1',
        'import_run_id', evidence.import_run_id,
        'evidence_id', evidence.id,
        'source_slug', evidence.source_slug,
        'formula_id', evidence.linked_formula_id,
        'ingredient_hash', evidence.ingredient_hash,
        'package_size_is_sku_only', true,
        'identity_gates', jsonb_build_array(
          'same_brand', 'same_species', 'compatible_food_form',
          'compatible_life_stage', 'same_normalized_full_ingredients'
        )
      ) AS provenance
    FROM public.catalog_retailer_ingredient_evidence evidence
    JOIN public.product_data product
      ON product.cache_key = evidence.promoted_cache_key
    WHERE (p_import_run_id IS NULL OR evidence.import_run_id = p_import_run_id)
      AND evidence.is_current
      AND evidence.evidence_status = 'promoted'
      AND NULLIF(btrim(evidence.source_url), '') IS NOT NULL
      AND evidence.source_url ~ '^https://'
      AND NULLIF(btrim(evidence.formula_title), '') IS NOT NULL
      AND NULLIF(btrim(evidence.retailer_brand), '') IS NOT NULL
      AND lower(regexp_replace(evidence.retailer_brand, '[^a-z0-9]+', '', 'g'))
        = lower(regexp_replace(product.brand, '[^a-z0-9]+', '', 'g'))
      AND evidence.pet_type = product.pet_type
      AND (
        evidence.food_form = 'unknown'
        OR product.food_form = 'unknown'
        OR evidence.food_form = product.food_form
      )
      AND (
        evidence.life_stage = 'unknown'
        OR product.life_stage = 'unknown'
        OR evidence.life_stage = product.life_stage
      )
      AND public.catalog_normalize_retailer_serving_ingredient_text(
        evidence.ingredient_text
      ) = product.ingredient_text
      AND product.pet_type IN ('dog', 'cat')
      AND product.is_complete_food
      AND product.catalog_exclusion_reason IS NULL
      AND product.ingredient_count >= 5
      AND NULLIF(btrim(product.ingredient_text), '') IS NOT NULL
      AND NULLIF(btrim(product.image_url), '') IS NOT NULL
      AND product.source_quality IN (
        'manufacturer', 'official', 'retailer_verified', 'gdsn'
      )
      AND product.ingredient_verification_status IN (
        'manufacturer', 'official', 'retailer_verified', 'gdsn',
        'label_ocr_verified'
      )
      AND product.image_verification_status IN (
        'manufacturer', 'official', 'retailer_verified'
      )
      AND (product.expires_at IS NULL OR product.expires_at > now())
  ), upserted AS (
    INSERT INTO public.catalog_verified_product_source_aliases (
      source_url,
      cache_key,
      alias_text,
      source_authority,
      evidence_observed_at,
      provenance,
      active,
      updated_at
    )
    SELECT
      source_url,
      cache_key,
      alias_text,
      'retailer_identity',
      evidence_observed_at,
      provenance,
      true,
      now()
    FROM safe_source_rows
    ON CONFLICT (source_url) DO UPDATE SET
      cache_key = EXCLUDED.cache_key,
      alias_text = EXCLUDED.alias_text,
      source_authority = EXCLUDED.source_authority,
      evidence_observed_at = EXCLUDED.evidence_observed_at,
      provenance = EXCLUDED.provenance,
      active = true,
      updated_at = now()
    RETURNING id
  )
  SELECT count(*)::INTEGER INTO v_upserted FROM upserted;

  RETURN QUERY SELECT v_upserted;
END;
$function$;

REVOKE ALL ON FUNCTION public.sync_retailer_verified_source_aliases(UUID)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sync_retailer_verified_source_aliases(UUID)
  TO service_role;

-- Seed every safe current promoted package. No generated ID is referenced;
-- the evidence relationship and exact ingredient equality are revalidated.
SELECT public.sync_retailer_verified_source_aliases(NULL);

-- Preserve older reviewed aliases only when no exact promoted-package row owns
-- that URL. This keeps manufacturer/manual evidence available without
-- overriding the current retailer package version.
INSERT INTO public.catalog_verified_product_source_aliases (
  source_url,
  cache_key,
  alias_text,
  source_authority,
  evidence_observed_at,
  provenance,
  active
)
SELECT DISTINCT ON (alias.source_url)
  alias.source_url,
  alias.cache_key,
  alias.alias_text,
  alias.source_authority,
  alias.evidence_observed_at,
  jsonb_build_object(
    'source', 'legacy_reviewed_search_alias_backfill_v1',
    'search_alias_id', alias.id
  ),
  true
FROM public.catalog_verified_product_search_aliases alias
JOIN public.product_data product ON product.cache_key = alias.cache_key
WHERE alias.active
  AND NULLIF(btrim(alias.source_url), '') IS NOT NULL
  AND alias.source_url ~ '^https://'
  AND product.pet_type IN ('dog', 'cat')
  AND product.is_complete_food IS NOT FALSE
  AND product.catalog_exclusion_reason IS NULL
  AND product.ingredient_count >= 5
  AND NULLIF(btrim(product.ingredient_text), '') IS NOT NULL
  AND NULLIF(btrim(product.image_url), '') IS NOT NULL
  AND product.source_quality IN (
    'manufacturer', 'official', 'retailer_verified', 'gdsn'
  )
  AND product.ingredient_verification_status IN (
    'manufacturer', 'official', 'retailer_verified', 'gdsn',
    'label_ocr_verified'
  )
  AND product.image_verification_status IN (
    'manufacturer', 'official', 'retailer_verified'
  )
  AND (product.expires_at IS NULL OR product.expires_at > now())
ORDER BY alias.source_url, alias.evidence_observed_at DESC, alias.id DESC
ON CONFLICT (source_url) DO NOTHING;

CREATE OR REPLACE FUNCTION public.get_verified_retailer_source_aliases_keyset(
  p_after_id BIGINT DEFAULT 0,
  p_limit INTEGER DEFAULT 1000
)
RETURNS TABLE(
  alias_id BIGINT,
  source_url TEXT,
  cache_key TEXT,
  alias_text TEXT,
  source_authority TEXT,
  evidence_observed_at TIMESTAMPTZ
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
  SELECT
    alias.id,
    alias.source_url,
    alias.cache_key,
    alias.alias_text,
    alias.source_authority,
    alias.evidence_observed_at
  FROM public.catalog_verified_product_source_aliases alias
  JOIN public.product_data product ON product.cache_key = alias.cache_key
  WHERE alias.id > GREATEST(COALESCE(p_after_id, 0), 0)
    AND alias.active
    AND product.pet_type IN ('dog', 'cat')
    AND product.is_complete_food IS NOT FALSE
    AND product.catalog_exclusion_reason IS NULL
    AND product.ingredient_count >= 5
    AND NULLIF(btrim(product.ingredient_text), '') IS NOT NULL
    AND NULLIF(btrim(product.image_url), '') IS NOT NULL
    AND product.source_quality IN (
      'manufacturer', 'official', 'retailer_verified', 'gdsn'
    )
    AND product.ingredient_verification_status IN (
      'manufacturer', 'official', 'retailer_verified', 'gdsn',
      'label_ocr_verified'
    )
    AND product.image_verification_status IN (
      'manufacturer', 'official', 'retailer_verified'
    )
    AND (product.expires_at IS NULL OR product.expires_at > now())
  ORDER BY alias.id
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 1000), 1), 1000);
$function$;

REVOKE ALL ON FUNCTION
  public.get_verified_retailer_source_aliases_keyset(BIGINT, INTEGER)
  FROM PUBLIC;
-- CREATE OR REPLACE preserves the RPC's already-reviewed execution grants;
-- do not broaden them in this migration.

COMMENT ON TABLE public.catalog_verified_product_source_aliases IS
  'Exact evidence-backed source URL to verified serving-version aliases; package sizes remain SKU evidence.';
COMMENT ON FUNCTION public.sync_retailer_verified_source_aliases(UUID) IS
  'Upserts exact promoted retailer PDP aliases after brand/species/form/stage and full-ingredient equality gates.';
