INSERT INTO public.catalog_coverage_snapshots (
  snapshot_key, census_started_at, census_completed_at, source_panel,
  required_source_panel, completed_source_panel, denominator_formula_count,
  verified_formula_count, verified_formula_percent, popular_brand_count,
  complete_popular_brand_count, popular_formula_gap_count,
  ingredient_verified_percent, image_verified_percent,
  independent_denominator, passes_source_panel, passes_total_coverage,
  passes_popular_brands, passes_release_gate, details
) VALUES (
  'public-reviewed-major95-petsmart-source-versions-v180:20260727',
  '2026-07-27T18:18:00Z', '2026-07-27T18:27:22.781Z',
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap',
    'petco-retail-catalog','amazon-retail-catalog'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  9698, 6868, 70.82, 86, 42, 2830, 70.82, 70.82,
  true, false, false, false, false,
  jsonb_build_object(
    'searchable_web_evidenced_count', 6868,
    'manufacturer_current_exact_count', 4938,
    'retailer_web_version_count', 1792,
    'web_label_version_count', 138,
    'unresolved_formula_count', 2830,
    'reviewed_petsmart_source_version_count_v180', 12,
    'petsmart_formula_count', 2233,
    'petsmart_searchable_formula_count', 2233,
    'petsmart_formula_gap_count', 0,
    'petsmart_searchable_percent', 100.00,
    'major95_formula_count', 9117,
    'major95_searchable_formula_count', 6287,
    'major95_formula_gap_count', 2830,
    'major95_inventory_continuity_failure_count', 0,
    'major95_release_complete_brand_count', 18,
    'gtin_resolution_policy',
      'select exact package version when identified; barcode-only lookup abstains on incompatible ingredient versions and deduplicates identical versions in favor of manufacturer-current evidence',
    'formula_version_policy',
      'retailer_web_version and web_label_version remain source-versioned records with URL, package identifier, capture date, image, and full ingredients; never overwrite a different manufacturer-current ingredient version',
    'evidence_gate',
      'exact GTIN or unambiguous package identity, full readable ingredients, matching front image, source URL, capture date, and compatible brand/species/line/form/recipe identity',
    'source_evidence_artifact',
      'outputs/catalog-source-imports/petsmart-source-versions-v180/source-evidence.json',
    'coverage_report',
      'outputs/catalog-market-leaders/brand-coverage-sprint-current-major95-petsmart-source-versions-v180-20260727-sprint/WAVE_REPORT.md',
    'missing_source_panel',
      jsonb_build_array('petco-retail-catalog','amazon-retail-catalog'),
    'second_census_seven_days_apart', false,
    'eric_physical_device_validation', false
  )
)
ON CONFLICT (snapshot_key) DO UPDATE SET
  census_completed_at = excluded.census_completed_at,
  denominator_formula_count = excluded.denominator_formula_count,
  verified_formula_count = excluded.verified_formula_count,
  verified_formula_percent = excluded.verified_formula_percent,
  complete_popular_brand_count = excluded.complete_popular_brand_count,
  popular_formula_gap_count = excluded.popular_formula_gap_count,
  ingredient_verified_percent = excluded.ingredient_verified_percent,
  image_verified_percent = excluded.image_verified_percent,
  passes_source_panel = excluded.passes_source_panel,
  passes_total_coverage = excluded.passes_total_coverage,
  passes_popular_brands = excluded.passes_popular_brands,
  passes_release_gate = excluded.passes_release_gate,
  details = excluded.details;
