INSERT INTO public.catalog_coverage_snapshots (
  snapshot_key, census_started_at, census_completed_at, source_panel,
  required_source_panel, completed_source_panel, denominator_formula_count,
  verified_formula_count, verified_formula_percent, popular_brand_count,
  complete_popular_brand_count, popular_formula_gap_count,
  ingredient_verified_percent, image_verified_percent,
  independent_denominator, passes_source_panel, passes_total_coverage,
  passes_popular_brands, passes_release_gate, details
) VALUES (
  'public-reviewed-major95-target-blue-buffalo-v160:20260727',
  '2026-07-27T08:59:00Z', '2026-07-27T09:01:32.763Z',
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap',
    'petco-retail-catalog','amazon-retail-catalog'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  9746, 6840, 70.18, 86, 38, 2906, 70.18, 70.18,
  true, false, false, false, false,
  jsonb_build_object(
    'searchable_web_evidenced_count', 6840,
    'manufacturer_current_exact_count', 4941,
    'retailer_web_version_count', 1761,
    'web_label_version_count', 138,
    'unresolved_formula_count', 2906,
    'promoted_exact_source_version_formula_count', 8,
    'exact_equivalent_existing_package_count', 1,
    'reviewed_exact_package_sku_count', 10,
    'version_conflicting_gtin_abstention_count', 1,
    'runtime_exact_gtin_resolution_count', 9,
    'actionable_quarantine_count', 2,
    'net_searchable_formula_gain_since_v156', 3,
    'net_gap_reduction_since_v156', 4,
    'denominator_deduplication_since_v156', 1,
    'target_formula_count', 510,
    'target_searchable_formula_count', 238,
    'target_formula_gap_count', 272,
    'blue_buffalo_formula_count', 894,
    'blue_buffalo_searchable_formula_count', 519,
    'blue_buffalo_formula_gap_count', 375,
    'major95_formula_count', 9165,
    'major95_searchable_formula_count', 6259,
    'major95_formula_gap_count', 2906,
    'major95_inventory_continuity_failure_count', 0,
    'missing_source_panel',
      jsonb_build_array('petco-retail-catalog','amazon-retail-catalog'),
    'second_census_seven_days_apart', false,
    'eric_physical_device_validation', false
  )
)
ON CONFLICT (snapshot_key) DO UPDATE SET
  census_completed_at=excluded.census_completed_at,
  denominator_formula_count=excluded.denominator_formula_count,
  verified_formula_count=excluded.verified_formula_count,
  verified_formula_percent=excluded.verified_formula_percent,
  popular_formula_gap_count=excluded.popular_formula_gap_count,
  details=excluded.details;
