INSERT INTO public.catalog_coverage_snapshots (
  snapshot_key, census_started_at, census_completed_at, source_panel,
  required_source_panel, completed_source_panel, denominator_formula_count,
  verified_formula_count, verified_formula_percent, popular_brand_count,
  complete_popular_brand_count, popular_formula_gap_count,
  ingredient_verified_percent, image_verified_percent,
  independent_denominator, passes_source_panel, passes_total_coverage,
  passes_popular_brands, passes_release_gate, details
) VALUES (
  'public-reviewed-major95-visible-package-v176:20260727',
  '2026-07-27T17:25:00Z', '2026-07-27T17:28:52.406Z',
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap',
    'petco-retail-catalog','amazon-retail-catalog'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  9718, 6853, 70.52, 86, 38, 2865, 70.52, 70.52,
  true, false, false, false, false,
  jsonb_build_object(
    'searchable_web_evidenced_count', 6853,
    'manufacturer_current_exact_count', 4941,
    'retailer_web_version_count', 1774,
    'web_label_version_count', 138,
    'unresolved_formula_count', 2865,
    'reviewed_exact_gtin_alias_count_v171', 43,
    'reviewed_visible_package_alias_count_v176', 7,
    'reviewed_visible_package_formula_count_v176', 5,
    'closed_independent_gap_count_since_v175', 31,
    'canonical_duplicate_formula_collapse_since_v175', 29,
    'net_searchable_formula_gain_since_v175', 2,
    'target_formula_count', 509,
    'target_searchable_formula_count', 245,
    'target_formula_gap_count', 264,
    'chewy_formula_count', 3328,
    'chewy_searchable_formula_count', 1832,
    'chewy_formula_gap_count', 1496,
    'petsmart_formula_count', 2240,
    'petsmart_searchable_formula_count', 2212,
    'petsmart_formula_gap_count', 28,
    'blue_buffalo_formula_count', 905,
    'blue_buffalo_searchable_formula_count', 530,
    'blue_buffalo_formula_gap_count', 375,
    'purina_pro_plan_formula_count', 470,
    'purina_pro_plan_searchable_formula_count', 272,
    'purina_pro_plan_formula_gap_count', 198,
    'royal_canin_formula_count', 457,
    'royal_canin_searchable_formula_count', 403,
    'royal_canin_formula_gap_count', 54,
    'authority_formula_count', 84,
    'authority_searchable_formula_count', 82,
    'authority_formula_gap_count', 2,
    'major95_formula_count', 9137,
    'major95_searchable_formula_count', 6272,
    'major95_formula_gap_count', 2865,
    'major95_inventory_continuity_failure_count', 0,
    'formula_version_policy',
      'exact readable current package evidence is retained as retailer_web_version or web_label_version and never overwrites a different ingredient version',
    'reviewed_alias_reconciliation_policy',
      'generic GTIN reconciliation preserves only exact reviewed_official_formula_alias mappings',
    'authority_reviewed_duplicate_collapse_count', 15,
    'authority_continuity_review_file',
      'outputs/catalog-official-duplicate-canonical-stage/authority-v176-reviewed-alias-continuity-adjustment-20260727.json',
    'rejected_non_complete_blue_tastefuls_salmon_puree', true,
    'verified_serving_gtin_version_conflict_count', 110,
    'verified_serving_gtin_version_conflicts_still_resolving', 0,
    'missing_source_panel',
      jsonb_build_array('petco-retail-catalog','amazon-retail-catalog'),
    'second_census_seven_days_apart', false,
    'eric_physical_device_validation', false
  )
)
ON CONFLICT (snapshot_key) DO UPDATE SET
  census_completed_at = excluded.census_completed_at,
  denominator_formula_count = excluded.denominator_formula_count,
  verified_formula_count = excluded.verified_formula_count,
  verified_formula_percent = excluded.verified_formula_percent,
  popular_formula_gap_count = excluded.popular_formula_gap_count,
  ingredient_verified_percent = excluded.ingredient_verified_percent,
  image_verified_percent = excluded.image_verified_percent,
  passes_release_gate = excluded.passes_release_gate,
  details = excluded.details;
