-- Deterministic retailer identity aliases, wave nutrish_public_front_ocr_a.
-- Generated from inputs/catalog-reviewed-nutrish-public-front-ocr-aliases-20260809.json after exact official/live evidence validation.
-- Retailer rows remain identity-only; this migration never copies retailer
-- ingredients or images into product_data and never changes scoring.

DO $migration$
DECLARE
  v_payload JSONB := convert_from(
    decode('W3siYWxpYXNfZm9ybXVsYV9rZXkiOiJyYWNoYWVsIHJheSBudXRyaXNofHJhY2hhZWwgcmF5IG51dHJpc2h8cmFjaGFlbCByYXkgbnV0cmlzaCBncmFpbiBmcmVlIHNhbG1vbiBhbmQgc3dlZXQgcG90YXRvIHJlY2lwZSBkcnkgZG9nIGZvb2R8ZG9nfHVua25vd258ZHJ5fHwiLCJzb3VyY2VfdXJsIjoiaHR0cHM6Ly93d3cuY2hld3kuY29tL3JhY2hhZWwtcmF5LW51dHJpc2gtemVyby1ncmFpbi9kcC8xMTc2NjMiLCJvZmZpY2lhbF9zb3VyY2VfdXJsIjoiaHR0cHM6Ly93d3cubnV0cmlzaC5jb20vcHJvZHVjdC9udXRyaXNoLWdyYWluLWZyZWUtc2FsbW9uLXN3ZWV0LXBvdGF0by1yZWNpcGUtZHJ5LWRvZy1mb29kLyIsImNhY2hlX2tleSI6Im51dHJpc2g6bnV0cmlzaCByYWNoYWVsIHJheSBudXRyaXNoIGdyYWluIGZyZWUgc2FsbW9uIHN3ZWV0IHBvdGF0byByZWNpcGUgZHJ5IGRvZyBmb29kIiwidGFyZ2V0X2Zvcm11bGFfa2V5IjoibnV0cmlzaHxudXRyaXNofHJhY2hhZWwgcmF5IG51dHJpc2ggZ3JhaW4gZnJlZSBzYWxtb24gYW5kIHN3ZWV0IHBvdGF0byByZWNpcGUgZHJ5IGRvZyBmb29kfGRvZ3x1bmtub3dufGRyeXxyYWNoYWVsIHJheSBncmFpbiBmcmVlIHNhbG1vbiBhbmQgc3dlZXQgcG90YXRvIHJlY2lwZXwiLCJyZXZpZXdlZF9hdCI6IjIwMjYtMDgtMTBUMDQ6Mjk6MDAuMDAwWiIsInJldmlld19tZXRob2QiOiJwdWJsaWNfcmV0YWlsZXJfZnJvbnRfb2NyX3RvX29mZmljaWFsX3N0cnVjdHVyZWRfaWRlbnRpdHlfbWFudWFsX3JldmlldyIsInJldmlld19yZWFzb24iOiJNYW51YWwgcmV2aWV3IG9mIHRoZSBwdWJsaWMgcmV0YWlsZXIgcGFja2FnZSBmcm9udCBjb25maXJtcyB0aGF0IHRoZSBSYWNoYWVsIFJheSBOdXRyaXNoIGRlbWFuZCBsYWJlbCBhbmQgdGhlIE51dHJpc2ggbWFudWZhY3R1cmVyIGxhYmVsIHJlZmVyIHRvIHRoZSBzYW1lIHNwZWNpZXMsIGZvb2QgZm9ybSwgcmVjaXBlLCBwcmVzZW50YXRpb24sIGFuZCBjb25kaXRpb24gZm9yIG9uZSBtYW51ZmFjdHVyZXItY3VycmVudCBmb3JtdWxhLiBGcm9udC1sYWJlbCBPQ1IgaXMgaWRlbnRpdHkgZXZpZGVuY2Ugb25seTsgaW5ncmVkaWVudHMgYW5kIHRoZSBzZXJ2aW5nIGltYWdlIHJlbWFpbiBib3VuZCB0byB0aGUgbWFudWZhY3R1cmVyIHJvdy4iLCJyZXRhaWxlcl9pZGVudGl0eV9vbmx5Ijp0cnVlLCJyZXRhaWxlcl9pbmdyZWRpZW50X3ZlcmlmaWNhdGlvbiI6ZmFsc2UsInJldGFpbGVyX3NvdXJjZV9zbHVnIjoiY2hld3ktcHVibGljLXNpdGVtYXAiLCJyZXRhaWxlcl9wcm9kdWN0X2lkIjoiMTE3NjYzIiwicmV0YWlsZXJfdGl0bGUiOiJSYWNoYWVsIFJheSBOdXRyaXNoIEdyYWluLUZyZWUgU2FsbW9uICYgU3dlZXQgUG90YXRvIFJlY2lwZSBEcnkgRG9nIEZvb2QiLCJyZXRhaWxlcl9vYnNlcnZlZF9hdCI6IjIwMjYtMDgtMDVUMjA6NTU6MjkuOTkyWiIsInJldGFpbGVyX2NvbnRlbnRfaGFzaCI6ImY0YTUzZjBjNTQyZDljOWJlZWE2NmE1MGNjYzY1MTdlYzU2ZjEzYWNiNGRlOTNiYTY2YzE3OTI0NzI5N2FmYjQiLCJyZXRhaWxlcl9mcm9udF9pbWFnZV91cmwiOiJodHRwczovL2ltYWdlLmNoZXd5LmNvbS9jYXRhbG9nL2dlbmVyYWwvaW1hZ2VzL21vZS8wNmEwZTEwNi1kODAxLTdjY2QtODAwMC1iYzJjMjQ1ZGMwOTcuX1YxXy5qcGciLCJyZXRhaWxlcl9mcm9udF9pbWFnZV9zaGEyNTYiOiI5ZGNkZWQwZjEzNmEwNDlhYjU5OGI1OGQ0OWZlZjk1ODJhN2U4MTk0NTM2NjdmNDZhNmIzZmU2YzMwOTYzZjY1IiwicmV0YWlsZXJfZnJvbnRfbGFiZWxfb2NyIjoiRXZlcnkgQmFnIEhlbHBzIEFuaW1hbHMgaW4gTmVlZC4gTnV0cmlzaCBJTkdSRURJRU5UIFJFQUwgU0FMTU9OIEdSQUlOIC1GUkVFLS5XNFwiIFNBTE1PTiAmIFNXRUVUIFBPVEFUTyBSRUNJUEUgTk8gQURERUQgU1dFRVQgUE9UQVRPRVMgUkVBTCBTQUxNT04gTkVUV1QgMjMgSUIxMTAuNCBrZykgVkVURVJJTkFSSUFOIFJFVklFV0VEIEZPUk1VTEEgQ09NUExFVEUgQU5EQkFMQU5DwqNEIE5BVFVSQUxGT09EIEZPUiBET0dTIiwibWFudWFsX3BhY2thZ2VfaW1hZ2VfbWF0Y2giOnRydWUsIm1hbnVhbF9mcm9udF9sYWJlbF9vY3JfbWF0Y2giOnRydWUsIm1hbnVhbF9mcm9udF9sYWJlbF92aXN1YWxfbWF0Y2giOnRydWUsInJlcXVpcmVkX29jcl90ZXJtcyI6WyJudXRyaXNoIiwiZ3JhaW4gZnJlZSIsInNhbG1vbiIsInN3ZWV0IHBvdGF0byIsIjIzIGliIiwiZG9ncyJdLCJwcm90ZWN0ZWRfaWRlbnRpdHlfdGVybXMiOlsibnV0cmlzaCIsImdyYWluIGZyZWUiLCJzYWxtb24gYW5kIHN3ZWV0IHBvdGF0byByZWNpcGUiLCJyZWFsIHNhbG1vbiIsIjIzIGxiIiwibmF0dXJhbCBmb29kIGZvciBkb2dzIl0sIm9ic2VydmVkX2lkZW50aXR5Ijp7ImJyYW5kIjoicmFjaGFlbCByYXkgbnV0cmlzaCIsInBldF90eXBlIjoiZG9nIiwibGlmZV9zdGFnZSI6InVua25vd24iLCJmb29kX2Zvcm0iOiJkcnkifSwidGFyZ2V0X2lkZW50aXR5Ijp7ImJyYW5kIjoiTnV0cmlzaCIsInByb2R1Y3RfbmFtZSI6IlJhY2hhZWwgUmF5IE51dHJpc2ggR3JhaW4gRnJlZSBTYWxtb24gJiBTd2VldCBQb3RhdG8gUmVjaXBlIERyeSBEb2cgRm9vZCIsInByb2R1Y3RfbGluZSI6IlJhY2hhZWwgUmF5IE51dHJpc2ggR3JhaW4gRnJlZSIsImZsYXZvciI6IlJhY2hhZWwgUmF5IEdyYWluIEZyZWUgU2FsbW9uICYgU3dlZXQgUG90YXRvIFJlY2lwZSIsInBldF90eXBlIjoiZG9nIiwibGlmZV9zdGFnZSI6bnVsbCwiZm9vZF9mb3JtIjoiZHJ5IiwicGFja2FnZV9zaXplIjpudWxsfSwib2ZmaWNpYWxfZGF0YWJhc2VfaW1hZ2VfdXJsIjoiaHR0cHM6Ly93d3cubnV0cmlzaC5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMjQvMDMvMS4wLURyeS1Eb2ctR3JhaW4tRnJlZS1TYWxtb24tU3dlZXQtUG90YXRvLTIzLWxiLmF2aWYiLCJvZmZpY2lhbF9pbWFnZV91cmwiOiJodHRwczovL3d3dy5udXRyaXNoLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAyNC8wMy8xLjAtRHJ5LURvZy1HcmFpbi1GcmVlLVNhbG1vbi1Td2VldC1Qb3RhdG8tMjMtbGIuYXZpZiIsIm9mZmljaWFsX2luZ3JlZGllbnRfY291bnQiOjM4LCJvZmZpY2lhbF9kYXRhYmFzZV9pbmdyZWRpZW50X2hhc2giOiJlNDU2NzdmZTI1MjU0Y2I0NWM1NDA5MmY3ZjQzYjBjZWRhMzU1ODUzNGQ0ZGUyNWRlY2IyMjNlOTExYjJhYTNlIiwib2ZmaWNpYWxfY2Fub25pY2FsX2luZ3JlZGllbnRfaGFzaCI6ImMyMGJkZTJiZmNhNjY5N2E5ZGM0YWE1MWE2ZGY3ZDg3ZjJkZGFlYTBkNjg3MzVlNTEyYzVkZjI5ZWVmZWNjNDEiLCJvZmZpY2lhbF9yYXdfaW5ncmVkaWVudF9oYXNoIjoiZjUyZWU1NWU0ZjM1ZjliNjE2ZTY4YTZiMzAzZjE5MGFmODFmZmYwYjNjNWJlZjk3MDY2ZjkzMmZjMTViYTc4ZCIsIm9mZmljaWFsX29ic2VydmVkX2F0IjoiMjAyNi0wNy0yNlQxMjozNzozMi4xMzYrMDA6MDAiLCJmb3JtdWxhX2lkX2hpbnQiOiIwNTc5NzQ2NS00YzQ0LTQ4ZjEtYjA5ZC1mZWY4NTlhM2VlZDYiLCJhdWRpdF9zY29yZSI6MSwiYXVkaXRfbWFyZ2luIjowLjMzMzMsImF1ZGl0X3NoYXJlZF90ZXJtcyI6WyJzYWxtb24iLCJzd2VldCIsInBvdGF0byJdfSx7ImFsaWFzX2Zvcm11bGFfa2V5IjoicmFjaGFlbCByYXkgbnV0cmlzaHxyYWNoYWVsIHJheSBudXRyaXNofHJhY2hhZWwgcmF5IG51dHJpc2ggaGlnaCBwcm90ZWluIGJlZWYgcG90YXRvIGFuZCBwZWFzIHJlY2lwZSB3aXRoIHZlbmlzb24gYW5kIGxhbWIgZHJ5IGRvZyBmb29kfGRvZ3x1bmtub3dufGRyeXx8Iiwic291cmNlX3VybCI6Imh0dHBzOi8vd3d3LmNoZXd5LmNvbS9yYWNoYWVsLXJheS1udXRyaXNoLXBlYWstb3Blbi1wcmFpcmllL2RwLzEzNTg5OSIsIm9mZmljaWFsX3NvdXJjZV91cmwiOiJodHRwczovL3d3dy5udXRyaXNoLmNvbS9wcm9kdWN0L2hpZ2gtcHJvdGVpbi1iZWVmLWRyeS1kb2ctZm9vZC8iLCJjYWNoZV9rZXkiOiJudXRyaXNoOm51dHJpc2ggcmFjaGFlbCByYXkgbnV0cmlzaCBoaWdoIHByb3RlaW4gYmVlZiBwb3RhdG8gcGVhcyByZWNpcGUgZHJ5IGRvZyBmb29kIiwidGFyZ2V0X2Zvcm11bGFfa2V5IjoibnV0cmlzaHxudXRyaXNofHJhY2hhZWwgcmF5IG51dHJpc2ggaGlnaCBwcm90ZWluIGJlZWYgcG90YXRvIGFuZCBwZWFzIHJlY2lwZSBkcnkgZG9nIGZvb2R8ZG9nfHVua25vd258ZHJ5fHBvdGF0byBhbmQgcGVhcyByZWNpcGV8IiwicmV2aWV3ZWRfYXQiOiIyMDI2LTA4LTEwVDA0OjI5OjAwLjAwMFoiLCJyZXZpZXdfbWV0aG9kIjoicHVibGljX3JldGFpbGVyX2Zyb250X29jcl90b19vZmZpY2lhbF9zdHJ1Y3R1cmVkX2lkZW50aXR5X21hbnVhbF9yZXZpZXciLCJyZXZpZXdfcmVhc29uIjoiTWFudWFsIHJldmlldyBvZiB0aGUgcHVibGljIHJldGFpbGVyIHBhY2thZ2UgZnJvbnQgY29uZmlybXMgdGhhdCB0aGUgUmFjaGFlbCBSYXkgTnV0cmlzaCBkZW1hbmQgbGFiZWwgYW5kIHRoZSBOdXRyaXNoIG1hbnVmYWN0dXJlciBsYWJlbCByZWZlciB0byB0aGUgc2FtZSBzcGVjaWVzLCBmb29kIGZvcm0sIHJlY2lwZSwgcHJlc2VudGF0aW9uLCBhbmQgY29uZGl0aW9uIGZvciBvbmUgbWFudWZhY3R1cmVyLWN1cnJlbnQgZm9ybXVsYS4gRnJvbnQtbGFiZWwgT0NSIGlzIGlkZW50aXR5IGV2aWRlbmNlIG9ubHk7IGluZ3JlZGllbnRzIGFuZCB0aGUgc2VydmluZyBpbWFnZSByZW1haW4gYm91bmQgdG8gdGhlIG1hbnVmYWN0dXJlciByb3cuIiwicmV0YWlsZXJfaWRlbnRpdHlfb25seSI6dHJ1ZSwicmV0YWlsZXJfaW5ncmVkaWVudF92ZXJpZmljYXRpb24iOmZhbHNlLCJyZXRhaWxlcl9zb3VyY2Vfc2x1ZyI6ImNoZXd5LXB1YmxpYy1zaXRlbWFwIiwicmV0YWlsZXJfcHJvZHVjdF9pZCI6IjEzNTg5OSIsInJldGFpbGVyX3RpdGxlIjoiUmFjaGFlbCBSYXkgTnV0cmlzaCBIaWdoIFByb3RlaW4gQmVlZiwgUG90YXRvICYgUGVhcyBSZWNpcGUgd2l0aCBWZW5pc29uICYgTGFtYiBEcnkgRG9nIEZvb2QiLCJyZXRhaWxlcl9vYnNlcnZlZF9hdCI6IjIwMjYtMDgtMDVUMjA6NTU6MjcuMjg0WiIsInJldGFpbGVyX2NvbnRlbnRfaGFzaCI6IjNjM2E5NjAwMDIzY2ExZGMyNTllZmU1NTQ0MzJiMWNkMDgxYTIwMjNkZTU2Y2MzYzM1NDQxZTViMjQyY2IxMGMiLCJyZXRhaWxlcl9mcm9udF9pbWFnZV91cmwiOiJodHRwczovL2ltYWdlLmNoZXd5LmNvbS9jYXRhbG9nL2dlbmVyYWwvaW1hZ2VzL21vZS8wNmEwZTEwNi1jZGY3LTdhZTAtODAwMC01ZGU3YWZiMjE5Y2YuX1YxXy5qcGciLCJyZXRhaWxlcl9mcm9udF9pbWFnZV9zaGEyNTYiOiI0ZTJjNWY0OWZlMTBhNjdiN2E1MWNiMGE5YTQzZjBlMmE5NDMxMTM3NzcwZDI4MDAwZGUzZDg4OTUzYzdjOWU1IiwicmV0YWlsZXJfZnJvbnRfbGFiZWxfb2NyIjoiRXZlcnkgQmFnIEhlbHBzIEFuaW1hbHMgaW4gTmVlZC4gTnV0cmlzaC4gSU5HUkVESUVNVCBSRUFJIEJFRUYgLUhJR0gtIFBST1RFSU4gQkVFRiwgUE9UQVRPICYgUEVBUyBSRUNJUEUgV0lUSCBWRU5JU09OICYgTEFNQiAzMCwgU1VTVEFJTkVEIEVORVJHWSBISUdILlFVQUxJVFkgUFJPVEVJTiBMRUFOIFBST1RFSU4gJiBBRERFRCBUQVVSSU5FIE5FVCBXVCAyMyBMQjExMC40IGtnfSBWRVRFUklOQVJJQU4gUkVWSUVXRUQgRk9STVVMQSBDT01QTEVURUFOREJBTEFOQ0VEIE5BVFVSQUxGT09EIEZPUiBET0dTIiwibWFudWFsX3BhY2thZ2VfaW1hZ2VfbWF0Y2giOnRydWUsIm1hbnVhbF9mcm9udF9sYWJlbF9vY3JfbWF0Y2giOnRydWUsIm1hbnVhbF9mcm9udF9sYWJlbF92aXN1YWxfbWF0Y2giOnRydWUsInJlcXVpcmVkX29jcl90ZXJtcyI6WyJudXRyaXNoIiwiaGlnaCBwcm90ZWluIiwiYmVlZiIsInBvdGF0byIsInBlYXMiLCJ2ZW5pc29uIiwibGFtYiIsIjIzbGIiXSwicHJvdGVjdGVkX2lkZW50aXR5X3Rlcm1zIjpbIm51dHJpc2giLCJoaWdoIHByb3RlaW4iLCJiZWVmIHBvdGF0byBhbmQgcGVhcyByZWNpcGUiLCJ3aXRoIHZlbmlzb24gYW5kIGxhbWIiLCIyMyBsYiIsIm5hdHVyYWwgZm9vZCBmb3IgZG9ncyJdLCJvYnNlcnZlZF9pZGVudGl0eSI6eyJicmFuZCI6InJhY2hhZWwgcmF5IG51dHJpc2giLCJwZXRfdHlwZSI6ImRvZyIsImxpZmVfc3RhZ2UiOiJ1bmtub3duIiwiZm9vZF9mb3JtIjoiZHJ5In0sInRhcmdldF9pZGVudGl0eSI6eyJicmFuZCI6Ik51dHJpc2giLCJwcm9kdWN0X25hbWUiOiJSYWNoYWVsIFJheSBOdXRyaXNoIEhpZ2ggUHJvdGVpbiBCZWVmLCBQb3RhdG8gJiBQZWFzIFJlY2lwZSBEcnkgRG9nIEZvb2QiLCJwcm9kdWN0X2xpbmUiOiJSYWNoYWVsIFJheSBOdXRyaXNoIEhpZ2ggUHJvdGVpbiIsImZsYXZvciI6IlBvdGF0byAmIFBlYXMgUmVjaXBlIiwicGV0X3R5cGUiOiJkb2ciLCJsaWZlX3N0YWdlIjpudWxsLCJmb29kX2Zvcm0iOiJkcnkiLCJwYWNrYWdlX3NpemUiOm51bGx9LCJvZmZpY2lhbF9kYXRhYmFzZV9pbWFnZV91cmwiOiJodHRwczovL3d3dy5udXRyaXNoLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAyNC8wMy8wMDA3MTE5MDAwMzQyM19BMU4xXzQ5NjY2LmF2aWYiLCJvZmZpY2lhbF9pbWFnZV91cmwiOiJodHRwczovL3d3dy5udXRyaXNoLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAyNC8wMy8wMDA3MTE5MDAwMzQyM19BMU4xXzQ5NjY2LmF2aWYiLCJvZmZpY2lhbF9pbmdyZWRpZW50X2NvdW50IjozOSwib2ZmaWNpYWxfZGF0YWJhc2VfaW5ncmVkaWVudF9oYXNoIjoiZWM2NmJiOTYxMDgwYTA5OTBlNDE0NDc2ODk4ZjAxY2NmNGU4YTlmYzQ5ZTAxMjdlYTE1Y2EyYzdkODIyNTBlNCIsIm9mZmljaWFsX2Nhbm9uaWNhbF9pbmdyZWRpZW50X2hhc2giOiJmMDZmNmJiM2Y0ZTM2NDdlMmNlNGMxNTE5ZmM0ZGEwNDY3OGZiNTU3ZTczMTU3ZjE0Mzc3NGUwZGMxMTM3YTU4Iiwib2ZmaWNpYWxfcmF3X2luZ3JlZGllbnRfaGFzaCI6ImFkMGJlNjc1MTQ5ODQwNzI1NmFhZTA3NGY1M2M4ZTkyOGU3MjI3NWQxOWI0YjM2YzZiZThlZDNhYjllNWU4MjIiLCJvZmZpY2lhbF9vYnNlcnZlZF9hdCI6IjIwMjYtMDctMjZUMTI6Mzc6MzIuMTM2KzAwOjAwIiwiZm9ybXVsYV9pZF9oaW50IjoiNTliNWNhOGMtNjlkYy00ZWFhLWEyYzAtMjIyOTAyNDJmZDg5IiwiYXVkaXRfc2NvcmUiOjEsImF1ZGl0X21hcmdpbiI6MC42NjY3LCJhdWRpdF9zaGFyZWRfdGVybXMiOlsicHJvdGVpbiIsImJlZWYiLCJwb3RhdG8iLCJwZWFzIl19LHsiYWxpYXNfZm9ybXVsYV9rZXkiOiJyYWNoYWVsIHJheSBudXRyaXNofHJhY2hhZWwgcmF5IG51dHJpc2h8cmFjaGFlbCByYXkgbnV0cmlzaCBncmFpbiBmcmVlIGNoaWNrZW4gYW5kIHN3ZWV0IHBvdGF0byByZWNpcGUgZHJ5IGRvZyBmb29kfGRvZ3x1bmtub3dufGRyeXx8Iiwic291cmNlX3VybCI6Imh0dHBzOi8vd3d3LmNoZXd5LmNvbS9yYWNoYWVsLXJheS1udXRyaXNoLXplcm8tZ3JhaW4vZHAvMjk4MDY2Iiwib2ZmaWNpYWxfc291cmNlX3VybCI6Imh0dHBzOi8vd3d3Lm51dHJpc2guY29tL3Byb2R1Y3QvbnV0cmlzaC1ncmFpbi1mcmVlLWNoaWNrZW4tc3dlZXQtcG90YXRvLXJlY2lwZS1kcnktZG9nLWZvb2QvIiwiY2FjaGVfa2V5IjoibnV0cmlzaDpudXRyaXNoIHJhY2hhZWwgcmF5IG51dHJpc2ggZ3JhaW4gZnJlZSBjaGlja2VuIHN3ZWV0IHBvdGF0byByZWNpcGUgZHJ5IGRvZyBmb29kIiwidGFyZ2V0X2Zvcm11bGFfa2V5IjoibnV0cmlzaHxudXRyaXNofHJhY2hhZWwgcmF5IG51dHJpc2ggZ3JhaW4gZnJlZSBjaGlja2VuIGFuZCBzd2VldCBwb3RhdG8gcmVjaXBlIGRyeSBkb2cgZm9vZHxkb2d8dW5rbm93bnxkcnl8cmFjaGFlbCByYXkgZ3JhaW4gZnJlZSBjaGlja2VuIGFuZCBzd2VldCBwb3RhdG8gcmVjaXBlfCIsInJldmlld2VkX2F0IjoiMjAyNi0wOC0xMFQwNDoyOTowMC4wMDBaIiwicmV2aWV3X21ldGhvZCI6InB1YmxpY19yZXRhaWxlcl9mcm9udF9vY3JfdG9fb2ZmaWNpYWxfc3RydWN0dXJlZF9pZGVudGl0eV9tYW51YWxfcmV2aWV3IiwicmV2aWV3X3JlYXNvbiI6Ik1hbnVhbCByZXZpZXcgb2YgdGhlIHB1YmxpYyByZXRhaWxlciBwYWNrYWdlIGZyb250IGNvbmZpcm1zIHRoYXQgdGhlIFJhY2hhZWwgUmF5IE51dHJpc2ggZGVtYW5kIGxhYmVsIGFuZCB0aGUgTnV0cmlzaCBtYW51ZmFjdHVyZXIgbGFiZWwgcmVmZXIgdG8gdGhlIHNhbWUgc3BlY2llcywgZm9vZCBmb3JtLCByZWNpcGUsIHByZXNlbnRhdGlvbiwgYW5kIGNvbmRpdGlvbiBmb3Igb25lIG1hbnVmYWN0dXJlci1jdXJyZW50IGZvcm11bGEuIEZyb250LWxhYmVsIE9DUiBpcyBpZGVudGl0eSBldmlkZW5jZSBvbmx5OyBpbmdyZWRpZW50cyBhbmQgdGhlIHNlcnZpbmcgaW1hZ2UgcmVtYWluIGJvdW5kIHRvIHRoZSBtYW51ZmFjdHVyZXIgcm93LiIsInJldGFpbGVyX2lkZW50aXR5X29ubHkiOnRydWUsInJldGFpbGVyX2luZ3JlZGllbnRfdmVyaWZpY2F0aW9uIjpmYWxzZSwicmV0YWlsZXJfc291cmNlX3NsdWciOiJjaGV3eS1wdWJsaWMtc2l0ZW1hcCIsInJldGFpbGVyX3Byb2R1Y3RfaWQiOiIyOTgwNjYiLCJyZXRhaWxlcl90aXRsZSI6IlJhY2hhZWwgUmF5IE51dHJpc2ggR3JhaW4tRnJlZSBDaGlja2VuICYgU3dlZXQgUG90YXRvIFJlY2lwZSBEcnkgRG9nIEZvb2QiLCJyZXRhaWxlcl9vYnNlcnZlZF9hdCI6IjIwMjYtMDctMjRUMjE6MTI6MjIuNzU5WiIsInJldGFpbGVyX2NvbnRlbnRfaGFzaCI6IjM0OWNhNmZmMDk1ZDgwNTNhMjMzMTI1NzdhODIzZGI4OWRlOGNjYTkwZTA2ZWU2ZjQ2ZDczMWU5MGMyMmViMmMiLCJyZXRhaWxlcl9mcm9udF9pbWFnZV91cmwiOiJodHRwczovL2ltYWdlLmNoZXd5LmNvbS9jYXRhbG9nL2dlbmVyYWwvaW1hZ2VzL21vZS8wNmEwZTEwYy01YWU1LTdmZjItODAwMC04ZjhiMzc4OWJjZmUuX1YxXy5qcGciLCJyZXRhaWxlcl9mcm9udF9pbWFnZV9zaGEyNTYiOiIzYjQzOGE0ODZlMmIzNmE5MjQ0ODhmOGY1MDU2NTk2NGViZGRkOGQ2NmRmNTg3YTQ5ZjUyYzQzY2Q5ODZkMDk0IiwicmV0YWlsZXJfZnJvbnRfbGFiZWxfb2NyIjoiRXZlcnkgQmFnIEhlbHBzIEFuaW1hbHMgaW4gTmVlZC4gTnV0cmlzaCBJTkdSRURJRU5JIFJFQUkgSUhJKEtFTiBHUkFJTiAtRlJFRS0gQ0hJQ0tFTiAmIFNXRUVUIFBPVEFUTyBSRUNJUEUgTk8gQURERUQgU1dFRVQgUE9UQVRPRVMgUkVBTCBDSElDS0VOIE5FVFdUIDEzIExCMTUuOSBrZykgVkVURVJJTkFSSUFOIFJFVklFV0VEIEZEUk1VTEEgQ09NUExFVEUgQU5EIEJBTEFOQ0VEIE5BVFVSQUxGT09EIEZPUiBET0dTIiwibWFudWFsX3BhY2thZ2VfaW1hZ2VfbWF0Y2giOnRydWUsIm1hbnVhbF9mcm9udF9sYWJlbF9vY3JfbWF0Y2giOnRydWUsIm1hbnVhbF9mcm9udF9sYWJlbF92aXN1YWxfbWF0Y2giOnRydWUsInJlcXVpcmVkX29jcl90ZXJtcyI6WyJudXRyaXNoIiwiZ3JhaW4gZnJlZSIsImNoaWNrZW4iLCJzd2VldCBwb3RhdG8iLCIxM2xiIiwiZG9ncyJdLCJwcm90ZWN0ZWRfaWRlbnRpdHlfdGVybXMiOlsibnV0cmlzaCIsImdyYWluIGZyZWUiLCJjaGlja2VuIGFuZCBzd2VldCBwb3RhdG8gcmVjaXBlIiwicmVhbCBjaGlja2VuIiwiMTMgbGIiLCJuYXR1cmFsIGZvb2QgZm9yIGRvZ3MiXSwib2JzZXJ2ZWRfaWRlbnRpdHkiOnsiYnJhbmQiOiJyYWNoYWVsIHJheSBudXRyaXNoIiwicGV0X3R5cGUiOiJkb2ciLCJsaWZlX3N0YWdlIjoidW5rbm93biIsImZvb2RfZm9ybSI6ImRyeSJ9LCJ0YXJnZXRfaWRlbnRpdHkiOnsiYnJhbmQiOiJOdXRyaXNoIiwicHJvZHVjdF9uYW1lIjoiUmFjaGFlbCBSYXkgTnV0cmlzaCBHcmFpbiBGcmVlIENoaWNrZW4gJiBTd2VldCBQb3RhdG8gUmVjaXBlIERyeSBEb2cgRm9vZCIsInByb2R1Y3RfbGluZSI6IlJhY2hhZWwgUmF5IE51dHJpc2ggR3JhaW4gRnJlZSIsImZsYXZvciI6IlJhY2hhZWwgUmF5IEdyYWluIEZyZWUgQ2hpY2tlbiAmIFN3ZWV0IFBvdGF0byBSZWNpcGUiLCJwZXRfdHlwZSI6ImRvZyIsImxpZmVfc3RhZ2UiOm51bGwsImZvb2RfZm9ybSI6ImRyeSIsInBhY2thZ2Vfc2l6ZSI6bnVsbH0sIm9mZmljaWFsX2RhdGFiYXNlX2ltYWdlX3VybCI6Imh0dHBzOi8vd3d3Lm51dHJpc2guY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDI0LzAzLzEuMC1EcnktRG9nLUdyYWluLUZyZWUtQ2hpY2tlbi1Td2VldC1Qb3RhdG8tMjYtbGIuYXZpZiIsIm9mZmljaWFsX2ltYWdlX3VybCI6Imh0dHBzOi8vd3d3Lm51dHJpc2guY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDI0LzAzLzEuMC1EcnktRG9nLUdyYWluLUZyZWUtQ2hpY2tlbi1Td2VldC1Qb3RhdG8tMjYtbGIuYXZpZiIsIm9mZmljaWFsX2luZ3JlZGllbnRfY291bnQiOjQxLCJvZmZpY2lhbF9kYXRhYmFzZV9pbmdyZWRpZW50X2hhc2giOiIzZTgwMmUyNmMzZGRhOTIzZjkxOGFiZmQ0YTIyY2Q5NzdjNDQyNTIyNTA0OTViNGJjMTVlODlmNDc1YzY1YTllIiwib2ZmaWNpYWxfY2Fub25pY2FsX2luZ3JlZGllbnRfaGFzaCI6ImI5NzY2ZTMxYWMyZjMwNjU0YzdmMWEwNWY1NzY1ZDBkNDZjMGE1ZDQ2MGZhNjVlOWYxMmFiOGQzNjFhMmVhZjAiLCJvZmZpY2lhbF9yYXdfaW5ncmVkaWVudF9oYXNoIjoiMzNjMTM3MzY0NzVhMzEyZTlhOTg3MWJmOGM4ZTgzOWM0NTYwZjk5NDRjZTZhOWM0YWM3MWYwZDJmMWI3NGJmMSIsIm9mZmljaWFsX29ic2VydmVkX2F0IjoiMjAyNi0wNy0yNlQxMjozNzozMi4xMzYrMDA6MDAiLCJmb3JtdWxhX2lkX2hpbnQiOiIwNzczN2I5NC05Mjk3LTQzMTEtYmViNC1iODc0NjVjMjE4NzYiLCJhdWRpdF9zY29yZSI6MSwiYXVkaXRfbWFyZ2luIjowLjMzMzMsImF1ZGl0X3NoYXJlZF90ZXJtcyI6WyJjaGlja2VuIiwic3dlZXQiLCJwb3RhdG8iXX0seyJhbGlhc19mb3JtdWxhX2tleSI6InJhY2hhZWwgcmF5IG51dHJpc2h8cmFjaGFlbCByYXkgbnV0cmlzaHxyYWNoYWVsIHJheSBudXRyaXNoIHdob2xlIGhlYWx0aCBibGVuZCByZWFsIHNhbG1vbiB2ZWdnaWVzIGFuZCBicm93biByaWNlIHJlY2lwZSBnZW50bGUgZGlnZXN0aW9uIGRyeSBkb2cgZm9vZHxkb2d8dW5rbm93bnxkcnl8fCIsInNvdXJjZV91cmwiOiJodHRwczovL3d3dy5jaGV3eS5jb20vcmFjaGFlbC1yYXktbnV0cmlzaC1yZWFsLXNhbG1vbi9kcC8zOTQ4NTY2Iiwib2ZmaWNpYWxfc291cmNlX3VybCI6Imh0dHBzOi8vd3d3Lm51dHJpc2guY29tL3Byb2R1Y3QvbnV0cmlzaC1yZWFsLXNhbG1vbi12ZWdnaWVzLWJyb3duLXJpY2UtcmVjaXBlLWRyeS1kb2ctZm9vZC8iLCJjYWNoZV9rZXkiOiJudXRyaXNoOm51dHJpc2ggcmFjaGFlbCByYXkgbnV0cmlzaCByZWFsIHNhbG1vbiB2ZWdnaWVzIGJyb3duIHJpY2UgZHJ5IGRvZyBmb29kIiwidGFyZ2V0X2Zvcm11bGFfa2V5IjoibnV0cmlzaHxudXRyaXNofHJhY2hhZWwgcmF5IG51dHJpc2ggYWR1bHQgZHJ5IGRvZyBmb29kIHJlYWwgc2FsbW9uIHZlZ2dpZXMgYW5kIGJyb3duIHJpY2UgcmVjaXBlfGRvZ3xhZHVsdHxkcnl8dmVnZ2llcyBhbmQgYnJvd24gcmljZSByZWNpcGV8IiwicmV2aWV3ZWRfYXQiOiIyMDI2LTA4LTEwVDA0OjI5OjAwLjAwMFoiLCJyZXZpZXdfbWV0aG9kIjoicHVibGljX3JldGFpbGVyX2Zyb250X29jcl90b19vZmZpY2lhbF9zdHJ1Y3R1cmVkX2lkZW50aXR5X21hbnVhbF9yZXZpZXciLCJyZXZpZXdfcmVhc29uIjoiTWFudWFsIHJldmlldyBvZiB0aGUgcHVibGljIHJldGFpbGVyIHBhY2thZ2UgZnJvbnQgY29uZmlybXMgdGhhdCB0aGUgUmFjaGFlbCBSYXkgTnV0cmlzaCBkZW1hbmQgbGFiZWwgYW5kIHRoZSBOdXRyaXNoIG1hbnVmYWN0dXJlciBsYWJlbCByZWZlciB0byB0aGUgc2FtZSBzcGVjaWVzLCBmb29kIGZvcm0sIHJlY2lwZSwgcHJlc2VudGF0aW9uLCBhbmQgY29uZGl0aW9uIGZvciBvbmUgbWFudWZhY3R1cmVyLWN1cnJlbnQgZm9ybXVsYS4gRnJvbnQtbGFiZWwgT0NSIGlzIGlkZW50aXR5IGV2aWRlbmNlIG9ubHk7IGluZ3JlZGllbnRzIGFuZCB0aGUgc2VydmluZyBpbWFnZSByZW1haW4gYm91bmQgdG8gdGhlIG1hbnVmYWN0dXJlciByb3cuIiwicmV0YWlsZXJfaWRlbnRpdHlfb25seSI6dHJ1ZSwicmV0YWlsZXJfaW5ncmVkaWVudF92ZXJpZmljYXRpb24iOmZhbHNlLCJyZXRhaWxlcl9zb3VyY2Vfc2x1ZyI6ImNoZXd5LXB1YmxpYy1zaXRlbWFwIiwicmV0YWlsZXJfcHJvZHVjdF9pZCI6IjM5NDg1NjYiLCJyZXRhaWxlcl90aXRsZSI6IlJhY2hhZWwgUmF5IE51dHJpc2ggV2hvbGUgSGVhbHRoIEJsZW5kIFJlYWwgU2FsbW9uLCBWZWdnaWVzICYgQnJvd24gUmljZSBSZWNpcGUgR2VudGxlIERpZ2VzdGlvbiBEcnkgRG9nIEZvb2QiLCJyZXRhaWxlcl9vYnNlcnZlZF9hdCI6IjIwMjYtMDgtMDVUMjA6NTU6MjkuOTg0WiIsInJldGFpbGVyX2NvbnRlbnRfaGFzaCI6ImQ5Mzg4NDZjNTI5MTJiMWU5Mjc4NzIyMWI3OTZkNDkwNTY3OGNiZDk5OTMxMTUyYTdhYzRmOGY2NWM5MGUwZDYiLCJyZXRhaWxlcl9mcm9udF9pbWFnZV91cmwiOiJodHRwczovL2ltYWdlLmNoZXd5LmNvbS9jYXRhbG9nL2dlbmVyYWwvaW1hZ2VzL21vZS8wNmEyNmZjNS0xNGZiLTdlNjAtODAwMC01YmNmOTRiOTlhYzYuX1YxXy5qcGciLCJyZXRhaWxlcl9mcm9udF9pbWFnZV9zaGEyNTYiOiJhYTE5ODhmYzRjMzQ2ZTIxNjAzOTRhYjhjMTMxN2M5ZGY0NGFmMTM2OGVhNjE1OWVlNTBmZGY4ZGM0YTMyMGVkIiwicmV0YWlsZXJfZnJvbnRfbGFiZWxfb2NyIjoiRVZFUlkgU0FHIEhFTFBTIEFOSU1BTFMgSU4gTkVFIHI0ZypGKkVMUkFZJyBOdXRyaXNoIFZFVEVSSU5BUklBSyBSRVZJRVdFTyBGT1JNVUxBIFJFQUwgU0FMTU9OICNJIElOR1JFRElFTlQgUkVBTCBTQUxNT04sIFZFR0dJRVMgJiBCUk9XTiBSSUNFIFJFQ0lQRSBSZWFsIEluZ3JlZGxlbnRzLiBSZWFsIFJlY2xwZXMuIFJFQUwgR09PRC4gTmF0dWlhbCBmb29kIHdsdGggYWRkb2Qgdmx0YW1sbnMuIE5vIGFydGxmbGNsYWwgwqXDqHNsbHkgZGxnw6hzdGxibGUgaGVhbHRoeSBkbDllU3Rsb24gRFJZIERPRyBGT09EIHwgTkVUV1QgNC41IElCICgyLjA0IGtnKSIsIm1hbnVhbF9wYWNrYWdlX2ltYWdlX21hdGNoIjp0cnVlLCJtYW51YWxfZnJvbnRfbGFiZWxfb2NyX21hdGNoIjp0cnVlLCJtYW51YWxfZnJvbnRfbGFiZWxfdmlzdWFsX21hdGNoIjp0cnVlLCJyZXF1aXJlZF9vY3JfdGVybXMiOlsibnV0cmlzaCIsInJlYWwgc2FsbW9uIiwidmVnZ2llcyIsImJyb3duIHJpY2UiLCJkcnkgZG9nIGZvb2QiLCI0LjUgaWIiXSwicHJvdGVjdGVkX2lkZW50aXR5X3Rlcm1zIjpbInJhY2hhZWwgcmF5IG51dHJpc2giLCJyZWFsIHNhbG1vbiB2ZWdnaWVzIGFuZCBicm93biByaWNlIHJlY2lwZSIsImRyeSBkb2cgZm9vZCIsIjQuNSBsYiJdLCJvYnNlcnZlZF9pZGVudGl0eSI6eyJicmFuZCI6InJhY2hhZWwgcmF5IG51dHJpc2giLCJwZXRfdHlwZSI6ImRvZyIsImxpZmVfc3RhZ2UiOiJ1bmtub3duIiwiZm9vZF9mb3JtIjoiZHJ5In0sInRhcmdldF9pZGVudGl0eSI6eyJicmFuZCI6Ik51dHJpc2giLCJwcm9kdWN0X25hbWUiOiJSYWNoYWVsIFJheSBOdXRyaXNoIEFkdWx0IERyeSBEb2cgRm9vZCBSZWFsIFNhbG1vbiwgVmVnZ2llcyAmIEJyb3duIFJpY2UgUmVjaXBlIiwicHJvZHVjdF9saW5lIjoiUmFjaGFlbCBSYXkgTnV0cmlzaCBBZHVsdCBEcnkgUmVhbCIsImZsYXZvciI6IlZlZ2dpZXMgJiBCcm93biBSaWNlIFJlY2lwZSIsInBldF90eXBlIjoiZG9nIiwibGlmZV9zdGFnZSI6ImFkdWx0IiwiZm9vZF9mb3JtIjoiZHJ5IiwicGFja2FnZV9zaXplIjpudWxsfSwib2ZmaWNpYWxfZGF0YWJhc2VfaW1hZ2VfdXJsIjoiaHR0cHM6Ly93d3cubnV0cmlzaC5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMjQvMDMvMDAwNzExOTA1NDM2MDhfQTFOMV80OTIyMy5hdmlmIiwib2ZmaWNpYWxfaW1hZ2VfdXJsIjoiaHR0cHM6Ly93d3cubnV0cmlzaC5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMjQvMDMvMDAwNzExOTA1NDM2MDhfQTFOMV80OTIyMy5hdmlmIiwib2ZmaWNpYWxfaW5ncmVkaWVudF9jb3VudCI6NDAsIm9mZmljaWFsX2RhdGFiYXNlX2luZ3JlZGllbnRfaGFzaCI6ImE5YjM4ZjExZTNkNjAwOTM4Nzc0MTFkNzRhMjZiOGE5NDk4ZGExYzRiYjQ3OWM3OTIwZmJmNGZlODI0NjM5NzkiLCJvZmZpY2lhbF9jYW5vbmljYWxfaW5ncmVkaWVudF9oYXNoIjoiZjA1MjNmMTk2NjU5ZjgxZGZhYTdmMTUwZjIxNjg2YmQ5YTQ5NGZkNTgxNTRiY2ZjYmY3MjQ1NzBmOTE5NWFkZSIsIm9mZmljaWFsX3Jhd19pbmdyZWRpZW50X2hhc2giOiIwZjFjZjNjOWI4NTAyZDAwNDI5NGI5NWMxNTBhYjlkN2UyNjc5YmZkN2YwZjdkNzQwNzYyZDJlNmMyYjE3ODQ3Iiwib2ZmaWNpYWxfb2JzZXJ2ZWRfYXQiOiIyMDI2LTA3LTI2VDEyOjM3OjMyLjEzNiswMDowMCIsImZvcm11bGFfaWRfaGludCI6ImQ1YTU3MzExLTE1ZTUtNDM1ZC04MzNhLWNiZmEyMjY5NzI4OSIsImF1ZGl0X3Njb3JlIjoxLCJhdWRpdF9tYXJnaW4iOjAuMzMzMywiYXVkaXRfc2hhcmVkX3Rlcm1zIjpbInJlYWwiLCJzYWxtb24iLCJ2ZWdnaWVzIiwiYnJvd24iLCJyaWNlIl19LHsiYWxpYXNfZm9ybXVsYV9rZXkiOiJyYWNoYWVsIHJheSBudXRyaXNofHJhY2hhZWwgcmF5IG51dHJpc2h8cmFjaGFlbCByYXkgbnV0cmlzaCByZWFsIHNhbG1vbiBhbmQgYnJvd24gcmljZSByZWNpcGUgZHJ5IGNhdCBmb29kfGNhdHx1bmtub3dufGRyeXx8Iiwic291cmNlX3VybCI6Imh0dHBzOi8vd3d3LmNoZXd5LmNvbS9yYWNoYWVsLXJheS1udXRyaXNoLXJlYWwtc2FsbW9uLWJyb3duL2RwLzM5NDg3MTgiLCJvZmZpY2lhbF9zb3VyY2VfdXJsIjoiaHR0cHM6Ly93d3cubnV0cmlzaC5jb20vcHJvZHVjdC9udXRyaXNoLXJlYWwtc2FsbW9uLWJyb3duLXJpY2UtcmVjaXBlLWRyeS1jYXQtZm9vZC8iLCJjYWNoZV9rZXkiOiJudXRyaXNoOm51dHJpc2ggcmFjaGFlbCByYXkgbnV0cmlzaCByZWFsIHNhbG1vbiBicm93biByaWNlIHJlY2lwZSB3aG9sZSBoZWFsdGggYmxlbmQgZHJ5IGZvb2QgZm9yIGNhdHMiLCJ0YXJnZXRfZm9ybXVsYV9rZXkiOiJudXRyaXNofG51dHJpc2h8cmFjaGFlbCByYXkgbnV0cmlzaCBkcnkgY2F0IGZvb2QgcmVhbCBzYWxtb24gYW5kIGJyb3duIHJpY2UgcmVjaXBlfGNhdHx1bmtub3dufGRyeXxyYWNoYWVsIHJheSByZWFsIHNhbG1vbiBhbmQgYnJvd24gcmljZSByZWNpcGV8IiwicmV2aWV3ZWRfYXQiOiIyMDI2LTA4LTEwVDA0OjI5OjAwLjAwMFoiLCJyZXZpZXdfbWV0aG9kIjoicHVibGljX3JldGFpbGVyX2Zyb250X29jcl90b19vZmZpY2lhbF9zdHJ1Y3R1cmVkX2lkZW50aXR5X21hbnVhbF9yZXZpZXciLCJyZXZpZXdfcmVhc29uIjoiTWFudWFsIHJldmlldyBvZiB0aGUgcHVibGljIHJldGFpbGVyIHBhY2thZ2UgZnJvbnQgY29uZmlybXMgdGhhdCB0aGUgUmFjaGFlbCBSYXkgTnV0cmlzaCBkZW1hbmQgbGFiZWwgYW5kIHRoZSBOdXRyaXNoIG1hbnVmYWN0dXJlciBsYWJlbCByZWZlciB0byB0aGUgc2FtZSBzcGVjaWVzLCBmb29kIGZvcm0sIHJlY2lwZSwgcHJlc2VudGF0aW9uLCBhbmQgY29uZGl0aW9uIGZvciBvbmUgbWFudWZhY3R1cmVyLWN1cnJlbnQgZm9ybXVsYS4gRnJvbnQtbGFiZWwgT0NSIGlzIGlkZW50aXR5IGV2aWRlbmNlIG9ubHk7IGluZ3JlZGllbnRzIGFuZCB0aGUgc2VydmluZyBpbWFnZSByZW1haW4gYm91bmQgdG8gdGhlIG1hbnVmYWN0dXJlciByb3cuIiwicmV0YWlsZXJfaWRlbnRpdHlfb25seSI6dHJ1ZSwicmV0YWlsZXJfaW5ncmVkaWVudF92ZXJpZmljYXRpb24iOmZhbHNlLCJyZXRhaWxlcl9zb3VyY2Vfc2x1ZyI6ImNoZXd5LXB1YmxpYy1zaXRlbWFwIiwicmV0YWlsZXJfcHJvZHVjdF9pZCI6IjM5NDg3MTgiLCJyZXRhaWxlcl90aXRsZSI6IlJhY2hhZWwgUmF5IE51dHJpc2ggUmVhbCBTYWxtb24gJiBCcm93biBSaWNlIFJlY2lwZSBEcnkgQ2F0IEZvb2QiLCJyZXRhaWxlcl9vYnNlcnZlZF9hdCI6IjIwMjYtMDgtMDVUMjA6NTU6MzAuMjM1WiIsInJldGFpbGVyX2NvbnRlbnRfaGFzaCI6IjlhZGFiOWMyMTE3ODQzYzE4YzFiNTc5NGI0MTVmZDY3MWE2YzE3NDg4Y2ZkY2VmYjZiZDI5MWNkODJkYWY3ZWEiLCJyZXRhaWxlcl9mcm9udF9pbWFnZV91cmwiOiJodHRwczovL2ltYWdlLmNoZXd5LmNvbS9jYXRhbG9nL2dlbmVyYWwvaW1hZ2VzL21vZS8wNjk5MmU5MS02ZmE3LTc5MTctODAwMC1hZWI0NDk4OWM5ZTAuX1YxXy5qcGciLCJyZXRhaWxlcl9mcm9udF9pbWFnZV9zaGEyNTYiOiI2MWFlNGIxZDg1M2RhZGJiYmU3MDRlYTEzMGJjMjcxY2E3NTEyYzE1ZjkwNDkwMDk0ZmQyM2JhNzE5MzNjMjhjIiwicmV0YWlsZXJfZnJvbnRfbGFiZWxfb2NyIjoiRVZFUlkgOGhHIEhlTFA1IEFOSU1BTFMgSU4gTkVFRCBOdXRyaXNoIFZFdEVSSU5BUklBTiBSRVZJRVdFRCBGT1JNVUxBIFJFQUwgU0FMTU9OIElOR1JFRElFTlQgUkVBTCBTQUxNT04gJiBCUk9XTiBSSUNFIFJFQ0lQRSBSZWFsIEluZ3JlZGxlbnRzLiBSZWFsIFJlY2xwZXMuIFJFQUwgR09PRC4gTmF0dXJhbCBmb29kIHdsdGggYWRkZWQgdml0YW1sbnMuIG1sbmVyYWxzICYgbnV0cmxlbnRzIE5vIGFydGxmbGNsIENvbXBsZXRzIC7igKIgYmFsYW5j4oCiZCBmb3IgYWxsIElsbGUgc3RhZ2UkIE9SWSBDQVQgRk9PRCB8IE5FVFdUIDUgTEIgKDIuMjcga2cpIiwibWFudWFsX3BhY2thZ2VfaW1hZ2VfbWF0Y2giOnRydWUsIm1hbnVhbF9mcm9udF9sYWJlbF9vY3JfbWF0Y2giOnRydWUsIm1hbnVhbF9mcm9udF9sYWJlbF92aXN1YWxfbWF0Y2giOnRydWUsInJlcXVpcmVkX29jcl90ZXJtcyI6WyJudXRyaXNoIiwicmVhbCBzYWxtb24iLCJicm93biByaWNlIiwib3J5IGNhdCBmb29kIiwiNWxiIl0sInByb3RlY3RlZF9pZGVudGl0eV90ZXJtcyI6WyJyYWNoYWVsIHJheSBudXRyaXNoIiwicmVhbCBzYWxtb24gYW5kIGJyb3duIHJpY2UgcmVjaXBlIiwiZHJ5IGNhdCBmb29kIiwiNSBsYiIsImFsbCBsaWZlIHN0YWdlcyJdLCJvYnNlcnZlZF9pZGVudGl0eSI6eyJicmFuZCI6InJhY2hhZWwgcmF5IG51dHJpc2giLCJwZXRfdHlwZSI6ImNhdCIsImxpZmVfc3RhZ2UiOiJ1bmtub3duIiwiZm9vZF9mb3JtIjoiZHJ5In0sInRhcmdldF9pZGVudGl0eSI6eyJicmFuZCI6Ik51dHJpc2giLCJwcm9kdWN0X25hbWUiOiJSYWNoYWVsIFJheSBOdXRyaXNoIERyeSBDYXQgRm9vZCBSZWFsIFNhbG1vbiAmIEJyb3duIFJpY2UgUmVjaXBlIiwicHJvZHVjdF9saW5lIjoiUmFjaGFlbCBSYXkgTnV0cmlzaCBEcnkgUmVhbCIsImZsYXZvciI6IlJhY2hhZWwgUmF5IFJlYWwgU2FsbW9uICYgQnJvd24gUmljZSBSZWNpcGUiLCJwZXRfdHlwZSI6ImNhdCIsImxpZmVfc3RhZ2UiOm51bGwsImZvb2RfZm9ybSI6ImRyeSIsInBhY2thZ2Vfc2l6ZSI6bnVsbH0sIm9mZmljaWFsX2RhdGFiYXNlX2ltYWdlX3VybCI6Imh0dHBzOi8vd3d3Lm51dHJpc2guY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDI0LzAzLzAwMDcxMTkwMDA3MDE4X0ExTjFfNDk5MzkuYXZpZiIsIm9mZmljaWFsX2ltYWdlX3VybCI6Imh0dHBzOi8vd3d3Lm51dHJpc2guY29tL3dwLWNvbnRlbnQvdXBsb2Fkcy8yMDI0LzAzLzAwMDcxMTkwMDA3MDE4X0ExTjFfNDk5MzkuYXZpZiIsIm9mZmljaWFsX2luZ3JlZGllbnRfY291bnQiOjQwLCJvZmZpY2lhbF9kYXRhYmFzZV9pbmdyZWRpZW50X2hhc2giOiIyYWJlNjIyNzJjMmMzMWNiOWFkOWYyZGIwYTRiZWQxNjY1Y2Y3ZDg4OGFhNWMxNmEzZWE5M2ZmOThkNjllNTBmIiwib2ZmaWNpYWxfY2Fub25pY2FsX2luZ3JlZGllbnRfaGFzaCI6ImFmMGFjNmMwMzZiMzJhNjQyOGY4NmE1ZWE4NzE2NjExMTdjMzQ3MmYzMzQzNzNkMjAwMzFlMTk1ZTYxZmVhZmYiLCJvZmZpY2lhbF9yYXdfaW5ncmVkaWVudF9oYXNoIjoiMjhiY2MyZGY0ZjM4MmM2ZDgwMGRmY2I0MjU5MjliODk0ODhlZmVhN2IxNmJjMDY5NmVlY2YwYTdkYjBhYjE1NyIsIm9mZmljaWFsX29ic2VydmVkX2F0IjoiMjAyNi0wNy0yNlQxMjozNzozMi4xMzYrMDA6MDAiLCJmb3JtdWxhX2lkX2hpbnQiOiI5MWQwMGUzMC00MjQwLTQyM2MtYjBiNy0wM2NiNTNlYWQxMDYiLCJhdWRpdF9zY29yZSI6MSwiYXVkaXRfbWFyZ2luIjowLjUsImF1ZGl0X3NoYXJlZF90ZXJtcyI6WyJyZWFsIiwic2FsbW9uIiwiYnJvd24iLCJyaWNlIl19LHsiYWxpYXNfZm9ybXVsYV9rZXkiOiJyYWNoYWVsIHJheSBudXRyaXNofHJhY2hhZWwgcmF5IG51dHJpc2h8cmFjaGFlbCByYXkgbnV0cmlzaCB3aG9sZSBoZWFsdGggYmxlbmQgcmVhbCBjaGlja2VuIGFuZCBhcHBsZSBjYW5uZWQgZG9nIGZvb2R8ZG9nfHVua25vd258d2V0fHwiLCJzb3VyY2VfdXJsIjoiaHR0cHM6Ly93d3cuY2hld3kuY29tL3JhY2hhZWwtcmF5LW51dHJpc2gtcmVhbC1jaGlja2VuL2RwLzM5OTY0MSIsIm9mZmljaWFsX3NvdXJjZV91cmwiOiJodHRwczovL3d3dy5udXRyaXNoLmNvbS9wcm9kdWN0L251dHJpc2gtcHJlbWl1bS1wYXRlLXJlYWwtY2hpY2tlbi1hcHBsZS1yZWNpcGUtd2V0LWRvZy1mb29kLyIsImNhY2hlX2tleSI6Im51dHJpc2g6bnV0cmlzaCByYWNoYWVsIHJheSBudXRyaXNoIHJlYWwgY2hpY2tlbiBhcHBsZSByZWNpcGUgd2hvbGUgaGVhbHRoIGJsZW5kIHByZW1pdW0gcGF0IHdldCBkb2cgZm9vZCIsInRhcmdldF9mb3JtdWxhX2tleSI6Im51dHJpc2h8bnV0cmlzaHxyYWNoYWVsIHJheSBudXRyaXNoIHJlYWwgY2hpY2tlbiBhbmQgYXBwbGUgcmVjaXBlIHByZW1pdW0gcGF0ZSB3ZXQgZG9nIGZvb2R8ZG9nfHVua25vd258d2V0fHJhY2hhZWwgcmF5IHJlYWwgY2hpY2tlbiBhbmQgYXBwbGUgcmVjaXBlfCIsInJldmlld2VkX2F0IjoiMjAyNi0wOC0xMFQwNDoyOTowMC4wMDBaIiwicmV2aWV3X21ldGhvZCI6InB1YmxpY19yZXRhaWxlcl9mcm9udF9vY3JfdG9fb2ZmaWNpYWxfc3RydWN0dXJlZF9pZGVudGl0eV9tYW51YWxfcmV2aWV3IiwicmV2aWV3X3JlYXNvbiI6Ik1hbnVhbCByZXZpZXcgb2YgdGhlIHB1YmxpYyByZXRhaWxlciBwYWNrYWdlIGZyb250IGNvbmZpcm1zIHRoYXQgdGhlIFJhY2hhZWwgUmF5IE51dHJpc2ggZGVtYW5kIGxhYmVsIGFuZCB0aGUgTnV0cmlzaCBtYW51ZmFjdHVyZXIgbGFiZWwgcmVmZXIgdG8gdGhlIHNhbWUgc3BlY2llcywgZm9vZCBmb3JtLCByZWNpcGUsIHByZXNlbnRhdGlvbiwgYW5kIGNvbmRpdGlvbiBmb3Igb25lIG1hbnVmYWN0dXJlci1jdXJyZW50IGZvcm11bGEuIEZyb250LWxhYmVsIE9DUiBpcyBpZGVudGl0eSBldmlkZW5jZSBvbmx5OyBpbmdyZWRpZW50cyBhbmQgdGhlIHNlcnZpbmcgaW1hZ2UgcmVtYWluIGJvdW5kIHRvIHRoZSBtYW51ZmFjdHVyZXIgcm93LiIsInJldGFpbGVyX2lkZW50aXR5X29ubHkiOnRydWUsInJldGFpbGVyX2luZ3JlZGllbnRfdmVyaWZpY2F0aW9uIjpmYWxzZSwicmV0YWlsZXJfc291cmNlX3NsdWciOiJjaGV3eS1wdWJsaWMtc2l0ZW1hcCIsInJldGFpbGVyX3Byb2R1Y3RfaWQiOiIzOTk2NDEiLCJyZXRhaWxlcl90aXRsZSI6IlJhY2hhZWwgUmF5IE51dHJpc2ggV2hvbGUgSGVhbHRoIEJsZW5kIFJlYWwgQ2hpY2tlbiAmIEFwcGxlIENhbm5lZCBEb2cgRm9vZCIsInJldGFpbGVyX29ic2VydmVkX2F0IjoiMjAyNi0wNy0yNFQyMToxMjoyNy43ODZaIiwicmV0YWlsZXJfY29udGVudF9oYXNoIjoiZWZlNTYxNDY4ZmQ2MmUwMTNhM2M1OGRkNWYyYTNlNmQ5MDI0ZDY2NzI4NmQzM2Q5YjgyZjJlOGM3MTRjNjFiMyIsInJldGFpbGVyX2Zyb250X2ltYWdlX3VybCI6Imh0dHBzOi8vaW1hZ2UuY2hld3kuY29tL2NhdGFsb2cvZ2VuZXJhbC9pbWFnZXMvbW9lLzA2ODM5YmFkLTBiNDUtN2U4OS04MDAwLTI3NWRjNmI3NGU4YS5fVjFfLmpwZyIsInJldGFpbGVyX2Zyb250X2ltYWdlX3NoYTI1NiI6ImZjOTY1NTM2NDJlMzQxOWY1OWVlZmY3Zjg2MmVjNzgwOGZmYjcwOTUzODQ1M2EwMGY0OTQ0MGQ5MGZhNjQ1MTQiLCJyZXRhaWxlcl9mcm9udF9sYWJlbF9vY3IiOiJQUkVNSVVNIFBBVMOJIFJFQUwgQ0hJQ0tFTiAmIEFQUExFIFJFQ0lQRSBQUkVNSVVNIFBBVMOJIFJFQUwgQ0hJQ0tFTiAmIEFQUExFIFJFQ0lQRSBQUkVNSVVNIFBBVEUgUkVBTCBDSElDS0VOICYgQVBQTEUgUkVDSVBFIE51dHJpc2ggTnV0cmlzaCBOdXRyaXNoIFsuIE51dHJpc2guIE1JWCBJVCBJTiwgVE9QIElUIE9GRiwgT1IgRkVFRCBBUyBBIEZJIE5FVyBMT09LIFZpc2l0IE51dHJpc2guY29tIHRvIHNlZSBhbGwgRHJ5IGFuZCBXZXQgRG9nIEZPTCIsIm1hbnVhbF9wYWNrYWdlX2ltYWdlX21hdGNoIjp0cnVlLCJtYW51YWxfZnJvbnRfbGFiZWxfb2NyX21hdGNoIjp0cnVlLCJtYW51YWxfZnJvbnRfbGFiZWxfdmlzdWFsX21hdGNoIjp0cnVlLCJyZXF1aXJlZF9vY3JfdGVybXMiOlsibnV0cmlzaCIsInByZW1pdW0gcGF0ZSIsInJlYWwgY2hpY2tlbiIsImFwcGxlIHJlY2lwZSJdLCJwcm90ZWN0ZWRfaWRlbnRpdHlfdGVybXMiOlsibnV0cmlzaCIsInByZW1pdW0gcGF0ZSIsInJlYWwgY2hpY2tlbiBhbmQgYXBwbGUgcmVjaXBlIiwid2V0IGRvZyBmb29kIl0sIm9ic2VydmVkX2lkZW50aXR5Ijp7ImJyYW5kIjoicmFjaGFlbCByYXkgbnV0cmlzaCIsInBldF90eXBlIjoiZG9nIiwibGlmZV9zdGFnZSI6InVua25vd24iLCJmb29kX2Zvcm0iOiJ3ZXQifSwidGFyZ2V0X2lkZW50aXR5Ijp7ImJyYW5kIjoiTnV0cmlzaCIsInByb2R1Y3RfbmFtZSI6IlJhY2hhZWwgUmF5IE51dHJpc2ggUmVhbCBDaGlja2VuICYgQXBwbGUgUmVjaXBlIFByZW1pdW0gUGF0w6kgV2V0IERvZyBGb29kIiwicHJvZHVjdF9saW5lIjoiUmFjaGFlbCBSYXkgTnV0cmlzaCBSZWFsIiwiZmxhdm9yIjoiUmFjaGFlbCBSYXkgUmVhbCBDaGlja2VuICYgQXBwbGUgUmVjaXBlIiwicGV0X3R5cGUiOiJkb2ciLCJsaWZlX3N0YWdlIjpudWxsLCJmb29kX2Zvcm0iOiJ3ZXQiLCJwYWNrYWdlX3NpemUiOm51bGx9LCJvZmZpY2lhbF9kYXRhYmFzZV9pbWFnZV91cmwiOiJodHRwczovL3d3dy5udXRyaXNoLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAyNC8wMy8wMDA3MTE5MDYxNTM0M19DMUMxX1BJTS5hdmlmIiwib2ZmaWNpYWxfaW1hZ2VfdXJsIjoiaHR0cHM6Ly93d3cubnV0cmlzaC5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMjQvMDMvMDAwNzExOTA2MTUzNDNfQzFDMV9QSU0uYXZpZiIsIm9mZmljaWFsX2luZ3JlZGllbnRfY291bnQiOjMxLCJvZmZpY2lhbF9kYXRhYmFzZV9pbmdyZWRpZW50X2hhc2giOiIzYjkxNmI3MzIzNWJlNDc1MDM0MDYyZGNlMzAxNTM0ZTVhNzhkMGFkMDhlMGZkMDIxN2Q3OGExMGU2MWQ2YjE2Iiwib2ZmaWNpYWxfY2Fub25pY2FsX2luZ3JlZGllbnRfaGFzaCI6IjQ1MjAwMzIzNWFjNWQ5ZDIxY2VkMjBjMmY0NDJiNzdkNjMzZDk3NDMyOGE1MGRhYWYzYzA3MzkzM2U0MmM1NGIiLCJvZmZpY2lhbF9yYXdfaW5ncmVkaWVudF9oYXNoIjoiMDVhYmM1NjYyNWM5MWQ5N2RjMzk2ODVmMWUxZjVjMDEzODVkODM5NzEwZjUzOWYzMmY1NjA2OTNkZDhjNGE2YyIsIm9mZmljaWFsX29ic2VydmVkX2F0IjoiMjAyNi0wNy0yNlQxMjozNzozMi4xMzYrMDA6MDAiLCJmb3JtdWxhX2lkX2hpbnQiOiJjMWQwZDY3Ni05NjFjLTRlNTMtYjUwNC04ZTgyMGFjYTc2MTMiLCJhdWRpdF9zY29yZSI6MSwiYXVkaXRfbWFyZ2luIjowLjUsImF1ZGl0X3NoYXJlZF90ZXJtcyI6WyJyZWFsIiwiY2hpY2tlbiIsImFwcGxlIiwicGF0ZSJdfV0=', 'base64'),
    'utf8'
  )::jsonb;
  v_alias JSONB;
  v_formula public.catalog_formulas%ROWTYPE;
  v_serving public.product_data%ROWTYPE;
  v_target_brand TEXT;
  v_target_pet_type TEXT;
  v_target_life_stage TEXT;
  v_target_food_form TEXT;
  v_normalized_alias TEXT;
  v_review_key TEXT;
  v_observation_id BIGINT;
  v_top_cache TEXT;
BEGIN
  FOR v_alias IN
    SELECT value
    FROM jsonb_array_elements(v_payload)
  LOOP
    v_target_brand := COALESCE(
      v_alias->>'target_brand',
      v_alias#>>'{target_identity,brand}'
    );
    v_target_pet_type := COALESCE(
      v_alias->>'target_pet_type',
      v_alias#>>'{target_identity,pet_type}'
    );
    v_target_life_stage := COALESCE(
      v_alias->>'target_life_stage',
      v_alias#>>'{target_identity,life_stage}'
    );
    v_target_food_form := COALESCE(
      v_alias->>'target_food_form',
      v_alias#>>'{target_identity,food_form}'
    );

    SELECT *
    INTO STRICT v_serving
    FROM public.product_data
    WHERE cache_key = v_alias->>'cache_key'
      AND brand = v_target_brand
      AND pet_type = v_target_pet_type
      AND COALESCE(life_stage, 'unknown') = COALESCE(v_target_life_stage, 'unknown')
      AND COALESCE(food_form, 'unknown') = COALESCE(v_target_food_form, 'unknown')
      AND source_url = v_alias->>'official_source_url'
      AND image_url = COALESCE(
        v_alias->>'official_database_image_url',
        v_alias->>'official_image_url'
      )
      AND ingredient_count = (v_alias->>'official_ingredient_count')::INTEGER
      AND encode(
        digest(
          public.catalog_normalize_ingredient_evidence(ingredient_text),
          'sha256'
        ),
        'hex'
      ) = v_alias->>'official_database_ingredient_hash'
      AND source_quality = 'manufacturer'
      AND ingredient_verification_status = 'manufacturer'
      AND image_verification_status = 'manufacturer'
      AND formula_evidence_tier = 'manufacturer_current_exact'
      AND is_complete_food
      AND catalog_exclusion_reason IS NULL;

    SELECT *
    INTO STRICT v_formula
    FROM public.catalog_formulas
    WHERE source_url = v_alias->>'official_source_url'
      AND brand = v_serving.brand
      AND product_name = v_serving.product_name
      AND COALESCE(product_line, '') = COALESCE(v_serving.product_line, '')
      AND COALESCE(flavor, '') = COALESCE(v_serving.flavor, '')
      AND pet_type = v_serving.pet_type
      AND COALESCE(life_stage, 'unknown') = COALESCE(v_serving.life_stage, 'unknown')
      AND COALESCE(food_form, 'unknown') = COALESCE(v_serving.food_form, 'unknown')
      AND cardinality(ingredients) = (v_alias->>'official_ingredient_count')::INTEGER
      AND encode(
        digest(
          public.catalog_normalize_ingredient_evidence(ingredient_text),
          'sha256'
        ),
        'hex'
      ) = v_alias->>'official_database_ingredient_hash'
      AND verification_status = 'verified'
      AND formula_evidence_tier = 'manufacturer_current_exact'
      AND ingredient_verification_status = 'manufacturer'
      AND image_verification_status = 'manufacturer'
      AND active;

    v_normalized_alias := public.normalize_verified_product_search_query(
      v_alias->>'retailer_title'
    );
    v_review_key := 'deterministic-retailer-identity-wave-nutrish_public_front_ocr_a:'
      || (v_alias->>'retailer_source_slug')
      || ':' || (v_alias->>'retailer_product_id');

    SELECT observation.id
    INTO v_observation_id
    FROM public.catalog_observations observation
    WHERE observation.source_slug = v_alias->>'retailer_source_slug'
      AND observation.source_external_id = v_alias->>'retailer_product_id'
      AND lower(regexp_replace(observation.source_url, '/+$', '')) =
          lower(regexp_replace(v_alias->>'source_url', '/+$', ''))
      AND lower(btrim(observation.product_name)) =
          lower(btrim(v_alias->>'retailer_title'))
    ORDER BY observation.observed_at DESC NULLS LAST, observation.id DESC
    LIMIT 1;

    IF EXISTS (
      SELECT 1
      FROM public.catalog_formula_aliases
      WHERE alias_formula_key = v_alias->>'alias_formula_key'
        AND formula_id <> v_formula.id
    ) THEN
      RAISE EXCEPTION 'Alias already belongs to another formula: %',
        v_alias->>'alias_formula_key';
    END IF;

    IF EXISTS (
      SELECT 1
      FROM public.catalog_verified_product_search_aliases
      WHERE active
        AND normalized_alias = v_normalized_alias
        AND cache_key <> v_serving.cache_key
    ) THEN
      RAISE EXCEPTION 'Search alias already belongs to another product: %',
        v_alias->>'retailer_title';
    END IF;

    INSERT INTO public.catalog_manual_evidence_reviews (
      review_key,
      target_formula_key,
      corrected_formula_key,
      brand,
      product_name,
      search_query,
      discovery_urls,
      authoritative_source_url,
      authoritative_source_type,
      expected_identity,
      resolved_identity,
      evidence_status,
      quarantine_reason,
      authoritative_content_hash,
      ingredient_text_hash,
      front_image_url_hash,
      observed_at,
      formula_id,
      promoted_cache_key,
      attempt_count,
      review_notes,
      ingredient_evidence_url,
      ingredient_evidence_mode,
      ingredient_original_text_hash,
      ingredient_corrections,
      updated_at
    ) VALUES (
      v_review_key,
      v_alias->>'alias_formula_key',
      v_formula.formula_key,
      v_target_brand,
      v_alias->>'retailer_title',
      v_alias->>'retailer_title',
      jsonb_build_array(
        v_alias->>'source_url',
        v_alias->>'retailer_front_image_url',
        v_alias->>'official_source_url',
        COALESCE(
          v_alias->>'official_database_image_url',
          v_alias->>'official_image_url'
        )
      ),
      v_alias->>'official_source_url',
      'manufacturer_page',
      jsonb_build_object(
        'alias_formula_key', v_alias->>'alias_formula_key',
        'retailer_source_slug', v_alias->>'retailer_source_slug',
        'retailer_product_id', v_alias->>'retailer_product_id',
        'retailer_title', v_alias->>'retailer_title',
        'retailer_source_url', v_alias->>'source_url',
        'retailer_identity_only', TRUE,
        'retailer_ingredient_verification', FALSE,
        'retailer_front_image_url', v_alias->>'retailer_front_image_url',
        'retailer_front_image_sha256',
          v_alias->>'retailer_front_image_sha256',
        'manual_package_image_match',
          COALESCE((v_alias->>'manual_package_image_match')::BOOLEAN, FALSE),
        'manual_front_label_ocr_match',
          COALESCE((v_alias->>'manual_front_label_ocr_match')::BOOLEAN, FALSE),
        'manual_front_label_visual_match',
          COALESCE((v_alias->>'manual_front_label_visual_match')::BOOLEAN, FALSE),
        'retailer_front_label_ocr', v_alias->>'retailer_front_label_ocr',
        'official_front_label_ocr', v_alias->>'official_front_label_ocr',
        'required_ocr_terms', COALESCE(v_alias->'required_ocr_terms', '[]'::jsonb),
        'required_title_terms',
          COALESCE(v_alias->'required_title_terms', '[]'::jsonb),
        'protected_identity_terms',
          COALESCE(v_alias->'protected_identity_terms', '[]'::jsonb),
        'retailer_package_identifier',
          v_alias->>'retailer_package_identifier',
        'official_package_identifier',
          v_alias->>'official_package_identifier',
        'target_cache_key', v_serving.cache_key,
        'audit_artifact', 'outputs/catalog-deterministic-reconciliation-batches/20260809-nutrish-public-front-ocr-wave-a/report.json'
      ),
      jsonb_build_object(
        'formula_id', v_formula.id,
        'formula_key', v_formula.formula_key,
        'cache_key', v_serving.cache_key,
        'official_source_url', v_alias->>'official_source_url',
        'official_image_url', COALESCE(
          v_alias->>'official_database_image_url',
          v_alias->>'official_image_url'
        ),
        'official_ingredient_count',
          (v_alias->>'official_ingredient_count')::INTEGER,
        'official_database_ingredient_hash',
          v_alias->>'official_database_ingredient_hash',
        'official_canonical_ingredient_hash',
          v_alias->>'official_canonical_ingredient_hash',
        'audit_artifact', 'outputs/catalog-deterministic-reconciliation-batches/20260809-nutrish-public-front-ocr-wave-a/report.json'
      ),
      'staged',
      NULL,
      encode(digest(
        (v_alias->>'source_url') || '|' ||
        (v_alias->>'retailer_title') || '|' ||
        (v_alias->>'official_source_url') || '|' ||
        (v_alias->>'official_database_ingredient_hash'),
        'sha256'
      ), 'hex'),
      v_alias->>'official_canonical_ingredient_hash',
      encode(digest(COALESCE(
        v_alias->>'official_database_image_url',
        v_alias->>'official_image_url'
      ), 'sha256'), 'hex'),
      (v_alias->>'retailer_observed_at')::TIMESTAMPTZ,
      NULL,
      v_serving.cache_key,
      1,
      'Exact retailer identity staged for reconciliation to one manufacturer-current formula. Retailer evidence is identity-only and does not verify ingredients or images.',
      v_alias->>'official_source_url',
      'source_text_exact',
      v_alias->>'official_database_ingredient_hash',
      '[]'::jsonb,
      NOW()
    )
    ON CONFLICT (review_key) DO UPDATE
    SET target_formula_key = EXCLUDED.target_formula_key,
        corrected_formula_key = EXCLUDED.corrected_formula_key,
        discovery_urls = EXCLUDED.discovery_urls,
        authoritative_source_url = EXCLUDED.authoritative_source_url,
        expected_identity = EXCLUDED.expected_identity,
        resolved_identity = EXCLUDED.resolved_identity,
        evidence_status = 'staged',
        quarantine_reason = NULL,
        authoritative_content_hash = EXCLUDED.authoritative_content_hash,
        ingredient_text_hash = EXCLUDED.ingredient_text_hash,
        front_image_url_hash = EXCLUDED.front_image_url_hash,
        observed_at = EXCLUDED.observed_at,
        formula_id = NULL,
        promoted_cache_key = EXCLUDED.promoted_cache_key,
        attempt_count = public.catalog_manual_evidence_reviews.attempt_count + 1,
        review_notes = EXCLUDED.review_notes,
        ingredient_evidence_url = EXCLUDED.ingredient_evidence_url,
        ingredient_evidence_mode = EXCLUDED.ingredient_evidence_mode,
        ingredient_original_text_hash = EXCLUDED.ingredient_original_text_hash,
        ingredient_corrections = EXCLUDED.ingredient_corrections,
        updated_at = NOW();

    INSERT INTO public.catalog_formula_aliases (
      alias_formula_key,
      formula_id,
      identity_hash,
      match_reason,
      source_url,
      metadata,
      updated_at
    ) VALUES (
      v_alias->>'alias_formula_key',
      v_formula.id,
      v_formula.identity_hash,
      'manual_review',
      v_alias->>'source_url',
      jsonb_build_object(
        'reason', v_alias->>'review_reason',
        'review_method', v_alias->>'review_method',
        'reviewed_at', v_alias->>'reviewed_at',
        'retailer_identity_only', TRUE,
        'retailer_ingredient_verification', FALSE,
        'retailer_source_slug', v_alias->>'retailer_source_slug',
        'retailer_product_id', v_alias->>'retailer_product_id',
        'retailer_title', v_alias->>'retailer_title',
        'retailer_observed_at', v_alias->>'retailer_observed_at',
        'retailer_front_image_url', v_alias->>'retailer_front_image_url',
        'retailer_front_image_sha256', v_alias->>'retailer_front_image_sha256',
        'manual_package_image_match',
          COALESCE((v_alias->>'manual_package_image_match')::BOOLEAN, FALSE),
        'manual_front_label_ocr_match',
          COALESCE((v_alias->>'manual_front_label_ocr_match')::BOOLEAN, FALSE),
        'manual_front_label_visual_match',
          COALESCE((v_alias->>'manual_front_label_visual_match')::BOOLEAN, FALSE),
        'required_ocr_terms', COALESCE(v_alias->'required_ocr_terms', '[]'::jsonb),
        'required_title_terms',
          COALESCE(v_alias->'required_title_terms', '[]'::jsonb),
        'protected_identity_terms',
          COALESCE(v_alias->'protected_identity_terms', '[]'::jsonb),
        'retailer_front_label_ocr', v_alias->>'retailer_front_label_ocr',
        'official_front_label_ocr', v_alias->>'official_front_label_ocr',
        'retailer_package_identifier',
          v_alias->>'retailer_package_identifier',
        'official_package_identifier',
          v_alias->>'official_package_identifier',
        'official_artifact_image_sha256',
          v_alias->>'official_artifact_image_sha256',
        'official_source_url', v_alias->>'official_source_url',
        'official_ingredient_hash', v_alias->>'official_canonical_ingredient_hash',
        'official_canonical_ingredient_hash',
          v_alias->>'official_canonical_ingredient_hash',
        'official_database_ingredient_hash',
          v_alias->>'official_database_ingredient_hash',
        'package_size_is_sku_only', TRUE,
        'audit_artifact', 'outputs/catalog-deterministic-reconciliation-batches/20260809-nutrish-public-front-ocr-wave-a/report.json'
      ),
      NOW()
    )
    ON CONFLICT (alias_formula_key) DO UPDATE
    SET source_url = EXCLUDED.source_url,
        metadata = public.catalog_formula_aliases.metadata || EXCLUDED.metadata,
        updated_at = NOW()
    WHERE public.catalog_formula_aliases.formula_id = EXCLUDED.formula_id;

    INSERT INTO public.catalog_verified_product_search_aliases (
      cache_key,
      alias_text,
      normalized_alias,
      source_url,
      source_authority,
      evidence_observed_at,
      provenance,
      active,
      updated_at
    ) VALUES (
      v_serving.cache_key,
      v_alias->>'retailer_title',
      v_normalized_alias,
      v_alias->>'source_url',
      'retailer_identity',
      (v_alias->>'retailer_observed_at')::TIMESTAMPTZ,
      jsonb_build_object(
        'review_key', v_review_key,
        'review_method', v_alias->>'review_method',
        'retailer_identity_only', TRUE,
        'retailer_ingredient_verification', FALSE,
        'retailer_source_slug', v_alias->>'retailer_source_slug',
        'retailer_product_id', v_alias->>'retailer_product_id',
        'manual_package_image_match',
          COALESCE((v_alias->>'manual_package_image_match')::BOOLEAN, FALSE),
        'manual_front_label_ocr_match',
          COALESCE((v_alias->>'manual_front_label_ocr_match')::BOOLEAN, FALSE),
        'manual_front_label_visual_match',
          COALESCE((v_alias->>'manual_front_label_visual_match')::BOOLEAN, FALSE),
        'formula_id', v_formula.id,
        'official_source_url', v_alias->>'official_source_url',
        'official_database_ingredient_hash',
          v_alias->>'official_database_ingredient_hash',
        'audit_artifact', 'outputs/catalog-deterministic-reconciliation-batches/20260809-nutrish-public-front-ocr-wave-a/report.json'
      ),
      TRUE,
      NOW()
    )
    ON CONFLICT (normalized_alias) WHERE active DO UPDATE
    SET cache_key = EXCLUDED.cache_key,
        alias_text = EXCLUDED.alias_text,
        source_url = EXCLUDED.source_url,
        source_authority = EXCLUDED.source_authority,
        evidence_observed_at = EXCLUDED.evidence_observed_at,
        provenance = public.catalog_verified_product_search_aliases.provenance
          || EXCLUDED.provenance,
        updated_at = NOW()
    WHERE public.catalog_verified_product_search_aliases.cache_key =
      EXCLUDED.cache_key;

    INSERT INTO public.catalog_field_evidence (
      formula_id,
      observation_id,
      field_name,
      field_value,
      source_url,
      source_authority,
      accepted,
      observed_at,
      content_hash
    ) VALUES (
      v_formula.id,
      v_observation_id,
      'retailer_exact_identity_alias',
      jsonb_build_object(
        'review_key', v_review_key,
        'alias_formula_key', v_alias->>'alias_formula_key',
        'review_method', v_alias->>'review_method',
        'retailer_identity_only', TRUE,
        'retailer_ingredient_verification', FALSE,
        'retailer_source_slug', v_alias->>'retailer_source_slug',
        'retailer_product_id', v_alias->>'retailer_product_id',
        'retailer_title', v_alias->>'retailer_title',
        'retailer_front_image_url', v_alias->>'retailer_front_image_url',
        'retailer_front_image_sha256',
          v_alias->>'retailer_front_image_sha256',
        'manual_package_image_match',
          COALESCE((v_alias->>'manual_package_image_match')::BOOLEAN, FALSE),
        'manual_front_label_ocr_match',
          COALESCE((v_alias->>'manual_front_label_ocr_match')::BOOLEAN, FALSE),
        'manual_front_label_visual_match',
          COALESCE((v_alias->>'manual_front_label_visual_match')::BOOLEAN, FALSE),
        'retailer_front_label_ocr', v_alias->>'retailer_front_label_ocr',
        'official_front_label_ocr', v_alias->>'official_front_label_ocr',
        'required_ocr_terms', COALESCE(v_alias->'required_ocr_terms', '[]'::jsonb),
        'required_title_terms',
          COALESCE(v_alias->'required_title_terms', '[]'::jsonb),
        'protected_identity_terms',
          COALESCE(v_alias->'protected_identity_terms', '[]'::jsonb),
        'retailer_package_identifier',
          v_alias->>'retailer_package_identifier',
        'official_package_identifier',
          v_alias->>'official_package_identifier',
        'official_source_url', v_alias->>'official_source_url',
        'official_database_ingredient_hash',
          v_alias->>'official_database_ingredient_hash',
        'official_canonical_ingredient_hash',
          v_alias->>'official_canonical_ingredient_hash',
        'audit_artifact', 'outputs/catalog-deterministic-reconciliation-batches/20260809-nutrish-public-front-ocr-wave-a/report.json'
      ),
      v_alias->>'source_url',
      'retailer_identity',
      TRUE,
      (v_alias->>'retailer_observed_at')::TIMESTAMPTZ,
      encode(digest(
        v_formula.id::TEXT || '|retailer_exact_identity_alias|' ||
        (v_alias->>'alias_formula_key') || '|' ||
        (v_alias->>'source_url') || '|' ||
        (v_alias->>'official_database_ingredient_hash'),
        'sha256'
      ), 'hex')
    )
    ON CONFLICT (formula_id, field_name, source_url, content_hash) DO UPDATE
    SET observation_id = EXCLUDED.observation_id,
        field_value = EXCLUDED.field_value,
        source_authority = EXCLUDED.source_authority,
        accepted = TRUE,
        observed_at = EXCLUDED.observed_at;

    UPDATE public.catalog_manual_evidence_reviews
    SET evidence_status = 'promoted',
        formula_id = v_formula.id,
        corrected_formula_key = v_formula.formula_key,
        promoted_cache_key = v_serving.cache_key,
        review_notes = review_notes ||
          ' Reconciliation, field evidence, and exact-title search alias promoted; serving evidence unchanged.',
        updated_at = NOW()
    WHERE review_key = v_review_key
      AND evidence_status = 'staged';

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Staged evidence review did not promote: %', v_review_key;
    END IF;

    SELECT result.cache_key
    INTO v_top_cache
    FROM public.search_verified_products(v_alias->>'retailer_title', 8) result
    ORDER BY result.rank DESC
    LIMIT 1;

    IF v_top_cache IS DISTINCT FROM v_serving.cache_key THEN
      RAISE EXCEPTION 'Exact-title search regression for %: expected %, got %',
        v_alias->>'retailer_product_id', v_serving.cache_key, v_top_cache;
    END IF;
  END LOOP;

  IF (SELECT count(*) FROM public.catalog_formula_aliases
      WHERE metadata->>'audit_artifact' = 'outputs/catalog-deterministic-reconciliation-batches/20260809-nutrish-public-front-ocr-wave-a/report.json') <>
      jsonb_array_length(v_payload)
     OR (SELECT count(*) FROM public.catalog_manual_evidence_reviews
         WHERE review_key LIKE
           'deterministic-retailer-identity-wave-nutrish_public_front_ocr_a:%'
           AND evidence_status = 'promoted'
           AND formula_id IS NOT NULL) <> jsonb_array_length(v_payload)
     OR (SELECT count(*) FROM public.catalog_verified_product_search_aliases
         WHERE active
           AND provenance->>'audit_artifact' = 'outputs/catalog-deterministic-reconciliation-batches/20260809-nutrish-public-front-ocr-wave-a/report.json') <>
           jsonb_array_length(v_payload)
     OR (SELECT count(*) FROM public.catalog_field_evidence
         WHERE accepted
           AND field_name = 'retailer_exact_identity_alias'
           AND field_value->>'audit_artifact' = 'outputs/catalog-deterministic-reconciliation-batches/20260809-nutrish-public-front-ocr-wave-a/report.json') <>
           jsonb_array_length(v_payload) THEN
    RAISE EXCEPTION 'Wave nutrish_public_front_ocr_a evidence promotion postcondition failed';
  END IF;
END
$migration$;
