INSERT INTO public.catalog_coverage_snapshots (
  snapshot_key, census_started_at, census_completed_at, source_panel,
  required_source_panel, completed_source_panel, denominator_formula_count,
  verified_formula_count, verified_formula_percent, popular_brand_count,
  complete_popular_brand_count, popular_formula_gap_count,
  ingredient_verified_percent, image_verified_percent,
  independent_denominator, passes_source_panel, passes_total_coverage,
  passes_popular_brands, passes_release_gate, details
) VALUES (
  'public-reviewed-major95-target-nutro-v194:20260727',
  '2026-07-27T19:33:03.792Z', '2026-07-27T19:50:24.306Z',
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap',
    'petco-retail-catalog','amazon-retail-catalog'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  9684, 6895, 71.20, 86, 42, 2789, 71.20, 71.20,
  true, false, false, false, false,
  jsonb_build_object(
    'searchable_web_evidenced_count', 6895,
    'manufacturer_current_exact_count', 4938,
    'retailer_web_version_count', 1819,
    'web_label_version_count', 138,
    'unresolved_formula_count', 2789,
    'reviewed_target_nutro_clean_package_count_v192', 16,
    'reviewed_target_nutro_formula_version_count_v192', 12,
    'promoted_retailer_web_version_formula_count_v193', 8,
    'manufacturer_current_equivalent_package_count_v193', 6,
    'retired_equivalent_size_family_duplicate_count_v194', 2,
    'remaining_distinct_target_nutro_source_version_count_v194', 6,
    'reused_or_incompatible_gtin_abstention_count_v194', 10,
    'unsafe_ingredient_transcription_quarantine_count_v192', 1,
    'nutro_formula_count', 212,
    'nutro_searchable_formula_count', 122,
    'nutro_formula_gap_count', 90,
    'target_formula_count', 508,
    'target_searchable_formula_count', 279,
    'target_formula_gap_count', 229,
    'major95_formula_count', 9103,
    'major95_searchable_formula_count', 6314,
    'major95_formula_gap_count', 2789,
    'major95_inventory_continuity_failure_count', 0,
    'major95_release_complete_brand_count', 18,
    'formula_version_policy',
      'retailer_web_version and web_label_version remain source-versioned records with URL, package identifier, capture date, image, and full ingredients; exact ingredient-equivalent size families link to one canonical manufacturer-current formula; reused or incompatible GTINs abstain',
    'source_evidence_artifacts',
      jsonb_build_array(
        'outputs/catalog-source-imports/target-nutro-gap-wave-v192-20260727/frozen/source-evidence-8a0c8d6dbaa6b92688fbd53f.json'
      ),
    'coverage_report',
      'outputs/catalog-market-leaders/brand-coverage-sprint-current-major95-target-nutro-v194-20260727-sprint/WAVE_REPORT.md',
    'missing_source_panel',
      jsonb_build_array('petco-retail-catalog','amazon-retail-catalog'),
    'second_census_seven_days_apart', false,
    'eric_physical_device_validation', false
  )
)
ON CONFLICT (snapshot_key) DO UPDATE SET
  census_completed_at = excluded.census_completed_at,
  denominator_formula_count = excluded.denominator_formula_count,
  verified_formula_count = excluded.verified_formula_count,
  verified_formula_percent = excluded.verified_formula_percent,
  complete_popular_brand_count = excluded.complete_popular_brand_count,
  popular_formula_gap_count = excluded.popular_formula_gap_count,
  ingredient_verified_percent = excluded.ingredient_verified_percent,
  image_verified_percent = excluded.image_verified_percent,
  passes_source_panel = excluded.passes_source_panel,
  passes_total_coverage = excluded.passes_total_coverage,
  passes_popular_brands = excluded.passes_popular_brands,
  passes_release_gate = excluded.passes_release_gate,
  details = excluded.details;
