INSERT INTO public.catalog_coverage_snapshots (
  snapshot_key, census_started_at, census_completed_at, source_panel,
  required_source_panel, completed_source_panel, denominator_formula_count,
  verified_formula_count, verified_formula_percent, popular_brand_count,
  complete_popular_brand_count, popular_formula_gap_count,
  ingredient_verified_percent, image_verified_percent,
  independent_denominator, passes_source_panel, passes_total_coverage,
  passes_popular_brands, passes_release_gate, details
) VALUES (
  'public-reviewed-major95-target-cesar-pedigree-v190:20260727',
  '2026-07-27T19:07:26.531Z', '2026-07-27T19:26:10.630Z',
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap',
    'petco-retail-catalog','amazon-retail-catalog'],
  ARRAY['manufacturer-catalogs','petsmart-retail-catalog',
    'chewy-public-sitemap','target-public-sitemap','walmart-public-sitemap'],
  9688, 6894, 71.16, 86, 42, 2794, 71.16, 71.16,
  true, false, false, false, false,
  jsonb_build_object(
    'searchable_web_evidenced_count', 6894,
    'manufacturer_current_exact_count', 4938,
    'retailer_web_version_count', 1818,
    'web_label_version_count', 138,
    'unresolved_formula_count', 2794,
    'reviewed_target_cesar_package_count_v188', 8,
    'reviewed_target_pedigree_package_count_v189', 17,
    'promoted_retailer_web_version_count_v190', 24,
    'manufacturer_current_equivalent_package_count_v190', 1,
    'cesar_formula_count', 109,
    'cesar_searchable_formula_count', 57,
    'cesar_formula_gap_count', 52,
    'pedigree_formula_count', 175,
    'pedigree_searchable_formula_count', 82,
    'pedigree_formula_gap_count', 93,
    'target_formula_count', 508,
    'target_searchable_formula_count', 275,
    'target_formula_gap_count', 233,
    'major95_formula_count', 9107,
    'major95_searchable_formula_count', 6313,
    'major95_formula_gap_count', 2794,
    'major95_inventory_continuity_failure_count', 0,
    'major95_release_complete_brand_count', 18,
    'multi_formula_exclusion',
      'Pedigree TCIN 80633938 excluded after counted Chicken and Duck / Beef and Bison component ingredient headings were detected',
    'formula_version_policy',
      'retailer_web_version and web_label_version remain source-versioned records with URL, package identifier, capture date, image, and full ingredients; never overwrite a different manufacturer-current ingredient version',
    'source_evidence_artifacts',
      jsonb_build_array(
        'outputs/catalog-source-imports/target-cesar-gap-wave-v188-20260727/frozen/source-evidence-47576fec7db1c158f6dbfc21.json',
        'outputs/catalog-source-imports/target-pedigree-gap-wave-v189-20260727/frozen/source-evidence-d313489ed1446ce724a68b82.json'
      ),
    'coverage_report',
      'outputs/catalog-market-leaders/brand-coverage-sprint-current-major95-target-cesar-pedigree-v190-20260727-sprint/WAVE_REPORT.md',
    'missing_source_panel',
      jsonb_build_array('petco-retail-catalog','amazon-retail-catalog'),
    'second_census_seven_days_apart', false,
    'eric_physical_device_validation', false
  )
)
ON CONFLICT (snapshot_key) DO UPDATE SET
  census_completed_at = excluded.census_completed_at,
  denominator_formula_count = excluded.denominator_formula_count,
  verified_formula_count = excluded.verified_formula_count,
  verified_formula_percent = excluded.verified_formula_percent,
  complete_popular_brand_count = excluded.complete_popular_brand_count,
  popular_formula_gap_count = excluded.popular_formula_gap_count,
  ingredient_verified_percent = excluded.ingredient_verified_percent,
  image_verified_percent = excluded.image_verified_percent,
  passes_source_panel = excluded.passes_source_panel,
  passes_total_coverage = excluded.passes_total_coverage,
  passes_popular_brands = excluded.passes_popular_brands,
  passes_release_gate = excluded.passes_release_gate,
  details = excluded.details;
